
	Select
  cmn_bpt_str_office_settingsprofile.CMN_BPT_STR_Office_SettingsProfileID,
  cmn_bpt_str_office_settingsprofile.Office_RefID,
  cmn_bpt_str_office_settingsprofile.AdulthoodAge,
  cmn_bpt_str_office_settingsprofile.RestMinimumThresholdl_NonAdults_in_mins,
  cmn_bpt_str_office_settingsprofile.RestWarningThreshold_NonAdults_in_mins,
  cmn_bpt_str_office_settingsprofile.RestWarningThreshold_Adults_in_mins,
  cmn_bpt_str_office_settingsprofile.RestMinimumThresholdl_Adults_in_mins,
  cmn_bpt_str_office_settingsprofile.WorkTimeWarningTreshold_Adults_in_mins,
  cmn_bpt_str_office_settingsprofile.WorkTimeWarningTreshold_NonAdults_in_mins,
  cmn_bpt_str_office_settingsprofile.WorkTimeMaximumTreshold_Adults_in_mins,
  cmn_bpt_str_office_settingsprofile.WorkTimeMaximumTreshold_NonAdults_in_mins,
  cmn_bpt_str_office_settingsprofile.WorkStartTimeWarning_NonAdults_in_mins,
  cmn_bpt_str_office_settingsprofile.WorkStartTimeMinimum_NonAdults_in_mins,
  cmn_bpt_str_office_settingsprofile.WorkEndTimeWarning_NonAdults_in_mins,
  cmn_bpt_str_office_settingsprofile.WorkEndTimeMaximum_NonAdults_in_mins,
  cmn_bpt_str_office_settingsprofile.WorktimeBalancePeriod_in_months,
  cmn_bpt_str_office_settingsprofile.WorkdayStart_in_mins,
  cmn_bpt_str_office_settingsprofile.RoosterGridMinimumPlanningUnit_in_mins,
  cmn_bpt_str_office_settingsprofile.MaximumPreWork_Period_in_mins,
  cmn_bpt_str_office_settingsprofile.MaximumPostWork_Period_in_mins
From
  cmn_bpt_str_office_settingsprofile
Where
  cmn_bpt_str_office_settingsprofile.IsDeleted = 0 And
  cmn_bpt_str_office_settingsprofile.Tenant_RefID = @TenantID
  