INSERT INTO 
	res_qst_questionnaire_version
	(
		RES_QST_Questionnaire_VersionID,
		Questionnaire_RefID,
		QuestionnaireVersion_Comment,
		QuestionnaireVersion_VersionNumber,
		IsApartmentStructureVisible,
		IsStaircaseStructureVisible,
		IsOutdoorFacilityVisible,
		IsFacadeVisible,
		IsRoofVisible,
		IsAtticVisible,
		IsBasementVisible,
		IsHVACRVisible,
		Creation_Timestamp,
		IsDeleted,
		Tenant_RefID
	)
VALUES 
	(
		@RES_QST_Questionnaire_VersionID,
		@Questionnaire_RefID,
		@QuestionnaireVersion_Comment,
		@QuestionnaireVersion_VersionNumber,
		@IsApartmentStructureVisible,
		@IsStaircaseStructureVisible,
		@IsOutdoorFacilityVisible,
		@IsFacadeVisible,
		@IsRoofVisible,
		@IsAtticVisible,
		@IsBasementVisible,
		@IsHVACRVisible,
		@Creation_Timestamp,
		@IsDeleted,
		@Tenant_RefID
	)