INSERT INTO 
	ord_prc_rfp_potentialsupplier_history
	(
		ORD_PRC_RFP_PotentialSupplier_HistoryID,
		ORD_PRC_RFP_PotentialSupplier_RefID,
		IsEvent_ProposalRequest_Sent,
		IsEvent_ProposalRequest_Revoked,
		IsEvent_BySupplier_ProposalRequest_ReceptionAcknowledged,
		IsEvent_BySupplier_ProposalRequest_Declined,
		IsEvent_ProposalResponse_Received,
		IsEvent_ProposalResponse_ReceptionAcknowledged,
		IsEvent_BySupplier_ProposalResponse_Revoked,
		IsEvent_ProposalResponse_ModificationRequired,
		IsEvent_ProposalResponse_Declined,
		IsEvent_ProposalResponse_Accepted,
		Proposal_Document_RefID,
		Comment,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@ORD_PRC_RFP_PotentialSupplier_HistoryID,
		@ORD_PRC_RFP_PotentialSupplier_RefID,
		@IsEvent_ProposalRequest_Sent,
		@IsEvent_ProposalRequest_Revoked,
		@IsEvent_BySupplier_ProposalRequest_ReceptionAcknowledged,
		@IsEvent_BySupplier_ProposalRequest_Declined,
		@IsEvent_ProposalResponse_Received,
		@IsEvent_ProposalResponse_ReceptionAcknowledged,
		@IsEvent_BySupplier_ProposalResponse_Revoked,
		@IsEvent_ProposalResponse_ModificationRequired,
		@IsEvent_ProposalResponse_Declined,
		@IsEvent_ProposalResponse_Accepted,
		@Proposal_Document_RefID,
		@Comment,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)