INSERT INTO 
	ocl_ordercollective_members
	(
		OCL_OrderCollective_MemberID,
		OrderCollective_RefID,
		OrderCollectiveMemberITL,
		IsOrderCollectiveLead,
		BusinessParticipant_RefID,
		MemberSince,
		EndOfMembership,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@OCL_OrderCollective_MemberID,
		@OrderCollective_RefID,
		@OrderCollectiveMemberITL,
		@IsOrderCollectiveLead,
		@BusinessParticipant_RefID,
		@MemberSince,
		@EndOfMembership,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)