INSERT INTO 
	hec_act_usedproducts
	(
		HEC_ACT_UsedProductID,
		HEC_ACT_PerformedAction_RefID,
		UsedIn_Procedure_RefID,
		Relevant_PatientDiagnosis_RefID,
		IsHealthcare,
		IsHealthcareProduct,
		HEC_Product_RefID,
		IsSubstance,
		IfSubstance_Strength,
		IfSubstance_Unit_RefID,
		IfSubstance_Substance_RefiD,
		Quantity,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@HEC_ACT_UsedProductID,
		@HEC_ACT_PerformedAction_RefID,
		@UsedIn_Procedure_RefID,
		@Relevant_PatientDiagnosis_RefID,
		@IsHealthcare,
		@IsHealthcareProduct,
		@HEC_Product_RefID,
		@IsSubstance,
		@IfSubstance_Strength,
		@IfSubstance_Unit_RefID,
		@IfSubstance_Substance_RefiD,
		@Quantity,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)