UPDATE 
	hec_act_usedproducts
SET 
	HEC_ACT_PerformedAction_RefID=@HEC_ACT_PerformedAction_RefID,
	UsedIn_Procedure_RefID=@UsedIn_Procedure_RefID,
	Relevant_PatientDiagnosis_RefID=@Relevant_PatientDiagnosis_RefID,
	IsHealthcare=@IsHealthcare,
	IsHealthcareProduct=@IsHealthcareProduct,
	HEC_Product_RefID=@HEC_Product_RefID,
	IsSubstance=@IsSubstance,
	IfSubstance_Strength=@IfSubstance_Strength,
	IfSubstance_Unit_RefID=@IfSubstance_Unit_RefID,
	IfSubstance_Substance_RefiD=@IfSubstance_Substance_RefiD,
	Quantity=@Quantity,
	Creation_Timestamp=@Creation_Timestamp,
	Tenant_RefID=@Tenant_RefID,
	IsDeleted=@IsDeleted,
	Modification_Timestamp=@Modification_Timestamp
WHERE 
	HEC_ACT_UsedProductID = @HEC_ACT_UsedProductID