(function () {
    'use strict';
    angular.module('mainModule').service('documentationOnlyService', ['ajaxService', 'ngDialog', 'planningService', 'alertService', 'commonServices',
        function (ajaxService, ngDialog, planningService, alertService, commonServices) {
            //-------------------------------------------------GET---------------------------------------------------//

            this.getExistingData = function (patient_id, successFunction, errorFunction) {
                ajaxService.AjaxGetWithData({ patient_id: patient_id }, "api/documentationOnly/GetDocumentationOnlyOpAndOctData", successFunction, errorFunction);
            };

            this.getExistingCasesForPatient = function (patient_id, successFunction, errorFunction) {
                ajaxService.AjaxGetWithData({ patient_id: patient_id }, "api/documentationOnly/GetExistingCasesForPatient", successFunction, errorFunction);
            };

            //------------------------------------------------POST--------------------------------------------------//
            this.saveData = function (parameter, successFunction, errorFunction) {
                ajaxService.AjaxPost(parameter, "api/documentationOnly/SaveDocumentationOnlyOpAndOctData", successFunction, errorFunction);
            };


            //-----------------------------------------------WIZARD--------------------------------------------------//
            this.openWizard = function (patient, scope) {
                ngDialog.open({
                    template: 'scripts/src/app/patient/view/addRetroCases.html',
                    controller: ['$scope', '$filter', '$routeParams', '$rootScope', 'diagnosesService', 'drugsService', 'alertService', 'documentationOnlyService', 'ngDialog', 'patient', 'doctorsService', addRetroCasesPopupController],
                    scope: scope,
                    resolve: {
                        patient: function () {
                            return patient;
                        }
                    }
                });
            }


            this.showExistingAutoGeneratedIvomMessage = function (patient_id, $scope) {
                commonServices.open_wizard_for_patient = patient_id;
                alertService.RenderNotificationMessage([{ message: 'LABEL_CANT_SUBMIT_OCT_SINCE_IVOM_AUTO_GENERATED' }], $scope, function () {
                    ngDialog.close();
                }, {
                    url: '/patient/patient_detail/' + patient_id + '/',
                    urlButtonMessage: 'LABEL_GO_TO_PATIENT_DETAILS_OPEN_WIZARD'
                });
            }
        }]);
})();
