INSERT INTO 
	ord_prc_shoppingcart_products
	(
		ORD_PRC_ShoppingCart_ProductID,
		ORD_PRC_ShoppingCart_RefID,
		CMN_PRO_Product_RefID,
		CMN_PRO_Product_Variant_RefID,
		CMN_PRO_Product_Release_RefID,
		SequenceNumber,
		Quantity,
		IsCanceled,
		Comment,
		IsProductReplacementAllowed,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@ORD_PRC_ShoppingCart_ProductID,
		@ORD_PRC_ShoppingCart_RefID,
		@CMN_PRO_Product_RefID,
		@CMN_PRO_Product_Variant_RefID,
		@CMN_PRO_Product_Release_RefID,
		@SequenceNumber,
		@Quantity,
		@IsCanceled,
		@Comment,
		@IsProductReplacementAllowed,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)