INSERT INTO 
	bil_billheaders
	(
		BIL_BillHeaderID,
		BillRecipient_BuisnessParticipant_RefID,
		CreatedBy_BusinessParticipant_RefID,
		Currency_RefID,
		BillNumber,
		DateOnBill,
		TotalValue_BeforeTax,
		TotalValue_IncludingTax,
		SourceEconomicRegion_RefID,
		TargetEconomicRegion_RefID,
		BillingAddress_UCD_RefID,
		BillHeader_PaymentCondition_RefID,
		BillComment,
		IsFullyPaid,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@BIL_BillHeaderID,
		@BillRecipient_BuisnessParticipant_RefID,
		@CreatedBy_BusinessParticipant_RefID,
		@Currency_RefID,
		@BillNumber,
		@DateOnBill,
		@TotalValue_BeforeTax,
		@TotalValue_IncludingTax,
		@SourceEconomicRegion_RefID,
		@TargetEconomicRegion_RefID,
		@BillingAddress_UCD_RefID,
		@BillHeader_PaymentCondition_RefID,
		@BillComment,
		@IsFullyPaid,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)