INSERT INTO 
	tms_quicktasks
	(
		TMS_QuickTaskID,
		IdentificationNumber,
		IsManuallyEntered,
		QuickTask_Title_DictID,
		QuickTask_Description_DictID,
		QuickTask_Type_RefID,
		R_QuickTask_InvestedTime_min,
		QuickTask_CreatedByAccount_RefID,
		QuickTask_DocumentStructureHeader_RefID,
		QuickTask_StartTime,
		AssignedTo_Project_RefID,
		AssignedTo_BusinessTask_RefID,
		AssignedTo_Feature_RefID,
		AssignedTo_DeveloperTask_RefID,
		Tenant_RefID,
		Creation_Timestamp,
		IsDeleted
	)
VALUES 
	(
		@TMS_QuickTaskID,
		@IdentificationNumber,
		@IsManuallyEntered,
		@QuickTask_Title,
		@QuickTask_Description,
		@QuickTask_Type_RefID,
		@R_QuickTask_InvestedTime_min,
		@QuickTask_CreatedByAccount_RefID,
		@QuickTask_DocumentStructureHeader_RefID,
		@QuickTask_StartTime,
		@AssignedTo_Project_RefID,
		@AssignedTo_BusinessTask_RefID,
		@AssignedTo_Feature_RefID,
		@AssignedTo_DeveloperTask_RefID,
		@Tenant_RefID,
		@Creation_Timestamp,
		@IsDeleted
	)