SELECT *
FROM 
	hec_ctr_i2bc_coveredpotentialbillcodes_universalproperties
WHERE 
	HEC_CTR_I2BC_CoveredPotentialBillCodes_UniversalPropertyID = @HEC_CTR_I2BC_CoveredPotentialBillCodes_UniversalPropertyID