INSERT INTO 
	tms_pro_developertask_involvements
	(
		TMS_PRO_DeveloperTask_InvolvementID,
		ProjectMember_RefID,
		DeveloperTask_RefID,
		OrderSequence,
		IsActive,
		IsArchived,
		R_InvestedWorkingTime_min,
		Developer_CompletionTimeEstimation_min,
		Creation_Timestamp,
		IsDeleted,
		Tenant_RefID
	)
VALUES 
	(
		@TMS_PRO_DeveloperTask_InvolvementID,
		@ProjectMember_RefID,
		@DeveloperTask_RefID,
		@OrderSequence,
		@IsActive,
		@IsArchived,
		@R_InvestedWorkingTime_min,
		@Developer_CompletionTimeEstimation_min,
		@Creation_Timestamp,
		@IsDeleted,
		@Tenant_RefID
	)