INSERT INTO 
	cmn_str_pps_shiftplan_days_employeeapplications
	(
		CMN_STR_PPS_ShiftPlan_Days_EmployeeApplicationID,
		CMN_STR_PPS_ShiftPlan_Day_ShiftTemplate_RefID,
		Employee_RefID,
		IsApproved,
		IfApproved_ByBusinessParticipant_RefID,
		IfApproved_DailyWorkSchedule_RefID,
		IsDenied,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@CMN_STR_PPS_ShiftPlan_Days_EmployeeApplicationID,
		@CMN_STR_PPS_ShiftPlan_Day_ShiftTemplate_RefID,
		@Employee_RefID,
		@IsApproved,
		@IfApproved_ByBusinessParticipant_RefID,
		@IfApproved_DailyWorkSchedule_RefID,
		@IsDenied,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)