INSERT INTO 
	usr_device_configurationcodes
	(
		USR_Device_ConfigurationCodeID,
		DeviceConfigurationCode,
		DateOfExpiry,
		IsMultipleUsagesAllowed,
		Exclusively_UsableBy_Device_RefID,
		Preconfigured_ApplicationBaseURL,
		Preconfigured_OtherConfigurationInformation,
		Preconfigured_PrimaryUser_RefID,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@USR_Device_ConfigurationCodeID,
		@DeviceConfigurationCode,
		@DateOfExpiry,
		@IsMultipleUsagesAllowed,
		@Exclusively_UsableBy_Device_RefID,
		@Preconfigured_ApplicationBaseURL,
		@Preconfigured_OtherConfigurationInformation,
		@Preconfigured_PrimaryUser_RefID,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)