INSERT INTO 
	hec_pro_components
	(
		HEC_PRO_ComponentID,
		GlobalPropertyMatchingID,
		ComponentMatterState,
		AbsoluteCompositionValue_Unit_RefID,
		AbsoluteCompositionValue,
		RelativeCompositionValue_Unit_RefID,
		RelativeCompositionValue,
		BreadUnitContainedAmount,
		EthanolContained_VolumePercentage,
		ComponentEneryValue_in_kJ,
		Component_SimpleName,
		Component_Name_DictID,
		Component_Description_DictID,
		ComponentDisposalSpeedStatus,
		GalenicalTypeInsidePackageStatus,
		ComponentExcipientStatus,
		GalenicalType_RelativeComposition,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@HEC_PRO_ComponentID,
		@GlobalPropertyMatchingID,
		@ComponentMatterState,
		@AbsoluteCompositionValue_Unit_RefID,
		@AbsoluteCompositionValue,
		@RelativeCompositionValue_Unit_RefID,
		@RelativeCompositionValue,
		@BreadUnitContainedAmount,
		@EthanolContained_VolumePercentage,
		@ComponentEneryValue_in_kJ,
		@Component_SimpleName,
		@Component_Name,
		@Component_Description,
		@ComponentDisposalSpeedStatus,
		@GalenicalTypeInsidePackageStatus,
		@ComponentExcipientStatus,
		@GalenicalType_RelativeComposition,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)