INSERT INTO 
	res_bld_apartments
	(
		RES_BLD_ApartmentID,
		Building_RefID,
		IsAppartment_ForRent,
		ApartmentSize_Unit_RefID,
		ApartmentSize_Value,
		TypeOfHeating_RefID,
		TypeOfFlooring_RefID,
		TypeOfWallCovering_RefID,
		Creation_Timestamp,
		IsDeleted,
		Tenant_RefID
	)
VALUES 
	(
		@RES_BLD_ApartmentID,
		@Building_RefID,
		@IsAppartment_ForRent,
		@ApartmentSize_Unit_RefID,
		@ApartmentSize_Value,
		@TypeOfHeating_RefID,
		@TypeOfFlooring_RefID,
		@TypeOfWallCovering_RefID,
		@Creation_Timestamp,
		@IsDeleted,
		@Tenant_RefID
	)