INSERT INTO 
	pps_tsk_task_officebookings
	(
		PPS_TSK_Task_OfficeBookingID,
		PPS_TSK_Task_RefID,
		CMN_STR_Office_RefID,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@PPS_TSK_Task_OfficeBookingID,
		@PPS_TSK_Task_RefID,
		@CMN_STR_Office_RefID,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)