INSERT INTO 
	cmn_pps_shifttemplates
	(
		CMN_PPS_ShiftTemplateID,
		ShiftTemplate_ShortName,
		ShiftTemplate_Name_DictID,
		CMN_STR_Office_RefID,
		CMN_STR_Workarea_RefID,
		CMN_STR_Workplace_RefID,
		Default_StartTime_in_sec,
		IsWorkPattern,
		Default_AllowedBreakTimeTemplate_RefID,
		DisplayColor,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@CMN_PPS_ShiftTemplateID,
		@ShiftTemplate_ShortName,
		@ShiftTemplate_Name,
		@CMN_STR_Office_RefID,
		@CMN_STR_Workarea_RefID,
		@CMN_STR_Workplace_RefID,
		@Default_StartTime_in_sec,
		@IsWorkPattern,
		@Default_AllowedBreakTimeTemplate_RefID,
		@DisplayColor,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)