INSERT INTO 
	res_qst_attic_availableproperties
	(
		RES_QST_Attic_AvailablePropertyID,
		RES_QST_Questionnaire_Version_RefID,
		RES_STR_Attic_Property_RefID,
		Creation_Timestamp,
		IsDeleted,
		Tenant_RefID
	)
VALUES 
	(
		@RES_QST_Attic_AvailablePropertyID,
		@RES_QST_Questionnaire_Version_RefID,
		@RES_STR_Attic_Property_RefID,
		@Creation_Timestamp,
		@IsDeleted,
		@Tenant_RefID
	)