INSERT INTO 
	imo_submissionbundles
	(
		IMO_SubmissionBundleID,
		WorkerAccount_RefID,
		Language_RefID,
		Bundle_Name,
		Bundle_Description,
		DueDate,
		GrabbedAtDate,
		GrabbedByAccount_RefID,
		IsGlobalBundle,
		IsCompleted,
		IsGrabbed,
		Creation_Timestamp,
		IsDeleted,
		Tenant_RefID
	)
VALUES 
	(
		@IMO_SubmissionBundleID,
		@WorkerAccount_RefID,
		@Language_RefID,
		@Bundle_Name,
		@Bundle_Description,
		@DueDate,
		@GrabbedAtDate,
		@GrabbedByAccount_RefID,
		@IsGlobalBundle,
		@IsCompleted,
		@IsGrabbed,
		@Creation_Timestamp,
		@IsDeleted,
		@Tenant_RefID
	)