INSERT INTO 
	hec_act_performedaction_diagnosisupdates
	(
		HEC_ACT_PerformedAction_DiagnosisUpdateID,
		HEC_ACT_PerformedAction_RefID,
		HEC_Patient_Diagnosis_RefID,
		PotentialDiagnosis_RefID,
		DiagnosisState_RefID,
		IsDiagnosisAssumed,
		IsDiagnosisConfirmed,
		IsDiagnosisNegated,
		IsDiagnosisCreated,
		IsDiagnosisModified,
		IsDiagnosisDeactivated,
		ScheduledExpiryDate,
		Deactivated_OnDate,
		DeactivatedBy_Doctor_RefID,
		DiagnosisUpdateComment,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@HEC_ACT_PerformedAction_DiagnosisUpdateID,
		@HEC_ACT_PerformedAction_RefID,
		@HEC_Patient_Diagnosis_RefID,
		@PotentialDiagnosis_RefID,
		@DiagnosisState_RefID,
		@IsDiagnosisAssumed,
		@IsDiagnosisConfirmed,
		@IsDiagnosisNegated,
		@IsDiagnosisCreated,
		@IsDiagnosisModified,
		@IsDiagnosisDeactivated,
		@ScheduledExpiryDate,
		@Deactivated_OnDate,
		@DeactivatedBy_Doctor_RefID,
		@DiagnosisUpdateComment,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)