INSERT INTO 
	cmn_cal_calendar_lockperiods
	(
		CMN_CAL_Calendar_LockPeriodID,
		LockPeriod_FromDate,
		LockPeriod_ToDate,
		LockPeriod_Comment,
		LockPeriod_LockedByAccount_RefID,
		IsUnlocked,
		UnlockedBy_Account_RefID,
		ReasonForUnlocking,
		Creation_Timestamp,
		IsDeleted,
		Tenant_RefID
	)
VALUES 
	(
		@CMN_CAL_Calendar_LockPeriodID,
		@LockPeriod_FromDate,
		@LockPeriod_ToDate,
		@LockPeriod_Comment,
		@LockPeriod_LockedByAccount_RefID,
		@IsUnlocked,
		@UnlockedBy_Account_RefID,
		@ReasonForUnlocking,
		@Creation_Timestamp,
		@IsDeleted,
		@Tenant_RefID
	)