INSERT INTO 
	hec_dia_potentialdiagnosis_catalogs
	(
		HEC_DIA_PotentialDiagnosis_CatalogID,
		GlobalPropertyMatchingID,
		Catalog_DisplayName,
		Catalog_Name_DictID,
		IsUsingSelfLearningPriorities,
		SelfLearningPriorities_InitializationTreshold,
		IsPrivateCatalog,
		R_InitializationTreshold_NumberOfRelevantDiagnosisPerformed,
		SelfLearningPriorities_NumberOfPastDaysTakenIntoAccount,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@HEC_DIA_PotentialDiagnosis_CatalogID,
		@GlobalPropertyMatchingID,
		@Catalog_DisplayName,
		@Catalog_Name,
		@IsUsingSelfLearningPriorities,
		@SelfLearningPriorities_InitializationTreshold,
		@IsPrivateCatalog,
		@R_InitializationTreshold_NumberOfRelevantDiagnosisPerformed,
		@SelfLearningPriorities_NumberOfPastDaysTakenIntoAccount,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)