INSERT INTO 
	cmn_bpt_emp_workingcontracts
	(
		CMN_BPT_EMP_WorkingContractID,
		ExtraWorkCalculation_RefID,
		WorkingContract_InCurrency_RefID,
		Contract_StartDate,
		Contract_EndDate,
		IsContractEndDateDefined,
		IsWorkTimeCalculated_InHours,
		IsWorkTimeCalculated_InDays,
		R_WorkTime_DaysPerWeek,
		R_WorkTime_HoursPerWeek,
		IsWorktimeChecked_Weekly,
		IsWorktimeChecked_Monthly,
		SurchargeCalculation_UseMaximum,
		SurchargeCalculation_UseAccumulated,
		IsMealAllowanceProvided,
		WorkingContract_Comment,
		Creation_Timestamp,
		IsDeleted,
		Tenant_RefID
	)
VALUES 
	(
		@CMN_BPT_EMP_WorkingContractID,
		@ExtraWorkCalculation_RefID,
		@WorkingContract_InCurrency_RefID,
		@Contract_StartDate,
		@Contract_EndDate,
		@IsContractEndDateDefined,
		@IsWorkTimeCalculated_InHours,
		@IsWorkTimeCalculated_InDays,
		@R_WorkTime_DaysPerWeek,
		@R_WorkTime_HoursPerWeek,
		@IsWorktimeChecked_Weekly,
		@IsWorktimeChecked_Monthly,
		@SurchargeCalculation_UseMaximum,
		@SurchargeCalculation_UseAccumulated,
		@IsMealAllowanceProvided,
		@WorkingContract_Comment,
		@Creation_Timestamp,
		@IsDeleted,
		@Tenant_RefID
	)