
Select
  hec_crt_insurancetobrokercontract_participatingpatients.HEC_CRT_InsuranceToBrokerContract_ParticipatingPatientID,
  hec_crt_insurancetobrokercontracts.Ext_CMN_CTR_Contract_RefID As contract_id
From
  hec_crt_insurancetobrokercontract_participatingpatients Inner Join
  hec_crt_insurancetobrokercontracts
    On
    hec_crt_insurancetobrokercontract_participatingpatients.InsuranceToBrokerContract_RefID = hec_crt_insurancetobrokercontracts.HEC_CRT_InsuranceToBrokerContractID   And
  hec_crt_insurancetobrokercontracts.IsDeleted = 0 And
  hec_crt_insurancetobrokercontracts.Tenant_RefID = @TenantID
Where
  hec_crt_insurancetobrokercontract_participatingpatients.HEC_CRT_InsuranceToBrokerContract_ParticipatingPatientID = @ParticipationID And
  hec_crt_insurancetobrokercontract_participatingpatients.IsDeleted = 0 And
  hec_crt_insurancetobrokercontract_participatingpatients.Tenant_RefID =
  @TenantID

  
	