INSERT INTO 
	ord_prc_procurementorder_notes
	(
		ORD_PRC_ProcurementOrder_NoteID,
		ORD_PRC_ProcurementOrder_Header_RefID,
		ORD_PRC_ProcurementOrder_Position_RefID,
		CMN_STR_Office_RefID,
		Comment,
		Title,
		NotePublishDate,
		SequenceOrderNumber,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@ORD_PRC_ProcurementOrder_NoteID,
		@ORD_PRC_ProcurementOrder_Header_RefID,
		@ORD_PRC_ProcurementOrder_Position_RefID,
		@CMN_STR_Office_RefID,
		@Comment,
		@Title,
		@NotePublishDate,
		@SequenceOrderNumber,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)