INSERT INTO 
	tms_pro_businesstasks
	(
		TMS_PRO_BusinessTaskID,
		IdentificationNumber,
		DOC_Structure_Header_RefID,
		BusinessTasksPackage_RefID,
		Project_RefID,
		Estimated_StartDate,
		Estimated_EndDate,
		Task_Name_DictID,
		Task_Description_DictID,
		Task_Type_RefID,
		Task_Status_RefID,
		Task_Deadline,
		IsArchived,
		CreatedByAccount_RefID,
		Creation_Timestamp,
		IsDeleted,
		Tenant_RefID
	)
VALUES 
	(
		@TMS_PRO_BusinessTaskID,
		@IdentificationNumber,
		@DOC_Structure_Header_RefID,
		@BusinessTasksPackage_RefID,
		@Project_RefID,
		@Estimated_StartDate,
		@Estimated_EndDate,
		@Task_Name,
		@Task_Description,
		@Task_Type_RefID,
		@Task_Status_RefID,
		@Task_Deadline,
		@IsArchived,
		@CreatedByAccount_RefID,
		@Creation_Timestamp,
		@IsDeleted,
		@Tenant_RefID
	)