INSERT INTO 
	log_rcp_rqf_header_2_shipmentheader
	(
		AssignmentID,
		LOG_RCP_RQF_RequestQuantityForwarding_Header_RefID,
		LOG_SHP_Shipment_Header_RefID,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@AssignmentID,
		@LOG_RCP_RQF_RequestQuantityForwarding_Header_RefID,
		@LOG_SHP_Shipment_Header_RefID,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)