INSERT INTO 
	log_rsv_reservation_shelfcontent_history
	(
		LOG_RSV_Reservation_ShelfContent_HistoryID,
		LOG_WRH_Shelf_Content_RefID,
		IsReservationMade,
		IsReservationReleased,
		NewReservedQuantity,
		ReservedQuantity,
		ReleasedQuantity,
		Comment,
		IfReservationMade_Reservation_RefID,
		IfReservationReleased_ReleasedReservation_RefID,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@LOG_RSV_Reservation_ShelfContent_HistoryID,
		@LOG_WRH_Shelf_Content_RefID,
		@IsReservationMade,
		@IsReservationReleased,
		@NewReservedQuantity,
		@ReservedQuantity,
		@ReleasedQuantity,
		@Comment,
		@IfReservationMade_Reservation_RefID,
		@IfReservationReleased_ReleasedReservation_RefID,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)