
	SELECT log_wrh_inj_inventoryjob_series_participatingshelves.LOG_WRH_Shelf_RefID
		,log_wrh_inj_inventoryjob_series_participatingshelves.LOG_WRH_INJ_InventoryJob_Series_RefID
		,log_wrh_inj_inventoryjob_series_participatingshelves.LOG_WRH_INJ_InventoryJob_Series_ParticipatingShelfID
		,log_wrh_inj_inventoryjob_series_participatingshelves.Creation_Timestamp
		,log_wrh_inj_inventoryjob_series_participatingshelves.Tenant_RefID
		,log_wrh_inj_inventoryjob_series_participatingshelves.IsDeleted
	FROM log_wrh_inj_inventoryjob_series_participatingshelves
	WHERE log_wrh_inj_inventoryjob_series_participatingshelves.IsDeleted = 0
		AND log_wrh_inj_inventoryjob_series_participatingshelves.Tenant_RefID = @TenantID
		AND log_wrh_inj_inventoryjob_series_participatingshelves.LOG_WRH_INJ_InventoryJob_Series_RefID = @InventoryJobSeriesID
  