

var translationsDE = {
    //***LABELS GLOBAL***//
    LABEL_OCT_CAN_BE_SUBMITTED_ONLY_UNTIL_LATE: 'Oct can only be submitted until latest ivom date + {{treatment_year_length}} ({{date}}).',

    LABEL_DOCUMENTATION_CASE_DELETED: 'Dokumentation löschen',
    LABEL_GO_TO_PATIENT_DETAILS_OPEN_WIZARD: 'BDOC Informationen aufrufen',
    LABEL_VIEW_ALL_PLANNED_IVOMS: 'Alle geplanten Vorgänge anzeigen',
    LABEL_OP: 'IVOM',
    LABEL_PRACTICE_HAS_OCT_DEVICE: 'Praxis verwendet ein SD-OCT',
    LABEL_PLEASE_ENTER_YOUR_PASSWORD_TO_CHANGE_PRACTICE_HAS_OCT_DEVICE_SETTING: 'Bitte geben Sie Ihr Passwort ein, um die Einstellungen zu speichern.',
    LABEL_DOCUMENTATION_ONLY: 'Nur zur Dokumentation',
    LABEL_SHOULD_DOWNLOAD_REPORT_UPON_SUBMISSION: 'Übermittlungsbestätigungen gesammelt herunterladen',
    LABEL_NO_ELIGIBLE_REPORTS: 'keine neuen Übermittlungsbestätigungen',
    LABEL_PRESS_ENTER_TO_SEARCH: 'aktivieren von: Zum Suchen Enter drücken',

    LABEL_PATIENT_HAS_NO_CONSENT: 'Eine Teilnahmeerklärung des Patienten liegt nicht vor.',
    LABEL_PATIENT_HAS_NO_CONSENT_ON_SELECTED_DATE: 'Für das Behandlungsdatum liegt keine gültige Teilnahmeerklärung des Patienten vor.',

    LABEL_HELP: 'Hilfe',
    LABEL_YOUR_SESSION_HAS_EXPIRED: 'Ihre Sitzung ist abgelaufen. Bitte klicken Sie OK, um Sich erneut anzumelden.',
    LABEL_NOTICE: 'Hinweis',

    LABEL_404: 'Zugriff nicht gestattet',
    LABEL_NOT_IMPLEMENTED: 'Diese Funktion ist in Arbeit. Bitte haben Sie noch etwas Geduld. Danke.',
    LABEL_WARNING: 'Warnung!',
    LABEL_DATE_PLACEHOLDER: 'TT.MM.JJJJ',
    LABEL_DATE_NOT_VALID: 'Ungültiges Datum',
    LABEL_WHAT_IS_YOUR_PASSWORD: 'Wie lautet Ihr Passwort?',
    LABEL_PLEASE_ENTER_PASSWORD: 'Bitte geben Sie Ihr Passwort ein',
    LABEL_CREDENTIALS_NOT_VERIFIED: 'Bitte überprüfen Sie Ihre Zugangsdaten und versuchen es noch Mal.',
    LABEL_DOCTOR_RESPONSIBLE: 'Behandelnder Arzt',
    LABEL_PASSWORD: 'Passwort',
    LABEL_NEW_CASE: 'neuer Vorgang',
    LABEL_PRACTICES: 'Praxen',
    LABEL_DOCTORS: 'Ärzte',
    LABEL_OPERATION_SUCCESSFUL: 'Vorgang erfolgreich abgeschlossen',
    LABEL_OPERATION_CANCELLED: 'Vorgang wurde abgebrochen',
    LABEL_SOMETHING_WENT_WRONG: 'Irgendwas ist schiefgegangen',
    LABEL_DO_YOU_WANT_TO_CONTINUE: 'Möchten Sie die Daten speichern?',
    LABEL_DATE: 'Datum',
    LABEL_CANCEL: 'Abbrechen',
    LABEL_CHANGES_SAVED: 'Änderung gespeichert',
    LABEL_CANCEL_DRUG_ORDER_POPUP: 'Möchten Sie die Medikamentenbestellung stornieren?',
    LABEL_DATE_CANNOT_BE_HIGHER_THEN_TODAY_DATE: 'Das angegebene Datum liegt außerhalb des gültigen Bereichs.',
    LABEL_SEARCH: 'Suche ...',
    LABEL_ALL: 'Alles',
    LABEL_OVERDUE: 'überfällig',
    LABEL_CURRENT: 'aktuell',
    LABEL_PLANNING: 'Planung',
    LABEL_WIDRAWN: 'zurückgezogen',
    LABEL_AFTERCARES: 'Nachsorge',
    LABEL_OCT: 'OCT',
    LABEL_OCT_DATE: 'OCT Datum',
    LABEL_OCT_DOCTOR: 'OCT Diagnostik Arzt',
    LABEL_SETTLEMENT: 'Abrechnungen',
    LABEL_OPERATIONS: 'Behandlung',
    LABEL_PATIENT: 'Patienten',
    LABEL_RECEIPT: 'Belege',
    LABEL_PRACTICE: 'Praxis',
    LABEL_CANCELLED: 'storniert',
    LABEL_PAID: 'bezahlt',
    LABEL_CORRECTION: 'Korrektur erforderlich',
    LABEL_CONFIRMED2: 'bestätigt',
    LABEL_SUBMITTED: 'übermittelt',
    LABEL_READY: 'durchgeführt',
    LABEL_RECLAIM: 'überwiesen',
    LABEL_TREATMENT_DATE_OUTSIDE_OF_SUBMISSION_TIMESPAN: 'Auf Grund des Vertrages mit der Krankenkasse, konnte die Behandlung nur bis zum {{timespan}} übermittelt werden.',
    LABEL_AFTERCARE_DATE_OUTSIDE_OF_SUBMISSION_TIMESPAN: 'Auf Grund des Vertrages mit der Krankenkasse, kann die Nachsorge nur zwischen dem {{timespan}} übermittelt werden.',
    LABEL_AFTERCARE_TOO_MANY_DAYS_HAVE_PASSED_SINCE_TREATMENT: 'Auf Grund des Vertrages mit der Krankenkasse, kann die Nachsorge nur zwischen dem {{timespan}} durchgeführt werden.',
    LABEL_DOCTOR_CONSENT_NOT_VALID: 'Für das Behandlungsdatum ({{date}}) liegt keine gültige Teilnahmeerklärung für den Arzt ({{name}}) vor.',
    LABEL_CONSENT_COMBINATION_NOT_VALID: 'Auf Grund des Vertrages mit der Krankenkasse, kann eine Behandlung mit dieser Kombination aus Diagnose und Medikament nicht abgerechnet werden.',
    LABEL_AFTERCARE_DOCTOR_CONSENT_NOT_VALID: 'Für das Behandlungsdatum ({{date}}) liegt keine gültige Teilnahmeerklärung für den Arzt ({{name}}) vor.',
    LABEL_AFTERCARE_PRACTICE_CONSENT_NOT_VALID: 'Für das Behandlungsdatum ({{date}}) liegt keine gültige Teilnahmeerklärung für einen Arzt aus der Praxis ({{name}}) vor.',
    LABEL_PATIENT_CONSENT_NOT_VALID: 'Für das Behandlungsdatum ({{date}}) liegt keine gültige Teilnahmeerklärung des Patienten ({{name}}) vor.',
    LABEL_SETTLEMENT_NOT_POSSIBLE: 'A new OCT is created for this localization. A settlement is currently not possible because the max number of OCT for this patient has been already settled. A settlement will be possible again, starting with {{date}}.',
    LABEL_CONTRACT_NOT_FOUND: 'Der Vertrag mit der Krankenkasse enthält die gewählte Kombination von Diagnose und Medikament nicht.',
    LABLE_CANCEL_CASE_TITLE: 'Achtung! Sie möchten eine bereits durchgeführte Behandlung stornieren.',
    LABEL_QUESTION_FOR_CANCELATION: 'Bitte geben sie den Grund der Stornierung an.',
    LABEL_PASSWORD_NEEDED: 'Bitte geben Sie Ihr Passwort ein, um die Stornierung zu bestätigen.',
    LABEL_INSURANCE_STATUS_BOTH: 'Der Versichertenstatus konnte nicht validiert werden. Bitte wählen Sie:',
    LABEL_OLD_INSURANCE_STATUS: 'alter Versichertenstatus (“n000n”)',
    LABEL_NEW_INSURANCE_STATUS: 'neuer Versichertenstatus (“n n”)',
    LABEL_OLD_INSURANCE_STATUS_VALIDATION: 'Der Versichertenstatus konnte nicht validiert werden. Möchten Sie fortfahren?',
    LABEL_LOGOUT: 'Abmelden',
    LABEL_MYACCOUNT: 'Mein Account',
    LABEL_TREATMENT_DATE_IN_FUTURE: 'Das Behandlungsdatum liegt in der Zukunft.',
    LABEL_NO_CASE_CAN_BE_SUBMITTED: 'Es konnte keine der ausgewählten Behandlungen übermittelt werden.',
    LABEL_DIAGNOSIS_DRUG: 'Diagnose / Medikament',
    LABEL_CASE_ONE: 'Vorgang',
    LABEL_PARTICIPATION_ACTIVE: 'Teilnahmeerklärung aktiv',
    LABEL_PARTICIPATION_NOT_ACTIVE: 'Teilnahmeerklärung abgelaufen',
    LABEL_PARTICIPATION_NOT_YET_ACTIVE: 'Teilnahmeerklärung noch nicht aktiv',
    LABEL_SEARCHING: 'Suchen ...',
    LABEL_NO_RESULTS: 'Keine Ergebnisse gefunden',
    LABEL_GPOS_DOESNT_EXIST: 'Auf Grund des Vertrages mit der Krankenkasse, kann eine Behandlung mit dieser Kombination aus Diagnose und Medikament nicht abgerechnet werden.',

    LABEL_NAME: 'Name',
    LABEL_CONTACT: 'Kontakt',
    LABEL_NEW_AFTERCARE_DOCTOR: 'neuen Augenarzt anlegen',
    LABEL_STREET: 'Straße',
    LABEL_HOUSE_NUMBER: 'Haus-Nr.',
    LABEL_ZIP: 'PLZ',
    LABEL_CITY: 'Ort',
    LABEL_PHONE: 'Telefon',
    LABEL_TELEPHONE: 'Telefon',
    LABEL_FAX: 'Fax',
    LABEL_EMAIL: 'E-Mail',
    LABEL_COMMENT: 'Kommentar',
    LABEL_SELECTED_AFTERCARE_DOCTOR_TEMPORARY: 'Die Behandlung kann nicht übermittelt werden, da der betreuende Augenarzt noch nicht in Medios Connect hinterlegt ist.',
    LABEL_TEMPORARY_DOCTOR_CREATED: 'Neuer Augenarzt wurde gespeichert.',
    LABEL_EMAIL_NOT_VALID: 'E-Mail Adresse ungültig',
    LABEL_PERIOD: 'Zeitraum',
    LABEL_AMOUNT: 'Betrag',
    LABEL_ACCOUNT: 'Mein Account',
    LABEL_SALUTATION: 'Anrede',
    LABEL_TITLE: 'Titel',
    LABEL_FIRSTNAME: 'Vorname',
    LABEL_LASTNAME: 'Nachname',
    LABEL_LANR: 'LANR',
    MY_CONTACT: 'Meine Kontaktdaten',
    LABEL_BANKACCOUNT: 'Bankverbindung',
    LABEL_USERPRACTICEBANK: 'Bankverbindung der Praxis übernehmen',
    LABEL_BIC: 'BIC',
    LABEL_IBAN: 'IBAN',
    LABEL_ACCOUNT_HOLDER: 'Kontoinhaber',
    LABEL_BANK: 'Bank',
    LABEL_CHANGE_PASSWORD: 'Passwort ändern',
    LABEL_LOGIN_EMAIL: 'Login E-Mail Adresse',
    LABEL_My_Access_Credentials: 'Meine Zugangsdaten',
    LABEL_RESET_PASSWORD: 'Passwort zurücksetzen',
    LABEL_NEW_PASSWORD_GENERATE: 'Neues Passwort generieren',
    LABEL_DEFINE_NEW_PASSWORD: 'Neues Passwort erstellen',
    LABEL_REPEAT_NEW_PASSWORD: 'Neues Passwort wiederholen',
    LABEL_CHANGE_PASSWORD_SURE1: 'Möchten Sie das Passwort für den ',
    LABEL_CHANGE_PASSWORD_SURE2: ' Account ändern?',
    LABEL_PASSWORD_CHANGED: 'Passwort erfolgreich geändert',
    LABEL_WELCOME_EMAIl1: 'Eine E-Mail mit dem neuen Passwort wird an den ',
    LABEL_WELCOME_EMAIl2: ' versendet.',
    LABEL_CHANGES_SAVED: 'Änderung gespeichert',
    LABEL_CHANGE_NOW: 'Jetzt ändern',
    op: 'Behandlung',
    ac: 'Nachsorge',
    order: 'Bestellungen',
    participation: 'Teilnahmeerklärung',

    LABEL_PRACTICE_ACCOUNT: 'Praxis Account',
    LABEL_PRACTICE_NAME: 'Praxisname',
    LABEL_BSNR: 'BSNR',
    LABEL_MAIN_EMAIL: 'Haupt-E-Mail Adresse',
    LABEL_MAIN_PHONE: 'Haupt Telefonnummer',
    LABEL_FAX: 'Fax',
    LABEL_CONTACT_PERSON: 'Ansprechpartner',
    LABEL_DEFAULT_SHIPPING_DATE_OFFSET: 'Standardlieferdatum',
    LABEL_LABEL_DAYS_TO_OP: 'Tag/Tage vor der IVOM',
    LABEL_OP_DATE: 'IVOM Datum',

    LABEL_DRUG: 'Medikament',
    LABEL_IVOM_DATE: 'IVOM Datum',
    LABEL_LATEST_IVOM_DATE: 'IVOM Datum',
    LABEL_OP_DOCTOR: 'operierender Arzt',
    LABEL_DIAGNOSIS: 'Diagnose',

    LABEL_INVALID_PLZ_NO: 'Postleitzahl ungültig',
    LABEL_INVALID_BSNR_NO: 'BSNR ungültig',
    LABEL_BSNR_LENGTH: 'Länge der BSNR ungültig',
    LABEL_BSNR_EXISTS: 'BSNR existiert bereits',
    LABEL_EMAIL_NOT_VALID: 'E-Mail Adresse ungültig',
    LABEL_INVALID_DATEFORMAT_NO: 'Datum ungültig',
    LABEL_IBAN_INVALID: 'IBAN ungültig',
    LABEL_BIC_INVALID: 'BIC ungültig',
    LABEL_ENTER_BANK_NAME: 'Bitte tragen Sie den Namen der Bank ein.',
    LABEL_ENTER_BIC: 'Bitte tragen Sie die BIC ein.',
    LABEL_ACCOUNT_EXISTS: 'Ein Account mit dieser E-Mail Adresse existiert bereits.',
    LABEL_ENTER_PASSWORD: 'Bitte geben Sie ein Passwort ein.',
    LABEL_PASSWORD_FORMAT: 'Bitte verwenden Sie für Ihr Passwort mind. 8 große und kleine Buchstaben und mind. eine Ziffer. Für erhöhte Passwortsicherheit wird die zusätzliche Verwendung der folgenden Symbole empfohlen: ~!@#$%^&*_-+=`|\(){}[]:;<>,.?/".',
    LABEL_PASSWORD_MISMATCH: 'Die Passwörter stimmen nicht überein.',
    LABEL_INVALID_LANR: 'LANR ungültig',
    LABEL_LANR_LENGTH: 'Länge der LANR ungültig',
    LABEL_LANR_EXISTS: 'LANR existiert bereits',
    LABEL_INVALID_LANR_NO: 'LANR ungültig',
    LABEL_NO: 'Haus-Nr.',
    LABEL_PRACTICE_BANK_ACCOUNT: 'Bankverbindung der Praxis',
    LABEL_NOT_ORDERED: 'Medikament nicht bestellt',
    LABEL_NONE: 'Keine',
    LABEL_NON_COOPERATTING_PHARMACY: 'Ich möchte eine andere Apotheke beauftragen',
    LABEL_DELIVERY_FROM_INVALID: 'Lieferzeit (von) ist ungültig',
    LABEL_DELIVERY_TO_INVALID: 'Lieferzeit (bis) ist ungültig',
    LABEL_FROM_LOWER: 'Das Ende des Lieferzeitraums ist kleiner als der Start',
    LABEL_ORDERED_DRUGS: 'Medikamente bestellt',
    LABEL_CANCELED_ORDERS: 'storniert',
    LABEL_DELETED_ORDERS: 'gelöscht',
    LABEL_DRUG_NOT_AVAILABLE: 'Nicht lieferbar',
    LABEL_ELIGIBLE_FOR_SETTLEMENT: 'Behandlung kann abgerechnet werden',
    LABEL_TREATMENT_ALREADY_EXIST: 'Für den selben Tag und die selbe Lokalisation existiert breits eine Behandlung.',
    LABEL_SUMITTED_ORDER_MESSAGE: 'Das Medikament wurde in den Warenkorb gelegt. Bitte rufen Sie den Warenkorb auf, um die Bestellung abzuschließen. Sie können auch zuerst weitere Medikamente in den Warenkorb legen und anschließend alle zusammen absenden.',
    LABEL_DONT_SHOW_MESSAGE: 'Diese Meldung nicht mehr anzeigen.',

    // Treatment eligibility
    LABEL_HIP_DOESNT_PARTICIPATE: 'Abrechnung nicht möglich. Kein Vertrag mit der Krankenkasse.',
    LABEL_NO_DOCTOR_CONTRACT: 'Abrechnung nicht möglich. Kein Arzt in der Praxis nimmt am Vertrag mit der Krankenkasse teil.',
    LABEL_NO_PATIENT_CONSENT: 'Abrechnung nicht möglich. Teilnahmeerklärung des Patienten fehlt.',
    LABEL_DRUG_NOT_VALID: 'Abrechnung nicht möglich. Medikament ist nicht im Vertrag enthalten.',
    LABEL_ADD_CONSENT: 'Teilnahmeerklärung hinzufügen',
    //statuses
    FS0: 'offen',
    FS1: 'durchgeführt',
    FS2: 'übermittelt',
    FS5: 'in Abrechnung',
    FS4: 'bestätigt',
    FS6: 'Korrektur erforderlich',
    FS7: 'überwiesen',
    FS8: 'storniert',
    FS9: 'Ablehnung durch die Krankenkasse',
    FS10: 'Rückforderung',
    FS12: 'bezahlt',
    FS13: 'zur Dokumentation',
    FS11: 'Stornierung anhängig',
    FS21: 'OCT vorgemerkt',
    OP9: 'bezahlt',
    OP10: 'storniert',

    AC10: 'bezahlt',
    AC11: 'storniert',
    AC12: 'Ablehnung durch die Krankenkasse',
    LABEL_PRIVATELY_INSURED: 'Privat',

    LABEL_EMPTY: '(leer)',
    LABEL_CONTRACT_HAS_NO_OP_GPOS: 'Für diese Behandlung enthält der Vertrag mit der Krankenkasse keine Gebührenposition.',
    LABEL_CONTRACT_HAS_NO_AC_GPOS: 'Für die Nachsorge enthält der Vertrag mit der Krankenkasse keine Gebührenposition.',
    LABEL_NO_ELIGIBLE_CASES_SELECTED: 'Für die ausgewählten Behandlungen ist dieser Vorgang nicht möglich.',
    LABEL_HIP_CANT_BE_CHANGED_OPEN_CASES_EXIST: 'Die Krankenkasse kann nicht gewechselt werden, da noch offene Vorgänge für diesen Patienten vorhanden sind. Bitte übermitteln oder stornieren Sie zunächst alle Vorgänge für diesen Patienten in der Planung.',


    // PRE-EXAMINATION LABELS
    LABEL_NEW_PREEXAMINATION: 'Neue OCT',
    LABEL_DOCTOR_HAS_NO_CONSENT_ON_CONTRACT_WITH_PREEXAMINATION_ON_SELECTED_DATE: 'Für das Behandlungsdatum liegt vom Arzt keine Teilnahmeerklärung am Vertrag vor.',
    LABEL_PATIENT_HAS_NO_CONSENT_ON_CONTRACT_WITH_PREEXAMINATION_ON_SELECTED_DATE: 'Für das Behandlungsdatum liegt für den Patienten keine Teilnahmeerklärung vor.',
    LABEL_PATIENT_HAS_NO_CONSENT_ON_CONTRACT_WITH_PREEXAMINATION: 'Für den Patienten liegt keine Teilnahmeerklärung vor.',
    LABEL_DOCTOR_HAS_NO_CONSENT_ON_CONTRACT_WITH_PREEXAMINATION: 'Für den Arzt liegt keine Teilnahmeerklärung vor.',
    LABEL_PREEXAMINATION_SUBMITTED: 'Die OCT wurde zur Abrechnung übermittelt.',
    LABEL_PREEXAMINATION_DATE_CANNOT_BE_IN_THE_FUTURE: 'Das angegebene Datum liegt in der Zukunft. Eine Übermittlung ist nicht möglich.',
    LABEL_PATIENT_PREEXAMINATION_LIMIT_EXCEEDED: 'Die maximale Anzahl an OCTs für die Lokalisation ist erreicht.',
    LABEL_PREEXAMINATIONS: 'OCT',
    LABEL_PASSWORD_NEEDED_FOR_PREEXAMINATION: 'Bitte geben sie ihr Passwort ein, um die Durchführung der OCT zu bestätigen.',

    LABEL_PATIENTS_WITH_REJECTED_OCTS: 'abgelehnte OCT',
    LABEL_THIS_PRACTICE: 'IVOM in unserer Praxis vorgenommen',
    LABEL_DIFFERENT_PRACTICE: 'IVOM in anderer Praxis vorgenommen',
    LABEL_INVALID_CONSENT: 'ohne gültige Teilnahmeerklärung',

    LABEL_PREFERRED_PHARMACY: 'Apotheke',
    LABEL_PHARMACY: 'Apotheke',
    LABEL_QUICK_ORDER_VERWNDEN: 'Direktbestellung aktivieren (Praxisadresse wird als Lieferadresse verwendet)',
    LABEL_QUICK_ORDER_GRACE_PERIOD: 'Passwort für Direktbestellungen speichern',
    LABEL_OTHER_OPTIONS: 'Andere Einstellungen',

    LABEL_ADD_TO_CART: 'Zum Warenkorb hinzufügen',
    LABEL_SUBMIT_AND_CLOSE: 'Schließen und abschicken',
    LABEL_ORDER_PDF_NOTICE: 'Nach der Bestätigung steht Ihnen ein PDF-Auftrag zum Download zur Verfügung. Wenn Sie es erneut herunterladen möchten, können Sie es im Abschnitt "Bestellungen" finden.',


    //***BUTTONS GLOBAL***//
    BUTTON_404: 'Zurück zur Hauptseite',
    BUTTON_PASSSWORD_SENT: 'Passwort senden',
    BUTTON_PDF: 'PDF',
    BUTTON_OK: 'OK',
    BUTTON_GO_TO_PATIENT_DETAILS: 'Patientenakte aufrufen',
    BUTTON_CANCEL: 'Abbrechen',
    BUTTON_SAVE: 'Speichern',
    BUTTON_SAVE_SUBMIT: 'Behandlung abrechnen',
    BUTTON_YES: 'Ja',
    BUTTON_NO: 'Nein',
    BUTTON_CONFIRM: 'BESTÄTIGEN',
    BUTTON_CONFIRM_NORMALCASE: 'Bestätigen',
    BUTTON_CONTINUE: 'Weiter',
    BUTTON_FINISH: 'Beenden',
    BUTTON_DELETE: 'löschen',
    BUTTON_BACK: 'Zurück',
    BUTTON_EDIT: 'bearbeiten',
    BUTTON_SUBMIT: 'Einsenden',
    BUTTON_DONT_SUBMIT: 'Don\'t submit',
    BUTTON_DOWNLOAD: 'Herunterladen',

    TOOLTIP_QUICK_ORDER_MSG: 'Um Direktbestellungen zu aktivieren, wählen Sie bitte eine Apotheke aus und geben Sie die Praxisadresse, den Ansprechpartner, das Standardlieferdatum und die Standardlieferzeit an.'
};

var translationsEN = {
    //***LABELS GLOBAL***//
    LABEL_HELP: 'Help',
    LABEL_YOUR_SESSION_HAS_EXPIRED: 'Your session has expired. Please press OK to logout.',
    LABEL_NOTICE: 'Notice',

    LABEL_404: 'Forbidden page.',
    LABEL_NOT_IMPLEMENTED: 'Sorry, this functionality is not implemented yet. Thanks for your patience.',
    LABEL_WARNING: 'Warning!',
    LABEL_DATE_NOT_VALID: 'Date is not valid.',
    LABEL_DATE_PLACEHOLDER: 'MM.DD.YYYY',
    LABEL_WHAT_IS_YOUR_PASSWORD: 'What is your password?',
    LABEL_PLEASE_ENTER_PASSWORD: 'Please enter your password',
    LABEL_CREDENTIALS_NOT_VERIFIED: 'Sorry, these credentials could not be verified.',
    LABEL_DOCTOR_RESPONSIBLE: 'Responsible doctor',
    LABEL_PASSWORD: 'Password',
    LABEL_NEW_CASE: 'New case',
    LABEL_PRACTICES: 'Praxen',
    LABEL_DOCTORS: 'Ärzte',
    LABEL_OPERATION_SUCCESSFUL: 'Operation successful.',
    LABEL_SOMETHING_WENT_WRONG: 'Something went wrong.',
    LABEL_OPERATION_CANCELLED: 'Operation has been canceled.',
    LABEL_DO_YOU_WANT_TO_CONTINUE: 'Do you wish to save data anyway?',
    LABEL_DATE: 'Date',
    LABEL_CANCEL: 'Cancel',
    LABEL_CHANGES_SAVED: 'Changes saved.',
    LABEL_CANCEL_DRUG_ORDER_POPUP: 'Are you sure you wish to cancel this drug order?',
    LABEL_DATE_CANNOT_BE_HIGHER_THEN_TODAY_DATE: 'Date can not be higher than todays date.',
    LABEL_SEARCH: 'Search...',
    LABEL_ALL: 'All',
    LABEL_OVERDUE: 'Overdue',
    LABEL_CURRENT: 'Current',
    LABEL_WIDRAWN: 'Withdrawn',
    LABEL_AFTERCARES: 'Aftercare',
    LABEL_OCT: 'OCT',
    LABEL_OCT_DATE: 'OCT date',
    LABEL_OCT_DOCTOR: 'OCT doctor',
    LABEL_OPERATIONS: 'Behandlung',
    LABEL_PATIENT: 'Patient',
    LABEL_RECEIPT: 'Receipt',
    LABEL_PLANNING: 'Planning',
    LABEL_PRACTICE: 'Praxis',
    LABEL_CANCELLED: 'Canceled',
    LABEL_SETTLEMENT: 'Settlement',
    LABEL_PAID: 'Paid',
    LABEL_CORRECTION: 'Error correction requited',
    LABEL_CONFIRMED2: 'Confirmed',
    LABEL_SUBMITTED: 'Processing',
    LABEL_READY: 'performed',
    LABEL_RECLAIM: 'Payment in Process ',
    LABEL_NO_CONTRACT_FOUND: 'No contract found for selected drug/diagnose combination',
    LABEL_DOCTOR_CONSENT_NOT_VALID: 'Selected treatment date ({{date}}) doesn\'t fall into doctors ({{name}}) participation consent timespan ({{timespan}})',
    LABEL_PATIENT_CONSENT_NOT_VALID: 'Selected treatment date ({{date}}) doesn\'t fall into patients ({{name}}) participation consent timespan ({{timespan}})',
    LABEL_SETTLEMENT_NOT_POSSIBLE: 'A new OCT is created for this localization. A settlement is currently not possible because the max number of OCT for this patient has been already settled. A settlement will be possible again, starting with {{date}}.',
    LABEL_AFTERCARE_DOCTOR_CONSENT_NOT_VALID: 'Selected treatment date ({{date}}) doesn\'t fall into aftercare doctors ({{name}}) participation consent timespan ({{timespan}})',
    LABEL_AFTERCARE_PRACTICE_CONSENT_NOT_VALID: 'Selected treatment date ({{date}}) doesn\'t fall into any doctors working in selected practice ({{name}}) participation consent timespan',
    LABEL_CONTRACT_NOT_FOUND: 'Contract containing selected diagnose/drug combination not found',
    LABEL_TREATMENT_DATE_OUTSIDE_OF_SUBMISSION_TIMESPAN: 'Selected treatment date ({{date}}) doesn\'t fall into contract\'s validity timespan ({{timespan}})',
    LABEL_AFTERCARE_DATE_OUTSIDE_OF_SUBMISSION_TIMESPAN: 'Selected aftercare performed date ({{date}}) doesn\'t fall into contract\'s validity timespan ({{timespan}})',
    LABLE_CANCEL_CASE_TITLE: 'ATTENTION! <br/> You want to cancel a settled treatment.',
    LABEL_QUESTION_FOR_CANCELATION: 'Please provide a reason for the cancelation.',
    LABEL_PASSWORD_NEEDED: 'Please enter your password to confirm the cancelation.',
    LABEL_INSURANCE_STATUS_BOTH: 'Inserted Insurance status passed validation rules for both, old (before 1st October, 2014) and new insurance status number. Please select if the number belongs to:',
    LABEL_OLD_INSURANCE_STATUS: 'Old Versichertenstatus (“n000n”)',
    LABEL_NEW_INSURANCE_STATUS: 'new Versichertenstatus (“n n”)',
    LABEL_OLD_INSURANCE_STATUS_VALIDATION: 'Inserted Insurance status passed validation rules for old insurance status number (before 1st October, 2014). By clicking yes you approve that the old insurance status (“ {{first_name}} ”) is valid.',
    LABEL_LOGOUT: 'Logout',
    LABEL_MYACCOUNT: 'My Account',
    LABEL_TREATMENT_DATE_IN_FUTURE: 'Selected date is in the future.',
    LABEL_DIAGNOSIS_DRUG: 'Diagnosis / Drug',
    LABEL_CASE_ONE: 'Case',
    LABEL_PARTICIPATION_ACTIVE: 'Teilnahmeerklärung aktiv',
    LABEL_PARTICIPATION_NOT_ACTIVE: 'Teilnahmeerklärung abgelaufen',
    LABEL_NAME: 'Name',
    LABEL_CONTACT: 'Contact',
    LABEL_NEW_AFTERCARE_DOCTOR: 'Add New Aftercare Doctor',
    LABEL_STREET: 'Street',
    LABEL_HOUSE_NUMBER: 'No.',
    LABEL_ZIP: 'ZIP',
    LABEL_CITY: 'City',
    LABEL_PHONE: 'Phone',
    LABEL_FAX: 'Fax',
    LABEL_EMAIL: 'Email',
    LABEL_COMMENT: 'Comment field (optional)',
    LABEL_SELECTED_AFTERCARE_DOCTOR_TEMPORARY: 'Selected case cannot be submitted since the selected aftercare doctor is not yet verified by the MM. \nFeel free to contact MM if you have any further questions.',
    LABEL_TEMPORARY_DOCTOR_CREATED: 'New temporary aftercare doctor saved.',
    LABEL_EMAIL_NOT_VALID: 'Invalid email address format.',
    LABEL_PERIOD: 'Period',
    LABEL_AMOUNT: 'Amount',
    LABEL_ACCOUNT: 'My  Account',
    LABEL_SALUTATION: 'Salutation',
    LABEL_TITLE: 'Title',
    LABEL_FIRSTNAME: 'First name',
    LABEL_LASTNAME: 'Last name',
    LABEL_LANR: 'LANR',
    MY_CONTACT: 'My Contact Details',
    LABEL_TELEPHONE: 'Phone',
    LABEL_BANKACCOUNT: 'Bank Account',
    LABEL_USERPRACTICEBANK: 'Use Practice Bank Account',
    LABEL_BIC: 'BIC',
    LABEL_IBAN: 'IBAN',
    LABEL_ACCOUNT_HOLDER: 'Account holder',
    LABEL_BANK: 'Bank',
    LABEL_CHANGE_PASSWORD: 'Change Password',
    LABEL_LOGIN_EMAIL: 'Login Email',
    LABEL_My_Access_Credentials: 'My Access Credentials',
    LABEL_RESET_PASSWORD: 'Reset Password',
    LABEL_NEW_PASSWORD_GENERATE: 'Generate Password',
    LABEL_DEFINE_NEW_PASSWORD: 'Define Password',
    LABEL_REPEAT_NEW_PASSWORD: 'Repeat Password',
    LABEL_CHANGE_PASSWORD_SURE1: 'Do you really want to change the password for the ',
    LABEL_CHANGE_PASSWORD_SURE2: ' account now?',
    LABEL_CHANGE_NOW: 'Change now (Save)',
    LABEL_PASSWORD_CHANGED: 'Password successfully changed.',
    LABEL_WELCOME_EMAIl1: 'A welcome email will be send to the ',
    LABEL_WELCOME_EMAIl2: ' account.',
    LABEL_CHANGES_SAVED: 'Changes saved.',
    LABEL_PRESS_ENTER_TO_SEARCH: 'Press enter to search',

    LABEL_PRACTICE_ACCOUNT: 'Practice Account',
    LABEL_PRACTICE_NAME: 'Practice name',
    LABEL_BSNR: 'BSNR',
    LABEL_MAIN_EMAIL: 'Main Email',
    LABEL_MAIN_PHONE: 'Main phone',
    LABEL_FAX: 'Fax',
    LABEL_CONTACT_PERSON: 'Contact person',
    LABEL_DEFAULT_SHIPPING_DATE_OFFSET: 'Default shipping date offset',
    LABEL_LABEL_DAYS_TO_OP: 'Tag/Tage vor der IVOM',

    LABEL_DRUG: 'Drug',
    LABEL_IVOM_DATE: 'IVOM date',
    LABEL_LATEST_IVOM_DATE: 'Latest IVOM date',
    LABEL_OP_DOCTOR: 'OP doctor',
    LABEL_DIAGNOSIS: 'Diagnosis',

    LABEL_INVALID_PLZ_NO: 'Invalid ZIP code format (numeric).',
    LABEL_INVALID_BSNR_NO: 'Invalid BSNR format (numeric).',
    LABEL_BSNR_LENGTH: 'Invalid BSNR format (length).',
    LABEL_BSNR_EXISTS: 'BSNR already exists.',
    LABEL_EMAIL_NOT_VALID: 'Invalid email address format.',
    LABEL_INVALID_DATEFORMAT_NO: 'Invalid date format (numeric).',
    LABEL_IBAN_INVALID: 'Invalid IBAN.',
    LABEL_BIC_INVALID: 'Invalid BIC.',
    LABEL_ENTER_BANK_NAME: "Please enter the bank's name.",
    LABEL_ENTER_BIC: 'Please enter the BIC.',
    LABEL_ACCOUNT_EXISTS: 'An account with this email address exists already.',
    LABEL_ENTER_PASSWORD: 'Please enter a password.',
    LABEL_PASSWORD_FORMAT: 'Please create a password with at least 8 characters in upper/lower case and at least one number. It is recommended to add the following symbols for extra security ~!@#$%^&*_-+=`|\(){}[]:;<>,.?/.',
    LABEL_PASSWORD_MISMATCH: 'Password missmatch.',
    LABEL_NO: 'No.',
    LABEL_PRACTICE_BANK_ACCOUNT: 'Practice Bank Account',
    LABEL_NOT_ORDERED: 'Medicine not ordered',
    LABEL_GPOS_DOESNT_EXIST: 'There is no GPOS which covers selected drug and diagnose combination',
    LABEL_NONE: 'None',
    LABEL_NON_COOPERATTING_PHARMACY: 'I would like to specify another pharmacy',
    LABEL_DELIVERY_FROM_INVALID: 'Delivery date from is invalid',
    LABEL_DELIVERY_TO_INVALID: 'Delivery date to is invalid',
    LABEL_FROM_LOWER: 'From must be lower than to date',
    LABEL_ORDERED_DRUGS: 'Medikamente bestellt',
    LABEL_CANCELED_ORDERS: 'Storniert',
    LABEL_DELETED_ORDERS: 'Gelöscht',
    LABEL_DRUG_NOT_AVAILABLE: 'Nicht lieferbar',
    LABEL_ELIGIBLE_FOR_SETTLEMENT: 'Eligible for settlement',
    LABEL_TREATMENT_ALREADY_EXIST: 'This is a duplicate treatment.',
    LABEL_SUMITTED_ORDER_MESSAGE: 'Treatment for selected date, patient, and localization already exist.',
    LABEL_DONT_SHOW_MESSAGE: 'Don\'t show this message again',
    LABEL_FARMACY_OPTIONS_CONSENT: 'Hiermit bestätige ich, meine Patienten über die freie Apothekenwahl aufgeklärt zu haben und dass meine Patienten mir die Auswahl der Apotheken durch schriftliche Einverständniserklärungen übertragen haben.',

    // Treatment eligibility
    LABEL_HIP_DOESNT_PARTICIPATE: 'Treatment not possible. Health insurance does not participate.',
    LABEL_NO_DOCTOR_CONTRACT: 'Settlement not possible. No contract signed.',
    LABEL_NO_PATIENT_CONSENT: 'Settlement not possible. No participation consent.',
    LABEL_DRUG_NOT_VALID: 'Settlement not possible with the selected drug.',



    // Statuses
    OP1: 'scheduled',
    OP2: 'performed',
    OP3: 'overdue',
    OP4: 'deleted',
    OP5: 'fee settlement in progress',
    OP6: 'confirmed by HIP',
    OP7: 'error correction required',
    OP8: 'payment in progress',
    OP9: 'paid',
    OP10: 'canceled',

    FS0: 'open',
    FS1: 'performed',
    FS2: 'submitted to HIP',
    FS5: 'payment in progress',
    FS4: 'confirmed by HIP',
    FS6: 'error correction',
    FS7: 'payment in process',
    FS8: 'canceled',
    FS9: 'rejection by HIP',
    FS10: 'reclaim the payment',
    FS11: 'Cancellation pending',
    FS12: 'paid',

    AC1: 'open',
    AC2: 'performed',
    AC3: 'overdue',
    AC4: 'withdrawn',

    AC6: 'fee settlement',
    AC7: 'confirmed by HIP',
    AC8: 'error correction necessary',
    AC9: 'payment in process',
    AC10: 'Paid',
    AC11: 'canceled',
    AC12: 'rejection by the - HIP',

    LABEL_EMPTY: '(empty)',

    // PRE-EXAMINATION LABELS
    LABEL_NEW_PREEXAMINATION: 'Neue Voruntersuchung',
    LABEL_DOCTOR_HAS_NO_CONSENT_ON_CONTRACT_WITH_PREEXAMINATION: 'Selected date doesn\'t fall into selected doctor\'s participation consent timespan ({{consentTimespan}})',
    LABEL_PATIENT_HAS_NO_CONSENT_ON_CONTRACT_WITH_PREEXAMINATION: 'Selected date doesn\'t fall into selected patient\'s participation consent timespan ({{consentTimespan}})',
    LABEL_PREEXAMINATION_SUBMITTED: 'Die Voruntersuchung wurde zur Abrechnung übermittelt.',
    LABEL_PREEXAMINATION_DATE_CANNOT_BE_IN_THE_FUTURE: 'Das angegebene Datum liegt in der Zukunft. Eine Übermittlung ist nicht möglich.',

    LABEL_PATIENTS_WITH_REJECTED_OCTS: 'Rejected oct',
    LABEL_THIS_PRACTICE: 'From this practice',
    LABEL_DIFFERENT_PRACTICE: 'From different practice',
    LABEL_INVALID_CONSENT: 'Without valid consent',

    LABEL_PREFERRED_PHARMACY: 'Preferred pharmacy',
    LABEL_PHARMACY: 'Pharmacy',
    LABEL_QUICK_ORDER_VERWNDEN: 'Quick-Order verwnden (Praxisadresse wird als Lieferadresse verwendet)',
    LABEL_QUICK_ORDER_GRACE_PERIOD: 'Passwort Grace-Periode bei Quick-Order verwenden',
    LABEL_OTHER_OPTIONS: 'Other options',

    LABEL_ADD_TO_CART: 'Add to cart',
    LABEL_SUBMIT_AND_CLOSE: 'Submit and close',
    LABEL_ORDER_PDF_NOTICE: 'Nach der Bestätigung steht Ihnen ein PDF-Auftrag zum Download zur Verfügung. Wenn Sie es erneut herunterladen möchten, können Sie es im Abschnitt "Bestellungen" finden.',

    //***BUTTONS GLOBAL***//
    BUTTON_404: 'Return to default page',
    BUTTON_PDF: 'PDF',

    BUTTON_CANCEL: 'Cancel',
    BUTTON_SAVE: 'Save',
    BUTTON_SAVE_SUBMIT: 'Save & Submit',

    BUTTON_BACK: 'Back',
    BUTTON_YES: 'Yes',
    BUTTON_NO: 'No',
    BUTTON_CONFIRM: 'CONFIRM',
    BUTTON_CONFIRM_NORMALCASE: 'Confirm',
    BUTTON_CONTINUE: 'Continue',
    BUTTON_FINISH: 'Finish',

    BUTTON_EDIT: 'Edit',
    BUTTON_SUBMIT: 'Submit',
    BUTTON_DONT_SUBMIT: 'Don\'t submit',
    BUTTON_DOWNLOAD: 'Download',
    op: 'Operation',
    ac: 'Aftercare',
    order: 'Order',
    participation: 'Participation',

    TOOLTIP_QUICK_ORDER_MSG: 'Um die Quick-Order zu nutzen, wählen Sie bitte eine bevorzugte Apotheke aus und geben Sie Praxisadresse, Ansprechpartner, Standardlieferdatum und Standardlieferzeit an.'
};
