INSERT INTO 
	cmn_sls_pricelist_discounts
	(
		CMN_SLS_Pricelist_DiscountID,
		PricelistVersion_RefID,
		ProductGroup_RefID,
		Product_RefID,
		Product_Variant_RefID,
		Product_Release_RefID,
		DiscountPercentAmount,
		DiscountValid_From,
		DiscountValid_To,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@CMN_SLS_Pricelist_DiscountID,
		@PricelistVersion_RefID,
		@ProductGroup_RefID,
		@Product_RefID,
		@Product_Variant_RefID,
		@Product_Release_RefID,
		@DiscountPercentAmount,
		@DiscountValid_From,
		@DiscountValid_To,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)