INSERT INTO 
	acc_fiscalyears
	(
		ACC_FiscalYearID,
		FiscalYearName,
		StartDate,
		EndDate,
		IsClosed,
		IsFinalized,
		IfFinalized_FollowingFiscalYear_RefID,
		IsFinalizationTriggered,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@ACC_FiscalYearID,
		@FiscalYearName,
		@StartDate,
		@EndDate,
		@IsClosed,
		@IsFinalized,
		@IfFinalized_FollowingFiscalYear_RefID,
		@IsFinalizationTriggered,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)