INSERT INTO 
	usr_not_notifications
	(
		USR_NOT_NotificationID,
		NotificationSubscription_RefID,
		R_Account_RefID,
		R_NotificationKey,
		Notification_Link,
		Notification_Text,
		IsViewed,
		ViewedOn_Date,
		Creation_Timestamp,
		IsDeleted,
		Tenant_RefID
	)
VALUES 
	(
		@USR_NOT_NotificationID,
		@NotificationSubscription_RefID,
		@R_Account_RefID,
		@R_NotificationKey,
		@Notification_Link,
		@Notification_Text,
		@IsViewed,
		@ViewedOn_Date,
		@Creation_Timestamp,
		@IsDeleted,
		@Tenant_RefID
	)