INSERT INTO 
	cmn_bpt_emp_employee_leaverequests
	(
		CMN_BPT_EMP_Employee_LeaveRequestID,
		RequestedBy_Employee_RefID,
		RequestedFor_Employee_RefID,
		CMN_CAL_Event_RefID,
		CMN_CAL_Event_Approval_RefID,
		CMN_BPT_STA_AbsenceReason_RefID,
		Comment,
		LeaveRequestCreationSource,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@CMN_BPT_EMP_Employee_LeaveRequestID,
		@RequestedBy_Employee_RefID,
		@RequestedFor_Employee_RefID,
		@CMN_CAL_Event_RefID,
		@CMN_CAL_Event_Approval_RefID,
		@CMN_BPT_STA_AbsenceReason_RefID,
		@Comment,
		@LeaveRequestCreationSource,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)