INSERT INTO 
	pps_tsk_task_staffbookings
	(
		PPS_TSK_Task_StaffBookingsID,
		PPS_TSK_Task_RefID,
		CMN_BPT_EMP_Employee_RefID,
		CreatedFrom_TaskTemplate_RequiredStaff_RefID,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@PPS_TSK_Task_StaffBookingsID,
		@PPS_TSK_Task_RefID,
		@CMN_BPT_EMP_Employee_RefID,
		@CreatedFrom_TaskTemplate_RequiredStaff_RefID,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)