INSERT INTO 
	tms_pro_developertask_priorities
	(
		TMS_PRO_DeveloperTask_PriorityID,
		GlobalPropertyMatchingID,
		Label_DictID,
		Description_DictID,
		IconLocationURL,
		Priority_Colour,
		Groups,
		PriorityLevel,
		IsPersistent,
		Creation_Timestamp,
		IsDeleted,
		Tenant_RefID
	)
VALUES 
	(
		@TMS_PRO_DeveloperTask_PriorityID,
		@GlobalPropertyMatchingID,
		@Label,
		@Description,
		@IconLocationURL,
		@Priority_Colour,
		@Groups,
		@PriorityLevel,
		@IsPersistent,
		@Creation_Timestamp,
		@IsDeleted,
		@Tenant_RefID
	)