INSERT INTO 
	hec_sub_substances
	(
		HEC_SUB_SubstanceID,
		HealthcareSubstanceITL,
		GlobalPropertyMatchingID,
		NarcoticAppendixStatus,
		CategoryByLawStatus,
		IsAntroposhopicalMedicine,
		IsChemical,
		IsHomeophaticMedicine,
		IsCOSubstance,
		IsExcipient,
		IsFoodAdditive,
		IsNaturalStimulant,
		IsAgriculturePesticide,
		IsPerscriptionRequired,
		IsCosmeticSubstance,
		IsActiveComponent,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@HEC_SUB_SubstanceID,
		@HealthcareSubstanceITL,
		@GlobalPropertyMatchingID,
		@NarcoticAppendixStatus,
		@CategoryByLawStatus,
		@IsAntroposhopicalMedicine,
		@IsChemical,
		@IsHomeophaticMedicine,
		@IsCOSubstance,
		@IsExcipient,
		@IsFoodAdditive,
		@IsNaturalStimulant,
		@IsAgriculturePesticide,
		@IsPerscriptionRequired,
		@IsCosmeticSubstance,
		@IsActiveComponent,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)