INSERT INTO 
	cmn_bpt_sta_absencereasons
	(
		CMN_BPT_STA_AbsenceReasonID,
		ShortName,
		Name_DictID,
		Description_DictID,
		AbsenceReason_Type_RefID,
		ColorCode,
		Parent_RefID,
		IsAuthorizationRequired,
		IsIncludedInCapacityCalculation,
		IsAllowedAbsence,
		IsDeactivated,
		IsCarryOverEnabled,
		IsCaryOverLimited,
		IfCarryOverLimited_MaximumAmount_Hrs,
		IsLeaveTimeReducing_WorkingHours,
		IsLeaveTimeReducing_OverHours,
		IsLeaveTimeReducing_OverDays,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@CMN_BPT_STA_AbsenceReasonID,
		@ShortName,
		@Name,
		@Description,
		@AbsenceReason_Type_RefID,
		@ColorCode,
		@Parent_RefID,
		@IsAuthorizationRequired,
		@IsIncludedInCapacityCalculation,
		@IsAllowedAbsence,
		@IsDeactivated,
		@IsCarryOverEnabled,
		@IsCaryOverLimited,
		@IfCarryOverLimited_MaximumAmount_Hrs,
		@IsLeaveTimeReducing_WorkingHours,
		@IsLeaveTimeReducing_OverHours,
		@IsLeaveTimeReducing_OverDays,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)