INSERT INTO 
	hec_cas_cases
	(
		HEC_CAS_CaseID,
		Patient_RefID,
		CreatedBy_BusinessParticipant_RefID,
		CaseNumber,
		CaseTitle_DictID,
		CaseDescription_DictID,
		IsClosed,
		IsSolved,
		Patient_FirstName,
		Patient_LastName,
		Patient_Gender,
		Patient_Age,
		Patient_BirthDate,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@HEC_CAS_CaseID,
		@Patient_RefID,
		@CreatedBy_BusinessParticipant_RefID,
		@CaseNumber,
		@CaseTitle,
		@CaseDescription,
		@IsClosed,
		@IsSolved,
		@Patient_FirstName,
		@Patient_LastName,
		@Patient_Gender,
		@Patient_Age,
		@Patient_BirthDate,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)