INSERT INTO 
	ord_prc_rfp_supplierproposalresponse_headers
	(
		ORD_PRC_RFP_SupplierProposalResponse_HeaderID,
		ProposalResponseHeaderITPL,
		CreatedFor_RequestForProposal_Header_RefID,
		OfferReceivedFrom_RegisteredBusinessParticipant_RefID,
		DefaultCurrency_RefID,
		ValidThrough,
		TotalPrice_WithoutTax,
		TotalPrice_IncludingTax,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@ORD_PRC_RFP_SupplierProposalResponse_HeaderID,
		@ProposalResponseHeaderITPL,
		@CreatedFor_RequestForProposal_Header_RefID,
		@OfferReceivedFrom_RegisteredBusinessParticipant_RefID,
		@DefaultCurrency_RefID,
		@ValidThrough,
		@TotalPrice_WithoutTax,
		@TotalPrice_IncludingTax,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)