UPDATE 
	ord_prc_rfp_supplierproposalresponse_headers
SET 
	ProposalResponseHeaderITPL=@ProposalResponseHeaderITPL,
	CreatedFor_RequestForProposal_Header_RefID=@CreatedFor_RequestForProposal_Header_RefID,
	OfferReceivedFrom_RegisteredBusinessParticipant_RefID=@OfferReceivedFrom_RegisteredBusinessParticipant_RefID,
	DefaultCurrency_RefID=@DefaultCurrency_RefID,
	ValidThrough=@ValidThrough,
	TotalPrice_WithoutTax=@TotalPrice_WithoutTax,
	TotalPrice_IncludingTax=@TotalPrice_IncludingTax,
	Creation_Timestamp=@Creation_Timestamp,
	Tenant_RefID=@Tenant_RefID,
	IsDeleted=@IsDeleted
WHERE 
	ORD_PRC_RFP_SupplierProposalResponse_HeaderID = @ORD_PRC_RFP_SupplierProposalResponse_HeaderID