INSERT INTO 
	ord_dis_distributionorder_header_history
	(
		ORD_DIS_DistributionOrder_Header_HistoryID,
		DistributionOrder_Header_RefID,
		TriggeredBy_BusinessParticipant_RefID,
		IsCreated,
		IsModified,
		IsCanceled,
		Comment,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@ORD_DIS_DistributionOrder_Header_HistoryID,
		@DistributionOrder_Header_RefID,
		@TriggeredBy_BusinessParticipant_RefID,
		@IsCreated,
		@IsModified,
		@IsCanceled,
		@Comment,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)