INSERT INTO 
	cmn_cal_repetitionpatterns_weekly
	(
		CMN_CAL_RepetitionPattern_WeeklyID,
		Repetition_RefID,
		Repetition_EveryNumberOfWeeks,
		HasRepeatingOn_Mondays,
		HasRepeatingOn_Tuesdays,
		HasRepeatingOn_Wednesdays,
		HasRepeatingOn_Thursdays,
		HasRepeatingOn_Fridays,
		HasRepeatingOn_Saturdays,
		HasRepeatingOn_Sundays,
		Creation_Timestamp,
		IsDeleted,
		Tenant_RefID
	)
VALUES 
	(
		@CMN_CAL_RepetitionPattern_WeeklyID,
		@Repetition_RefID,
		@Repetition_EveryNumberOfWeeks,
		@HasRepeatingOn_Mondays,
		@HasRepeatingOn_Tuesdays,
		@HasRepeatingOn_Wednesdays,
		@HasRepeatingOn_Thursdays,
		@HasRepeatingOn_Fridays,
		@HasRepeatingOn_Saturdays,
		@HasRepeatingOn_Sundays,
		@Creation_Timestamp,
		@IsDeleted,
		@Tenant_RefID
	)