INSERT INTO 
	cmn_bpt_emp_effectiveworktime_headers
	(
		CMN_STR_PPS_EffectiveWorkTime_HeaderID,
		Employee_RefID,
		EffectiveBusinessDay,
		SheduleBreakTemplate_RefID,
		IsBreakTimeManualySpecified,
		BreakDurationTime_in_sec,
		WorktimeComment,
		ContractWorkerText,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@CMN_STR_PPS_EffectiveWorkTime_HeaderID,
		@Employee_RefID,
		@EffectiveBusinessDay,
		@SheduleBreakTemplate_RefID,
		@IsBreakTimeManualySpecified,
		@BreakDurationTime_in_sec,
		@WorktimeComment,
		@ContractWorkerText,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)