INSERT INTO 
	log_shp_shipment_positions
	(
		LOG_SHP_Shipment_PositionID,
		ShipmentPositionITL,
		LOG_SHP_Shipment_Header_RefID,
		CMN_PRO_Product_RefID,
		CMN_PRO_ProductVariant_RefID,
		CMN_PRO_ProductRelease_RefID,
		TrackingInstance_ToShip_RefID,
		QuantityToShip,
		ShipmentPosition_ValueWithoutTax,
		ShipmentPosition_PricePerUnitValueWithoutTax,
		IsCancelled,
		CancelledBy_BusinessParticipant_RefID,
		CancelledOnDate,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@LOG_SHP_Shipment_PositionID,
		@ShipmentPositionITL,
		@LOG_SHP_Shipment_Header_RefID,
		@CMN_PRO_Product_RefID,
		@CMN_PRO_ProductVariant_RefID,
		@CMN_PRO_ProductRelease_RefID,
		@TrackingInstance_ToShip_RefID,
		@QuantityToShip,
		@ShipmentPosition_ValueWithoutTax,
		@ShipmentPosition_PricePerUnitValueWithoutTax,
		@IsCancelled,
		@CancelledBy_BusinessParticipant_RefID,
		@CancelledOnDate,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)