INSERT INTO 
	tms_pro_comments
	(
		TMS_PRO_CommentID,
		Comment_BoundTo_Project_RefID,
		Comment_BoundTo_BusinessTask_RefID,
		Comment_BoundTo_Feature_RefID,
		Comment_BoundTo_DeveloperTask_RefID,
		IsComment_BoundToBusinessTask,
		IsComment_BoundToFeature,
		IsComment_BoundToDeveloperTask,
		Comment_Quoatation_RefID,
		Comment_CreatedByAccount_RefID,
		Comment_Quotation_Text,
		Comment_TextContent,
		Creation_Timestamp,
		IsDeleted,
		Tenant_RefID
	)
VALUES 
	(
		@TMS_PRO_CommentID,
		@Comment_BoundTo_Project_RefID,
		@Comment_BoundTo_BusinessTask_RefID,
		@Comment_BoundTo_Feature_RefID,
		@Comment_BoundTo_DeveloperTask_RefID,
		@IsComment_BoundToBusinessTask,
		@IsComment_BoundToFeature,
		@IsComment_BoundToDeveloperTask,
		@Comment_Quoatation_RefID,
		@Comment_CreatedByAccount_RefID,
		@Comment_Quotation_Text,
		@Comment_TextContent,
		@Creation_Timestamp,
		@IsDeleted,
		@Tenant_RefID
	)