INSERT INTO 
	ord_cuo_customerorder_position_customizations
	(
		ORD_CUO_CustomerOrder_Position_CustomizationID,
		CustomerOrder_Position_RefID,
		Customization_Name,
		CustomizationVariant_Name,
		ValuePerUnit,
		ValueTotal,
		Customization_Variant_RefID,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@ORD_CUO_CustomerOrder_Position_CustomizationID,
		@CustomerOrder_Position_RefID,
		@Customization_Name,
		@CustomizationVariant_Name,
		@ValuePerUnit,
		@ValueTotal,
		@Customization_Variant_RefID,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)