INSERT INTO 
	acc_bok_accounting_bookinglines
	(
		ACC_BOK_Accounting_BookingLineID,
		ExternalBankKey,
		PartOfAccountingTransaction_RefID,
		BookingAccount_RefID,
		TransactionValue,
		DateOfBooking,
		DateOfTransaction,
		SenderText,
		SenderComment,
		Currency_RefID,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@ACC_BOK_Accounting_BookingLineID,
		@ExternalBankKey,
		@PartOfAccountingTransaction_RefID,
		@BookingAccount_RefID,
		@TransactionValue,
		@DateOfBooking,
		@DateOfTransaction,
		@SenderText,
		@SenderComment,
		@Currency_RefID,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)