INSERT INTO 
	tms_pro_businesstask_status
	(
		TMS_PRO_BusinessTask_StatusID,
		GlobalPropertyMatchingID,
		Label_DictID,
		Description_DictID,
		IsPersistent,
		Creation_Timestamp,
		IsDeleted,
		Tenant_RefID
	)
VALUES 
	(
		@TMS_PRO_BusinessTask_StatusID,
		@GlobalPropertyMatchingID,
		@Label,
		@Description,
		@IsPersistent,
		@Creation_Timestamp,
		@IsDeleted,
		@Tenant_RefID
	)