INSERT INTO 
	cmn_pro_catalog_revisions
	(
		CMN_PRO_Catalog_RevisionID,
		CMN_PRO_Catalog_RefID,
		CatalogRevision_Name,
		CatalogRevision_Description,
		RevisionNumber,
		Valid_From,
		Valid_Through,
		PublishedBy_BusinessParticipant_RefID,
		Default_PricelistRelease_RefID,
		PublishedOn_Date,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@CMN_PRO_Catalog_RevisionID,
		@CMN_PRO_Catalog_RefID,
		@CatalogRevision_Name,
		@CatalogRevision_Description,
		@RevisionNumber,
		@Valid_From,
		@Valid_Through,
		@PublishedBy_BusinessParticipant_RefID,
		@Default_PricelistRelease_RefID,
		@PublishedOn_Date,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)