INSERT INTO 
	hec_patient_healthinsurances
	(
		HEC_Patient_HealthInsurancesID,
		HealthInsurance_Number,
		HealthInsurance_State_RefID,
		Patient_RefID,
		HIS_HealthInsurance_Company_RefID,
		IsPrimary,
		SequenceNumber,
		InsuranceStateCode,
		InsuranceValidFrom,
		InsuranceValidThrough,
		IsNotSelfInsured,
		IsNotSelfInsured_InsuredPersonName,
		IsNotSelfInsured_InsuredPersonBirthday,
		Creation_Timestamp,
		IsDeleted,
		Tenant_RefID
	)
VALUES 
	(
		@HEC_Patient_HealthInsurancesID,
		@HealthInsurance_Number,
		@HealthInsurance_State_RefID,
		@Patient_RefID,
		@HIS_HealthInsurance_Company_RefID,
		@IsPrimary,
		@SequenceNumber,
		@InsuranceStateCode,
		@InsuranceValidFrom,
		@InsuranceValidThrough,
		@IsNotSelfInsured,
		@IsNotSelfInsured_InsuredPersonName,
		@IsNotSelfInsured_InsuredPersonBirthday,
		@Creation_Timestamp,
		@IsDeleted,
		@Tenant_RefID
	)