INSERT INTO 
	doc_documentrevisions
	(
		DOC_DocumentRevisionID,
		Document_RefID,
		Revision,
		IsLocked,
		IsLastRevision,
		UploadedByAccount,
		File_Name,
		File_Description,
		File_SourceLocation,
		File_ServerLocation,
		File_MIMEType,
		File_Extension,
		File_Size_Bytes,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@DOC_DocumentRevisionID,
		@Document_RefID,
		@Revision,
		@IsLocked,
		@IsLastRevision,
		@UploadedByAccount,
		@File_Name,
		@File_Description,
		@File_SourceLocation,
		@File_ServerLocation,
		@File_MIMEType,
		@File_Extension,
		@File_Size_Bytes,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)