INSERT INTO 
	log_shp_shipment_types
	(
		LOG_SHP_Shipment_TypeID,
		GlobalPropertyMatchingID,
		ShipmentType_Name_DictID,
		ShipmentType_Description_DictID,
		IsCustomerPickup,
		IsPartialPickingPermitted,
		IsFixedPricePerShipment,
		IfFixedPricePerShipment_Price_RefID,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@LOG_SHP_Shipment_TypeID,
		@GlobalPropertyMatchingID,
		@ShipmentType_Name,
		@ShipmentType_Description,
		@IsCustomerPickup,
		@IsPartialPickingPermitted,
		@IsFixedPricePerShipment,
		@IfFixedPricePerShipment_Price_RefID,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)