INSERT INTO 
	imo_questionnaire_submissions
	(
		IMO_Questionnaire_SubmissionID,
		Questionnaire_RefID,
		SubmittedBy_Account_RefID,
		QuestionnaireVersion_RefID,
		RealEstate_RefID,
		ImageGroup_RefID,
		Questionnaire_SubmissionBinder_RefID,
		Title,
		SubmittedOn,
		CreatedOn,
		LastUpdateOn,
		ResubmissionVersion,
		LastEdited_ByAccount_RefID,
		LastEdited_Date,
		Creation_Timestamp,
		IsDeleted,
		Tenant_RefID
	)
VALUES 
	(
		@IMO_Questionnaire_SubmissionID,
		@Questionnaire_RefID,
		@SubmittedBy_Account_RefID,
		@QuestionnaireVersion_RefID,
		@RealEstate_RefID,
		@ImageGroup_RefID,
		@Questionnaire_SubmissionBinder_RefID,
		@Title,
		@SubmittedOn,
		@CreatedOn,
		@LastUpdateOn,
		@ResubmissionVersion,
		@LastEdited_ByAccount_RefID,
		@LastEdited_Date,
		@Creation_Timestamp,
		@IsDeleted,
		@Tenant_RefID
	)