INSERT INTO 
	cmn_bpt_emp_extraworkcalculation_surcharges_details
	(
		CMN_BPT_EMP_ExtraWorkCalculation_Surcharges_DetailsID,
		ExtraWorkCalculation_Surcharge_RefID,
		TimeFrom_in_mins,
		TimeTo_in_mins,
		Surcharge_Standard_PercentValue,
		Surcharge_StartedBeforeMidnight_PercentValue,
		BoundTo_StructureCalendarEvent_Type_RefID,
		BoundTo_StructureCalendarEvent_RefID,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@CMN_BPT_EMP_ExtraWorkCalculation_Surcharges_DetailsID,
		@ExtraWorkCalculation_Surcharge_RefID,
		@TimeFrom_in_mins,
		@TimeTo_in_mins,
		@Surcharge_Standard_PercentValue,
		@Surcharge_StartedBeforeMidnight_PercentValue,
		@BoundTo_StructureCalendarEvent_Type_RefID,
		@BoundTo_StructureCalendarEvent_RefID,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)