INSERT INTO 
	hec_cas_case_universalpropertyvalue
	(
		HEC_CAS_Case_UniversalPropertyValueID,
		HEC_CAS_Case_RefID,
		HEC_CAS_Case_UniversalProperty_RefID,
		Value_String,
		Value_Number,
		Value_Boolean,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@HEC_CAS_Case_UniversalPropertyValueID,
		@HEC_CAS_Case_RefID,
		@HEC_CAS_Case_UniversalProperty_RefID,
		@Value_String,
		@Value_Number,
		@Value_Boolean,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)