INSERT INTO 
	ord_dis_distributionorder_positions
	(
		ORD_DIS_DistributionOrder_PositionID,
		DistributionOrder_Header_RefID,
		Product_RefID,
		Product_Variant_RefID,
		Product_Release_RefID,
		Quantity,
		InternallyCharged_TotalNetPriceValue,
		InternallyCharged_TotalPointValue,
		Position_OrdinalNumber,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@ORD_DIS_DistributionOrder_PositionID,
		@DistributionOrder_Header_RefID,
		@Product_RefID,
		@Product_Variant_RefID,
		@Product_Release_RefID,
		@Quantity,
		@InternallyCharged_TotalNetPriceValue,
		@InternallyCharged_TotalPointValue,
		@Position_OrdinalNumber,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)