INSERT INTO 
	cmn_bpt_emp_effectiveworktime_positionhistory
	(
		CMN_BPT_EMP_EffectiveWorkTime_PositionHistoryID,
		EffectiveWorkTime_Header_RefID,
		EffectiveWorkTime_Position_RefID,
		TriggeredAt_Date,
		TriggeredBy_BusinessParticipant_RefID,
		TriggeredBy_SourceOfEntry,
		Comment,
		Activity_RefID,
		Workplace_RefID,
		CMN_BPT_EMP_Employee_LeaveRequest_RefID,
		WorkTime_StartTime,
		WorkTime_Duration_in_sec,
		SourceOfEntry,
		IsCreated,
		IsModified,
		IsDeleted,
		Creation_Timestamp,
		Tenant_RefID,
		Modification_Timestamp
	)
VALUES 
	(
		@CMN_BPT_EMP_EffectiveWorkTime_PositionHistoryID,
		@EffectiveWorkTime_Header_RefID,
		@EffectiveWorkTime_Position_RefID,
		@TriggeredAt_Date,
		@TriggeredBy_BusinessParticipant_RefID,
		@TriggeredBy_SourceOfEntry,
		@Comment,
		@Activity_RefID,
		@Workplace_RefID,
		@CMN_BPT_EMP_Employee_LeaveRequest_RefID,
		@WorkTime_StartTime,
		@WorkTime_Duration_in_sec,
		@SourceOfEntry,
		@IsCreated,
		@IsModified,
		@IsDeleted,
		@Creation_Timestamp,
		@Tenant_RefID,
		@Modification_Timestamp
	)