INSERT INTO 
	tms_pro_request_2_businesstask
	(
		AssignmentID,
		TMS_PRO_Request_RefID,
		TMS_PRO_BusinessTask_RefID,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@AssignmentID,
		@TMS_PRO_Request_RefID,
		@TMS_PRO_BusinessTask_RefID,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)