INSERT INTO 
	usr_device_activityhistory
	(
		USR_Device_ActivityHistoryID,
		Device_RefID,
		Performing_Account_RefID,
		DateOfActivity,
		WasDevice_Configured,
		WasDevice_Configured_WithConfigurationCode_RefID,
		WasDevice_RequestingDSC,
		WasBanned,
		WasUnbanned,
		WasCreatedSession,
		WasOtherRelevantActivity,
		ActivityComment,
		AccountComment,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@USR_Device_ActivityHistoryID,
		@Device_RefID,
		@Performing_Account_RefID,
		@DateOfActivity,
		@WasDevice_Configured,
		@WasDevice_Configured_WithConfigurationCode_RefID,
		@WasDevice_RequestingDSC,
		@WasBanned,
		@WasUnbanned,
		@WasCreatedSession,
		@WasOtherRelevantActivity,
		@ActivityComment,
		@AccountComment,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)