INSERT INTO 
	cmn_trl_trustrelationrequests
	(
		CMN_TRL_TrustRelationRequestID,
		RequestFor_TrustRelationType_RefID,
		Requesting_BusinessParticipant_RefID,
		TrustRelationRequestITL,
		Title,
		Comment,
		IsApproved,
		IsRejected,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@CMN_TRL_TrustRelationRequestID,
		@RequestFor_TrustRelationType_RefID,
		@Requesting_BusinessParticipant_RefID,
		@TrustRelationRequestITL,
		@Title,
		@Comment,
		@IsApproved,
		@IsRejected,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)