INSERT INTO 
	bil_billposition_transmitionstatuses
	(
		BIL_BillPosition_TransmitionStatusID,
		BillPosition_RefID,
		TransmitionStatusKey,
		TransmitionCode,
		PrimaryComment,
		SecondaryComment,
		TransmittedOnDate,
		IsActive,
		TransmissionDataXML,
		IsTransmitionStatusManuallySet,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@BIL_BillPosition_TransmitionStatusID,
		@BillPosition_RefID,
		@TransmitionStatusKey,
		@TransmitionCode,
		@PrimaryComment,
		@SecondaryComment,
		@TransmittedOnDate,
		@IsActive,
		@TransmissionDataXML,
		@IsTransmitionStatusManuallySet,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)