INSERT INTO 
	cmn_bpt_emp_employmentrelationship_templates
	(
		CMN_BPT_EMP_EmploymentRelationship_TemplateID,
		Template_StartDate,
		Template_EndDate,
		Template_Name_DictID,
		RequiredMonthlyHours,
		RequiredWeeklyHours,
		RequiredDailyHours,
		R_WeeklyWorkPattern,
		Creation_Timestamp,
		IsDeleted,
		Tenant_RefID
	)
VALUES 
	(
		@CMN_BPT_EMP_EmploymentRelationship_TemplateID,
		@Template_StartDate,
		@Template_EndDate,
		@Template_Name,
		@RequiredMonthlyHours,
		@RequiredWeeklyHours,
		@RequiredDailyHours,
		@R_WeeklyWorkPattern,
		@Creation_Timestamp,
		@IsDeleted,
		@Tenant_RefID
	)