INSERT INTO 
	cmn_cal_weeklyofficehours_intervals
	(
		CMN_CAL_WeeklyOfficeHours_IntervalID,
		WeeklyOfficeHours_Template_RefID,
		IsWholeDay,
		TimeFrom_InMinutes,
		TimeTo_InMinutes,
		IsMonday,
		IsTuesday,
		IsWednesday,
		IsThursday,
		IsFriday,
		IsSaturday,
		IsSunday,
		Creation_Timestamp,
		IsDeleted,
		Tenant_RefID
	)
VALUES 
	(
		@CMN_CAL_WeeklyOfficeHours_IntervalID,
		@WeeklyOfficeHours_Template_RefID,
		@IsWholeDay,
		@TimeFrom_InMinutes,
		@TimeTo_InMinutes,
		@IsMonday,
		@IsTuesday,
		@IsWednesday,
		@IsThursday,
		@IsFriday,
		@IsSaturday,
		@IsSunday,
		@Creation_Timestamp,
		@IsDeleted,
		@Tenant_RefID
	)