INSERT INTO 
	ord_cuo_customerorder_position_2_shipmentposition
	(
		AssignmentID,
		ORD_CUO_CustomerOrder_Position_RefID,
		LOG_SHP_Shipment_Position_RefID,
		CMN_BPT_CTM_OrganizationalUnit_RefID,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@AssignmentID,
		@ORD_CUO_CustomerOrder_Position_RefID,
		@LOG_SHP_Shipment_Position_RefID,
		@CMN_BPT_CTM_OrganizationalUnit_RefID,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)