INSERT INTO 
	res_bld_buildings
	(
		RES_BLD_BuildingID,
		Building_CurrentAverageRentPrice_per_sqm_RefID,
		BuildingRevisionHeader_RefID,
		Building_BalconyPortionPercent,
		Building_Name,
		Building_DocumentationStructure_RefID,
		IsContaminationSuspected,
		Building_NumberOfFloors,
		Building_ElevatorCoveragePercent,
		Building_NumberOfAppartments,
		Building_NumberOfOccupiedAppartments,
		Building_NumberOfOffices,
		Building_NumberOfRetailUnits,
		Building_NumberOfProductionUnits,
		Building_NumberOfOtherUnits,
		Creation_Timestamp,
		IsDeleted,
		Tenant_RefID
	)
VALUES 
	(
		@RES_BLD_BuildingID,
		@Building_CurrentAverageRentPrice_per_sqm_RefID,
		@BuildingRevisionHeader_RefID,
		@Building_BalconyPortionPercent,
		@Building_Name,
		@Building_DocumentationStructure_RefID,
		@IsContaminationSuspected,
		@Building_NumberOfFloors,
		@Building_ElevatorCoveragePercent,
		@Building_NumberOfAppartments,
		@Building_NumberOfOccupiedAppartments,
		@Building_NumberOfOffices,
		@Building_NumberOfRetailUnits,
		@Building_NumberOfProductionUnits,
		@Building_NumberOfOtherUnits,
		@Creation_Timestamp,
		@IsDeleted,
		@Tenant_RefID
	)