INSERT INTO 
	cmn_per_personinfo
	(
		CMN_PER_PersonInfoID,
		Address_RefID,
		Title,
		Salutation_General,
		Salutation_Letter,
		Initials,
		FirstName,
		LastName,
		PrimaryEmail,
		ProfileImage_Document_RefID,
		BirthDate,
		Gender,
		NumberOfChildren,
		IsRepresentedByLegalGuardian,
		IsDead,
		DateOfDeath,
		AgeCalculation_YearOfBirth,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@CMN_PER_PersonInfoID,
		@Address_RefID,
		@Title,
		@Salutation_General,
		@Salutation_Letter,
		@Initials,
		@FirstName,
		@LastName,
		@PrimaryEmail,
		@ProfileImage_Document_RefID,
		@BirthDate,
		@Gender,
		@NumberOfChildren,
		@IsRepresentedByLegalGuardian,
		@IsDead,
		@DateOfDeath,
		@AgeCalculation_YearOfBirth,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)