INSERT INTO 
	ord_cuo_customerorderreturn_positions
	(
		ORD_CUO_CustomerOrderReturn_PositionID,
		CustomerOrderReturnHeader_RefID,
		CorrespondingReceiptPosition_RefID,
		Position_Quantity,
		Position_ValuePerUnit,
		Position_ValueTotal,
		Position_Comment,
		Position_Description,
		Position_Unit_RefID,
		CMN_PRO_Product_RefID,
		CMN_PRO_Product_Variant_RefID,
		CMN_PRO_Product_Release_RefID,
		Price_From_PricelistRelease_RefID,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@ORD_CUO_CustomerOrderReturn_PositionID,
		@CustomerOrderReturnHeader_RefID,
		@CorrespondingReceiptPosition_RefID,
		@Position_Quantity,
		@Position_ValuePerUnit,
		@Position_ValueTotal,
		@Position_Comment,
		@Position_Description,
		@Position_Unit_RefID,
		@CMN_PRO_Product_RefID,
		@CMN_PRO_Product_Variant_RefID,
		@CMN_PRO_Product_Release_RefID,
		@Price_From_PricelistRelease_RefID,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)