INSERT INTO 
	cmn_pro_ass_assortmentvariants
	(
		CMN_PRO_ASS_AssortmentVariantID,
		Ext_CMN_PRO_Product_Variant_RefID,
		DistributionPrice_RefID,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@CMN_PRO_ASS_AssortmentVariantID,
		@Ext_CMN_PRO_Product_Variant_RefID,
		@DistributionPrice_RefID,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)