INSERT INTO 
	ord_prc_procurementorder_position_history
	(
		ORD_PRC_ProcurementOrder_Position_HistoryID,
		ProcurementOrder_Position_RefID,
		IsCreated,
		IsModified,
		IsRemoved,
		TriggeredBy_BusinessParticipant_RefID,
		Comment,
		IsLivePriceRequestProcessTriggered,
		TriggeredFor_Quantity,
		IsLivePriceRequestProcessAnswered,
		AnsweredWith_TotalPrice,
		AnsweredWith_Currency_RefID,
		AnsweredWith_DeliverableQuantity,
		AnsweredWith_EarliestDeliveryDate,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@ORD_PRC_ProcurementOrder_Position_HistoryID,
		@ProcurementOrder_Position_RefID,
		@IsCreated,
		@IsModified,
		@IsRemoved,
		@TriggeredBy_BusinessParticipant_RefID,
		@Comment,
		@IsLivePriceRequestProcessTriggered,
		@TriggeredFor_Quantity,
		@IsLivePriceRequestProcessAnswered,
		@AnsweredWith_TotalPrice,
		@AnsweredWith_Currency_RefID,
		@AnsweredWith_DeliverableQuantity,
		@AnsweredWith_EarliestDeliveryDate,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)