INSERT INTO 
	ord_dis_distributionorder_position_customizations
	(
		ORD_DIS_DistributionOrder_Position_CustomizationID,
		DistributionOrder_Position_RefID,
		Customization_Name,
		CustomizationVariant_Name,
		ValuePerUnit,
		ValueTotal,
		Customization_Variant_RefID,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@ORD_DIS_DistributionOrder_Position_CustomizationID,
		@DistributionOrder_Position_RefID,
		@Customization_Name,
		@CustomizationVariant_Name,
		@ValuePerUnit,
		@ValueTotal,
		@Customization_Variant_RefID,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)