INSERT INTO 
	cmn_cal_repetitionpatterns_relative
	(
		CMN_CAL_RepetitionPattern_RelativeID,
		Ordinal,
		IsWeekDay,
		IsWeekendDay,
		IsMonday,
		IsTuesday,
		IsWednesday,
		IsThursday,
		IsFriday,
		IsSaturday,
		IsSunday,
		Creation_Timestamp,
		IsDeleted,
		Tenant_RefID
	)
VALUES 
	(
		@CMN_CAL_RepetitionPattern_RelativeID,
		@Ordinal,
		@IsWeekDay,
		@IsWeekendDay,
		@IsMonday,
		@IsTuesday,
		@IsWednesday,
		@IsThursday,
		@IsFriday,
		@IsSaturday,
		@IsSunday,
		@Creation_Timestamp,
		@IsDeleted,
		@Tenant_RefID
	)