INSERT INTO 
	cmn_btp_customer_promiseddeliverytimes
	(
		CMN_BTP_Supplier_DefaultDeliveryTimeID,
		Customer_RefID,
		CRONExpression,
		Specified_Product_Group_RefID,
		Specified_Product_RefID,
		Specified_Product_Variant_RefID,
		Specified_Product_Release_RefID,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@CMN_BTP_Supplier_DefaultDeliveryTimeID,
		@Customer_RefID,
		@CRONExpression,
		@Specified_Product_Group_RefID,
		@Specified_Product_RefID,
		@Specified_Product_Variant_RefID,
		@Specified_Product_Release_RefID,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)