UPDATE 
	pps_tsk_task_template_organizationalunitavailabilities
SET 
	PPS_TSK_Task_Template_RefID=@PPS_TSK_Task_Template_RefID,
	CMN_STR_Office_RefID=@CMN_STR_Office_RefID,
	Creation_Timestamp=@Creation_Timestamp,
	Tenant_RefID=@Tenant_RefID,
	IsDeleted=@IsDeleted
WHERE 
	PPS_TSK_Task_Template_OrganizationalUnitAvailabilityID = @PPS_TSK_Task_Template_OrganizationalUnitAvailabilityID