INSERT INTO 
	hec_act_performedaction_procedures
	(
		HEC_ACT_PerformedAction_ProcedureID,
		ActionProcedureITL,
		HEC_ACT_PerformedAction_RefID,
		PotentialProcedure_RefID,
		PotentialProcedure_Name,
		PotentialProcedure_Code,
		PotentialProcedure_Localization_RefID,
		PotentialProcedure_Localization_Name,
		PotentialProcedure_Localization_Code,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@HEC_ACT_PerformedAction_ProcedureID,
		@ActionProcedureITL,
		@HEC_ACT_PerformedAction_RefID,
		@PotentialProcedure_RefID,
		@PotentialProcedure_Name,
		@PotentialProcedure_Code,
		@PotentialProcedure_Localization_RefID,
		@PotentialProcedure_Localization_Name,
		@PotentialProcedure_Localization_Code,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)