
	SELECT
	  CMN_PRO_PRODUCTS.CMN_PRO_ProductID,
	  CMN_PRO_PRODUCTS.ProductITL
	FROM
	  CMN_PRO_PRODUCTS
	WHERE
	  CMN_PRO_PRODUCTS.ProductITL = @ProductITLList
	  AND CMN_PRO_PRODUCTS.Tenant_RefID = @TenantID
	  AND CMN_PRO_PRODUCTS.IsDeleted = 0
  