INSERT INTO 
	cmn_str_pps_dailyworkschedules
	(
		CMN_STR_PPS_DailyWorkScheduleID,
		Employee_RefID,
		WorkSheduleDate,
		SheduleBreakTemplate_RefID,
		R_WorkDay_Start_in_sec,
		R_WorkDay_End_in_sec,
		R_WorkDay_Duration_in_sec,
		IsBreakTimeManualySpecified,
		BreakDurationTime_in_sec,
		R_ContractSpecified_WorkingTime_in_sec,
		WorkingSheduleComment,
		ContractWorkerText,
		IsWorkShedule_Confirmed,
		WorkShedule_ConfirmedBy_Account_RefID,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@CMN_STR_PPS_DailyWorkScheduleID,
		@Employee_RefID,
		@WorkSheduleDate,
		@SheduleBreakTemplate_RefID,
		@R_WorkDay_Start_in_sec,
		@R_WorkDay_End_in_sec,
		@R_WorkDay_Duration_in_sec,
		@IsBreakTimeManualySpecified,
		@BreakDurationTime_in_sec,
		@R_ContractSpecified_WorkingTime_in_sec,
		@WorkingSheduleComment,
		@ContractWorkerText,
		@IsWorkShedule_Confirmed,
		@WorkShedule_ConfirmedBy_Account_RefID,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)