INSERT INTO 
	hec_cmt_community_offeredmembershiptypes
	(
		HEC_CMT_Community_OfferedMembershipTypeID,
		HealthcareCommunityOfferedMembershipTypesITL,
		Community_RefID,
		OfferedMembershipType_DisplayName,
		OfferedMembershipType_Name_DictID,
		IsAvailableFor_Tenants,
		IsAvailableFor_Doctors,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@HEC_CMT_Community_OfferedMembershipTypeID,
		@HealthcareCommunityOfferedMembershipTypesITL,
		@Community_RefID,
		@OfferedMembershipType_DisplayName,
		@OfferedMembershipType_Name,
		@IsAvailableFor_Tenants,
		@IsAvailableFor_Doctors,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)