INSERT INTO 
	cmn_numberranges
	(
		CMN_NumberRangeID,
		NumberRange_UsageArea_RefID,
		NumberRange_Name,
		Value_Current,
		Value_Start,
		Value_End,
		FixedPrefix,
		Formatting_NumberLength,
		Formatting_LeadingFillCharacter,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@CMN_NumberRangeID,
		@NumberRange_UsageArea_RefID,
		@NumberRange_Name,
		@Value_Current,
		@Value_Start,
		@Value_End,
		@FixedPrefix,
		@Formatting_NumberLength,
		@Formatting_LeadingFillCharacter,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)