INSERT INTO 
	hec_patient_treatment
	(
		HEC_Patient_TreatmentID,
		PotentialTreatment_RefID,
		TreatmentITL,
		IsTreatmentFollowup,
		IfTreatmentFollowup_FromTreatment_RefID,
		TreatmentPractice_RefID,
		IsTreatmentPerformed,
		IfTreatmentPerformed_ByDoctor_RefID,
		IfTreatmentPerformed_Date,
		IsScheduled,
		IfSheduled_Date,
		IfSheduled_ForDoctor_RefID,
		IsTreatmentBilled,
		IfTreatmentBilled_Date,
		Treatment_Comment,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@HEC_Patient_TreatmentID,
		@PotentialTreatment_RefID,
		@TreatmentITL,
		@IsTreatmentFollowup,
		@IfTreatmentFollowup_FromTreatment_RefID,
		@TreatmentPractice_RefID,
		@IsTreatmentPerformed,
		@IfTreatmentPerformed_ByDoctor_RefID,
		@IfTreatmentPerformed_Date,
		@IsScheduled,
		@IfSheduled_Date,
		@IfSheduled_ForDoctor_RefID,
		@IsTreatmentBilled,
		@IfTreatmentBilled_Date,
		@Treatment_Comment,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)