INSERT INTO 
	cmn_pro_subscribedcatalogs
	(
		CMN_PRO_SubscribedCatalogID,
		CatalogCodeITL,
		SubscribedCatalog_Language_RefID,
		SubscribedCatalog_Currency_RefID,
		SubscribedCatalog_Name,
		SubscribedCatalog_Description,
		SubscribedCatalog_CurrentRevision,
		PublishingSupplier_RefID,
		SubscribedBy_BusinessParticipant_RefID,
		SubscribedCatalog_PricelistRelease_RefID,
		SubscribedCatalog_ValidFrom,
		SubscribedCatalog_ValidThrough,
		IsCatalogValid,
		IsCatalogPublic,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@CMN_PRO_SubscribedCatalogID,
		@CatalogCodeITL,
		@SubscribedCatalog_Language_RefID,
		@SubscribedCatalog_Currency_RefID,
		@SubscribedCatalog_Name,
		@SubscribedCatalog_Description,
		@SubscribedCatalog_CurrentRevision,
		@PublishingSupplier_RefID,
		@SubscribedBy_BusinessParticipant_RefID,
		@SubscribedCatalog_PricelistRelease_RefID,
		@SubscribedCatalog_ValidFrom,
		@SubscribedCatalog_ValidThrough,
		@IsCatalogValid,
		@IsCatalogPublic,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)