INSERT INTO 
	cmn_bpt_emp_effectiveworktime_position_workscheduledetail
	(
		AssignmentID,
		CMN_STR_PPS_DailyWorkSchedule_Detail_RefID,
		CMN_BPT_EMP_EffectiveWorkTime_Position_RefID,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@AssignmentID,
		@CMN_STR_PPS_DailyWorkSchedule_Detail_RefID,
		@CMN_BPT_EMP_EffectiveWorkTime_Position_RefID,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)