INSERT INTO 
	cmn_per_personinfo_2_address
	(
		AssignmentID,
		AddressLabel,
		CMN_Address_RefID,
		CMN_PER_PersonInfo_RefID,
		SequenceNumber,
		IsPrimary,
		IsAddress_Contact,
		IsAddress_Billing,
		IsAddress_Shipping,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@AssignmentID,
		@AddressLabel,
		@CMN_Address_RefID,
		@CMN_PER_PersonInfo_RefID,
		@SequenceNumber,
		@IsPrimary,
		@IsAddress_Contact,
		@IsAddress_Billing,
		@IsAddress_Shipping,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)