INSERT INTO 
	cmn_bpt_emp_employee_absencereason_timeframestatistics
	(
		CMN_BPT_EMP_Employee_AbsenceReason_TimeframeStatisticsID,
		CalculationTimeframe_RefID,
		AbsenceReason_RefID,
		Employee_RefID,
		R_AbsenceCarryOver_InHours,
		R_AbsenceCarryOver_InDays,
		R_AbsenceTimeUsed_InHours,
		R_AbsenceTimeUsed_InDays,
		R_RequestReservedAbsence_InHours,
		R_RequestReservedAbsence_InDays,
		R_TotalAllowedAbsenceTime_InHours,
		R_TotalAllowedAbsenceTime_InDays,
		Creation_Timestamp,
		IsDeleted,
		Tenant_RefID
	)
VALUES 
	(
		@CMN_BPT_EMP_Employee_AbsenceReason_TimeframeStatisticsID,
		@CalculationTimeframe_RefID,
		@AbsenceReason_RefID,
		@Employee_RefID,
		@R_AbsenceCarryOver_InHours,
		@R_AbsenceCarryOver_InDays,
		@R_AbsenceTimeUsed_InHours,
		@R_AbsenceTimeUsed_InDays,
		@R_RequestReservedAbsence_InHours,
		@R_RequestReservedAbsence_InDays,
		@R_TotalAllowedAbsenceTime_InHours,
		@R_TotalAllowedAbsenceTime_InDays,
		@Creation_Timestamp,
		@IsDeleted,
		@Tenant_RefID
	)