INSERT INTO 
	usr_device_configurationcode_statushistory
	(
		USR_Device_ConfigurationCode_StatusHistoryID,
		Device_ConfigurationCode_RefID,
		WasUsed,
		WasUsedBy_UserDevice_RefID,
		WasDeactivated,
		WasDeactivatedBy_BusinessParticipant_RefID,
		WasDeleted,
		WasDeletedBy_BusinessParticipant_RefID,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@USR_Device_ConfigurationCode_StatusHistoryID,
		@Device_ConfigurationCode_RefID,
		@WasUsed,
		@WasUsedBy_UserDevice_RefID,
		@WasDeactivated,
		@WasDeactivatedBy_BusinessParticipant_RefID,
		@WasDeleted,
		@WasDeletedBy_BusinessParticipant_RefID,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)