INSERT INTO 
	imo_questionnaire_action_submissions
	(
		IMO_Questionnaire_Action_SubmissionID,
		Questionnaire_Action_RefID,
		Questionnaire_CustomAction_RefID,
		Questionnaire_Submission_RefID,
		Questionnaire_ActionTimeframe_RefID,
		Unit_Cost,
		Unit_Amount,
		Unit_TotalCost,
		Comment,
		Creation_Timestamp,
		IsDeleted,
		Tenant_RefID
	)
VALUES 
	(
		@IMO_Questionnaire_Action_SubmissionID,
		@Questionnaire_Action_RefID,
		@Questionnaire_CustomAction_RefID,
		@Questionnaire_Submission_RefID,
		@Questionnaire_ActionTimeframe_RefID,
		@Unit_Cost,
		@Unit_Amount,
		@Unit_TotalCost,
		@Comment,
		@Creation_Timestamp,
		@IsDeleted,
		@Tenant_RefID
	)