INSERT INTO 
	cmn_cal_events
	(
		CMN_CAL_EventID,
		CalendarInstance_RefID,
		Repetition_RefID,
		IsRepetitive,
		IsWholeDayEvent,
		StartTime,
		EndTime,
		R_EventDuration_sec,
		IsCalendarEvent_Editable,
		Creation_Timestamp,
		IsDeleted,
		Tenant_RefID
	)
VALUES 
	(
		@CMN_CAL_EventID,
		@CalendarInstance_RefID,
		@Repetition_RefID,
		@IsRepetitive,
		@IsWholeDayEvent,
		@StartTime,
		@EndTime,
		@R_EventDuration_sec,
		@IsCalendarEvent_Editable,
		@Creation_Timestamp,
		@IsDeleted,
		@Tenant_RefID
	)