INSERT INTO 
	ord_prc_procurementorder_headers
	(
		ORD_PRC_ProcurementOrder_HeaderID,
		SupplierCustomeOrderITL,
		Current_ProcurementOrderStatus_RefID,
		ProcurementOrder_Number,
		ProcurementOrder_Date,
		CreatedBy_BusinessParticipant_RefID,
		CanceledBy_BusinessParticipant_RefID,
		ProcurementOrder_Currency_RefID,
		ProcurementOrder_Supplier_RefID,
		TotalValue_BeforeTax,
		IsCreatedForExpectedDelivery,
		IsCreatedDueToReturnShipment,
		ApplicableSupplierPaymentCondition_RefID,
		BillingAddressUCD_RefID,
		ShippingAddressUCD_RefID,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@ORD_PRC_ProcurementOrder_HeaderID,
		@SupplierCustomeOrderITL,
		@Current_ProcurementOrderStatus_RefID,
		@ProcurementOrder_Number,
		@ProcurementOrder_Date,
		@CreatedBy_BusinessParticipant_RefID,
		@CanceledBy_BusinessParticipant_RefID,
		@ProcurementOrder_Currency_RefID,
		@ProcurementOrder_Supplier_RefID,
		@TotalValue_BeforeTax,
		@IsCreatedForExpectedDelivery,
		@IsCreatedDueToReturnShipment,
		@ApplicableSupplierPaymentCondition_RefID,
		@BillingAddressUCD_RefID,
		@ShippingAddressUCD_RefID,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)