INSERT INTO 
	hec_patient_parameters
	(
		HEC_Patient_ParameterID,
		PatientParameterITL,
		GlobalPropertyMatchingID,
		Parameter_Name_DictID,
		IsFloat,
		IfFloat_MinValue,
		IfFloat_MaxValue,
		IsFloat_ApplicableUnit_RefID,
		IsString,
		IsVitalParameter,
		HasHighRelevance,
		ParameterType_RefID,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@HEC_Patient_ParameterID,
		@PatientParameterITL,
		@GlobalPropertyMatchingID,
		@Parameter_Name,
		@IsFloat,
		@IfFloat_MinValue,
		@IfFloat_MaxValue,
		@IsFloat_ApplicableUnit_RefID,
		@IsString,
		@IsVitalParameter,
		@HasHighRelevance,
		@ParameterType_RefID,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)