INSERT INTO 
	cmn_cal_repetition_ranges
	(
		CMN_CAL_Repetition_RangeID,
		Repetition_RefID,
		StartDate,
		HasEndType_Occurrence,
		HasEndType_DateTime,
		HasEndType_NoEndDate,
		End_AfterSpecifiedOccurrences,
		End_ByDate,
		Creation_Timestamp,
		IsDeleted,
		Tenant_RefID
	)
VALUES 
	(
		@CMN_CAL_Repetition_RangeID,
		@Repetition_RefID,
		@StartDate,
		@HasEndType_Occurrence,
		@HasEndType_DateTime,
		@HasEndType_NoEndDate,
		@End_AfterSpecifiedOccurrences,
		@End_ByDate,
		@Creation_Timestamp,
		@IsDeleted,
		@Tenant_RefID
	)