UPDATE 
	ord_prc_spb_supplierbill_position_2_procurementorderposition
SET 
	ORD_PRC_SPB_SupplierBill_Position_RefID=@ORD_PRC_SPB_SupplierBill_Position_RefID,
	ORD_PRC_ProcurementOrder_Position_RefID=@ORD_PRC_ProcurementOrder_Position_RefID,
	Creation_Timestamp=@Creation_Timestamp,
	Tenant_RefID=@Tenant_RefID,
	IsDeleted=@IsDeleted
WHERE 
	AssignmentID = @AssignmentID