INSERT INTO 
	hec_cmt_opt_community_potentialprocedurecatalogs
	(
		HEC_CMT_OPT_Community_PotentialProcedureCatalogID,
		Community_RefID,
		Version_Internal,
		Version_Display,
		PublishDate,
		PublicDownloadURL,
		HEC_TRE_PotentialProcedure_Catalog_RefID,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@HEC_CMT_OPT_Community_PotentialProcedureCatalogID,
		@Community_RefID,
		@Version_Internal,
		@Version_Display,
		@PublishDate,
		@PublicDownloadURL,
		@HEC_TRE_PotentialProcedure_Catalog_RefID,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)