INSERT INTO 
	hec_act_performedaction_medicationupdates
	(
		HEC_ACT_PerformedAction_MedicationUpdateID,
		HEC_ACT_PerformedAction_RefID,
		HEC_Patient_Medication_RefID,
		Relevant_PatientDiagnosis_RefID,
		IsMedicationCreated,
		IsMedicationModified,
		IsMedicationDeactivated,
		IsHealthcareProduct,
		HEC_Product_RefID,
		IsSubstance,
		IfSubstance_Strength,
		IfSubstance_Unit_RefID,
		IfSubstance_Substance_RefiD,
		DosageText,
		IntendedApplicationDuration_in_days,
		MedicationUpdateComment,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@HEC_ACT_PerformedAction_MedicationUpdateID,
		@HEC_ACT_PerformedAction_RefID,
		@HEC_Patient_Medication_RefID,
		@Relevant_PatientDiagnosis_RefID,
		@IsMedicationCreated,
		@IsMedicationModified,
		@IsMedicationDeactivated,
		@IsHealthcareProduct,
		@HEC_Product_RefID,
		@IsSubstance,
		@IfSubstance_Strength,
		@IfSubstance_Unit_RefID,
		@IfSubstance_Substance_RefiD,
		@DosageText,
		@IntendedApplicationDuration_in_days,
		@MedicationUpdateComment,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)