INSERT INTO 
	cmn_com_companyinfo_addresses
	(
		CMN_COM_CompanyInfo_AddressID,
		CompanyInfo_RefID,
		IsDefault,
		IsBilling,
		IsShipping,
		IsContact,
		Address_Description,
		Address_UCD_RefID,
		Creation_Timestamp,
		IsDeleted,
		Tenant_RefID
	)
VALUES 
	(
		@CMN_COM_CompanyInfo_AddressID,
		@CompanyInfo_RefID,
		@IsDefault,
		@IsBilling,
		@IsShipping,
		@IsContact,
		@Address_Description,
		@Address_UCD_RefID,
		@Creation_Timestamp,
		@IsDeleted,
		@Tenant_RefID
	)