INSERT INTO 
	cmn_tenants
	(
		CMN_TenantID,
		TenantITL,
		UniversalContactDetail_RefID,
		CMN_CAL_CalendarInstance_RefID,
		IsUsing_Offices,
		IsUsing_WorkAreas,
		IsUsing_Workplaces,
		IsUsing_CostCenters,
		CMN_BPT_STA_SettingProfile_RefID,
		DocumentServerRootURL,
		Customers_DefaultPricelist_RefID,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@CMN_TenantID,
		@TenantITL,
		@UniversalContactDetail_RefID,
		@CMN_CAL_CalendarInstance_RefID,
		@IsUsing_Offices,
		@IsUsing_WorkAreas,
		@IsUsing_Workplaces,
		@IsUsing_CostCenters,
		@CMN_BPT_STA_SettingProfile_RefID,
		@DocumentServerRootURL,
		@Customers_DefaultPricelist_RefID,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)