INSERT INTO 
	res_dud_revisions
	(
		RES_DUD_RevisionID,
		RevisionGroup_RefID,
		RES_BLD_Building_RefID,
		QuestionnaireVersion_RefID,
		Revision_Comment,
		Revision_Title,
		ScopeOfInspectionIncludes_Internal,
		ScopeOfInspectionIncludes_External,
		Creation_Timestamp,
		IsDeleted,
		Tenant_RefID
	)
VALUES 
	(
		@RES_DUD_RevisionID,
		@RevisionGroup_RefID,
		@RES_BLD_Building_RefID,
		@QuestionnaireVersion_RefID,
		@Revision_Comment,
		@Revision_Title,
		@ScopeOfInspectionIncludes_Internal,
		@ScopeOfInspectionIncludes_External,
		@Creation_Timestamp,
		@IsDeleted,
		@Tenant_RefID
	)