INSERT INTO 
	hec_medicalpractises
	(
		HEC_MedicalPractiseID,
		WeeklyOfficeHours_Template_RefID,
		Ext_CompanyInfo_RefID,
		AssociatedWith_PhysitianAssociation_RefID,
		ContactPerson_RefID,
		WeeklySurgeryHours_Template_RefID,
		Contact_EmergencyPhoneNumber,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		IsHospital,
		Modification_Timestamp
	)
VALUES 
	(
		@HEC_MedicalPractiseID,
		@WeeklyOfficeHours_Template_RefID,
		@Ext_CompanyInfo_RefID,
		@AssociatedWith_PhysitianAssociation_RefID,
		@ContactPerson_RefID,
		@WeeklySurgeryHours_Template_RefID,
		@Contact_EmergencyPhoneNumber,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@IsHospital,
		@Modification_Timestamp
	)