INSERT INTO 
	hec_patients
	(
		HEC_PatientID,
		CMN_BPT_BusinessParticipant_RefID,
		HasSignedParticipationPolicyDocument,
		PatientComment,
		IsPatientParticipationPolicyValidated,
		PatientParticipationPolicyValidatedBy_Account_RefID,
		EmployerCompanyName,
		PatientProfession,
		IsTenant,
		Current_EMRFile_ExternalURL,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@HEC_PatientID,
		@CMN_BPT_BusinessParticipant_RefID,
		@HasSignedParticipationPolicyDocument,
		@PatientComment,
		@IsPatientParticipationPolicyValidated,
		@PatientParticipationPolicyValidatedBy_Account_RefID,
		@EmployerCompanyName,
		@PatientProfession,
		@IsTenant,
		@Current_EMRFile_ExternalURL,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)