INSERT INTO 
	cmn_ctr_contract_defaultparameters
	(
		CMN_CTR_Contract_DefaultParameterID,
		GlobalPropertyMatchingID,
		Contract_RefID,
		ParameterName,
		IsStringValue,
		IfStringValue_DefaultValue,
		IsNumericValue,
		IfNumericValue_DefaultValue,
		IsBooleanValue,
		IfBooleanValue_DefaultValue,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@CMN_CTR_Contract_DefaultParameterID,
		@GlobalPropertyMatchingID,
		@Contract_RefID,
		@ParameterName,
		@IsStringValue,
		@IfStringValue_DefaultValue,
		@IsNumericValue,
		@IfNumericValue_DefaultValue,
		@IsBooleanValue,
		@IfBooleanValue_DefaultValue,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)