INSERT INTO 
	hec_cmt_opt_uploadedmedications
	(
		HEC_CMT_OPT_UploadedMedicationID,
		UploadedBy_Member_RefID,
		IsProduct,
		IfProduct_UploadedProductITL,
		IsSubstance,
		IfSubstance_Unit_ISOCode,
		IfSubstance_UploadedSubstanceITL,
		IfSubstance_Strength,
		DosageText,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@HEC_CMT_OPT_UploadedMedicationID,
		@UploadedBy_Member_RefID,
		@IsProduct,
		@IfProduct_UploadedProductITL,
		@IsSubstance,
		@IfSubstance_Unit_ISOCode,
		@IfSubstance_UploadedSubstanceITL,
		@IfSubstance_Strength,
		@DosageText,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)