INSERT INTO 
	hec_patient_medications
	(
		HEC_Patient_MedicationID,
		Patient_RefID,
		R_IsActive,
		R_ActiveUntill,
		R_DateOfAdding,
		R_DateOfRemoval,
		R_IsHealthcareProduct,
		R_HEC_Product_RefID,
		R_IsSubstance,
		R_IfSubstance_Strength,
		R_IfSubstance_Unit_RefID,
		R_IfSubstance_Substance_RefiD,
		R_DosageText,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@HEC_Patient_MedicationID,
		@Patient_RefID,
		@R_IsActive,
		@R_ActiveUntill,
		@R_DateOfAdding,
		@R_DateOfRemoval,
		@R_IsHealthcareProduct,
		@R_HEC_Product_RefID,
		@R_IsSubstance,
		@R_IfSubstance_Strength,
		@R_IfSubstance_Unit_RefID,
		@R_IfSubstance_Substance_RefiD,
		@R_DosageText,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)