INSERT INTO 
	ord_cuo_customerorder_notes
	(
		ORD_CUO_CustomerOrder_NoteID,
		CustomerOrder_Header_RefID,
		CustomerOrder_Position_RefID,
		CMN_BPT_CTM_OrganizationalUnit_RefID,
		CreatedBy_BusinessParticipant_RefID,
		Title,
		Comment,
		NotePublishDate,
		SequenceOrderNumber,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@ORD_CUO_CustomerOrder_NoteID,
		@CustomerOrder_Header_RefID,
		@CustomerOrder_Position_RefID,
		@CMN_BPT_CTM_OrganizationalUnit_RefID,
		@CreatedBy_BusinessParticipant_RefID,
		@Title,
		@Comment,
		@NotePublishDate,
		@SequenceOrderNumber,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)