INSERT INTO 
	app_initializations
	(
		APP_InitializationID,
		Application_RefID,
		Module_RefID,
		Version,
		Initialization_StartedAtDate,
		Initialiaztion_CompletedAtDate,
		IsInitializationComplete,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@APP_InitializationID,
		@Application_RefID,
		@Module_RefID,
		@Version,
		@Initialization_StartedAtDate,
		@Initialiaztion_CompletedAtDate,
		@IsInitializationComplete,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)