INSERT INTO 
	cmn_pro_product_customerinquiries
	(
		CMN_PRO_Product_CustomerInquiryID,
		Product_RefID,
		Product_Variant_RefID,
		Product_Release_RefID,
		InquiredQuantity,
		DateOfInquiry,
		InquiringCustomer_RefID,
		IsFulfillable,
		IsFulfilled,
		IsFulfilled_CustomerOrderHeader_RefID,
		NotFulfilled_Reason,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@CMN_PRO_Product_CustomerInquiryID,
		@Product_RefID,
		@Product_Variant_RefID,
		@Product_Release_RefID,
		@InquiredQuantity,
		@DateOfInquiry,
		@InquiringCustomer_RefID,
		@IsFulfillable,
		@IsFulfilled,
		@IsFulfilled_CustomerOrderHeader_RefID,
		@NotFulfilled_Reason,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)