INSERT INTO 
	ord_cuo_rfp_requestforproposal_history
	(
		ORD_CUO_RFP_RequestForProposal_HistoryID,
		RequestForProposal_Header_RefID,
		IsEvent_ProposalRequest_Received,
		IsEvent_ProposalRequest_ReceptionAcknowledged,
		IsEvent_ProposalRequest_Declined,
		IsEvent_ByCustomer_ProposalRequest_Revoked,
		IsEvent_ProposalResponse_Sent,
		IsEvent_ProposalResponse_Revoked,
		IsEvent_ByCustomer_ProposalResponse_ReceptionAcknowledged,
		IsEvent_ByCustomer_ProposalResponse_Declined,
		IsEvent_ByCustomer_ProposalResponse_Accepted,
		IsEvent_ByCustomer_ProposalResponse_ModificationRequired,
		Comment,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@ORD_CUO_RFP_RequestForProposal_HistoryID,
		@RequestForProposal_Header_RefID,
		@IsEvent_ProposalRequest_Received,
		@IsEvent_ProposalRequest_ReceptionAcknowledged,
		@IsEvent_ProposalRequest_Declined,
		@IsEvent_ByCustomer_ProposalRequest_Revoked,
		@IsEvent_ProposalResponse_Sent,
		@IsEvent_ProposalResponse_Revoked,
		@IsEvent_ByCustomer_ProposalResponse_ReceptionAcknowledged,
		@IsEvent_ByCustomer_ProposalResponse_Declined,
		@IsEvent_ByCustomer_ProposalResponse_Accepted,
		@IsEvent_ByCustomer_ProposalResponse_ModificationRequired,
		@Comment,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)