
require.config({

    baseUrl: "scripts",

    // alias libraries paths
    paths: {
        'application-configuration': 'src/common/application-configuration',
        'angular': 'vendor/angular',
        'angular-route': 'vendor/angular-route',
        'angularAMD': 'vendor/angularAMD',
        'ngload': 'vendor/ngload',
        'ajaxService': 'src/common/services/ajaxServices',
        'patientService': 'src/app/patient/services/patientService',
        'angular-datepicker': 'vendor/angular-datepicker',
        'angular-translate': 'vendor/angular-translate',
        'ngDatefilter': 'src/common/directives/ngDatefilter',
        'addDoctorDirective': 'src/app/doctor/directives/addDoctorDirective',
        'addPracticeDirective': 'src/app/doctor/directives/addPracticeDirective',
        'addContractDirective': 'src/app/doctor/directives/addContractDirective',
        'globalSearchDirective': 'src/common/directives/globalSearchDirective',
        'doctorService': 'src/app/doctor/services/doctorService',
        'doctorController': 'src/app/doctor/controllers/doctorController',
        'globalResources': 'src/resource_files/global/globalResources',
        'dashboardPageResources': 'src/resource_files/pages/dashboardPageResources',
        'doctorPageResources': 'src/resource_files/pages/doctorPageResources',
        'offClick': 'vendor/offClick',
        'ngDialog': 'vendor/ngDialog',
        'validationService': 'src/common/services/validationService',
        'alertsServices': 'src/common/services/alertsServices',
        'blockUI': 'vendor/angular-block-ui',
        'ngAnimate': 'vendor/angular-animate',
        'angucomplete': 'vendor/angucomplete-alt',
        'changePassController': 'src/common/controllers/changePassController',
        'commonServices': 'src/common/services/commonServices',
        'ngFileUpload': 'vendor/ng-file-upload',
        'dropdownList': 'src/common/directives/dropdownListDirective',
        'orderPageResources': 'src/resource_files/pages/orderPageResources',
        'treatmentPageResources': 'src/resource_files/pages/treatmentPageResources',
        'orderService': 'src/app/order/services/orderService',
        'treatmentService': 'src/app/treatment/services/treatmentService',
        'groupBy': 'vendor/groupBy',
        'dashboardService': 'src/app/dashboard/services/dashboardService',
        'archiveService': 'src/app/archive/services/archiveService',
        'settingsService': 'src/app/settings/services/settingsService',
        'addUserDirective': 'src/app/settings/directives/addUserDirective',
        //custom directives
        'infiniteScroll': 'src/common/directives/directive.infinitive.scroll',
        'sticky': 'src/common/directives/sticky',
        'patientController': '/src/app/patient/controllers/patientController',
        'patientService': 'src/app/patient/services/patientService',
        'patientPageResources': 'src/resource_files/pages/patientPageResources',
        'patientDetailViewController': '/src/app/patient/controllers/patientDetailViewController',
        'medicationService': 'src/app/master_data/services/medicationService',
        'contractService': 'src/app/master_data/services/contractService',
        'addMedicationDirective': 'src/app/master_data/directives/addMedicationDirective',
        'medicationPageResources': 'src/resource_files/pages/medicationPageResources',
        'gposDetailDirective': 'src/app/master_data/directives/gposDetailDirective',
        'coveredDrugsDirective': 'src/app/master_data/directives/coveredDrugsDirective',
        'coveredDiagnosesDirective': 'src/app/master_data/directives/coveredDiagnosesDirective',
        'coveredHipsDirective': 'src/app/master_data/directives/coveredHipsDirective',
        'participatingDoctorsDirective': 'src/app/master_data/directives/participatingDoctorsDirective',
        'dueDatesOverviewDirective': 'src/app/master_data/directives/dueDatesOverviewDirective',
        'addGposDirective': 'src/app/master_data/directives/addGposDirective',
        'elipsisDirective': 'src/common/directives/elipsisDirective',
        'ng-tags-input': 'vendor/ng-tags-input',
        'pharmacyService': 'src/app/master_data/services/pharmacyService',
        'addPharmacyDirective': 'src/app/master_data/directives/addPharmacyDirective',
        'timeInput': 'vendor/timeInput',
    },

    waitSeconds: 15,
    urlArgs: "v2.3.44",

    // Add angular modules that does not support AMD out of the box, put it in a  shim
    shim: {
        'angular': ['jquery'],
        'angularAMD': ['angular'],
        'angular-route': ['angular'],
        'angular-translate': ['angular'],
        'blockUI': ['angular'],
        'ngAnimate': ['angular'],
        'timeInput': ['angular'],
        'infiniteScroll': ['angular']
    },

    // kick start application
    deps: ['application-configuration']
});
