INSERT INTO 
	cmn_pro_mastercatalog_product_2_productgroup
	(
		AssignmentID,
		CMN_PRO_MasterCatalog_Product_RefID,
		CMN_PRO_MasterCatalog_ProductGroup_RefID,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@AssignmentID,
		@CMN_PRO_MasterCatalog_Product_RefID,
		@CMN_PRO_MasterCatalog_ProductGroup_RefID,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)