INSERT INTO 
	cmn_bpt_emp_contractabsenceadjustments
	(
		CMN_BPT_EMP_ContractAbsenceAdjustmentID,
		EmploymentRelationship_Timeframe_RefID,
		AbsenceReason_RefID,
		ContractAbsenceAdjustment_Group_RefID,
		AbsenceTime_InMinutes,
		AdjustmentComment,
		TriggeringAccount_RefID,
		IsManual,
		InternalAdjustmentType,
		AdjustmentDate,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@CMN_BPT_EMP_ContractAbsenceAdjustmentID,
		@EmploymentRelationship_Timeframe_RefID,
		@AbsenceReason_RefID,
		@ContractAbsenceAdjustment_Group_RefID,
		@AbsenceTime_InMinutes,
		@AdjustmentComment,
		@TriggeringAccount_RefID,
		@IsManual,
		@InternalAdjustmentType,
		@AdjustmentDate,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)