INSERT INTO 
	cmn_bpt_emp_extraworkcalculations
	(
		CMN_BPT_EMP_ExtraWorkCalculationID,
		GlobalPropertyMatchingID,
		ExtraWorkCalculation_Name_DictID,
		IsCalculatingOvertimeEnabled,
		AreAdditionalWorkDays_CalculatedIn_Hours,
		AreAdditionalWorkDays_CalculatedIn_DaysAsHours,
		AreAdditionalWorkDays_CalculatedIn_Days,
		StandardWorkDay_in_mins,
		IsDisplayedAs_HoursAsDays,
		IsDisplayedAs_DaysAndHours,
		MinimalOvertimeTreshold_in_minutes,
		Creation_Timestamp,
		IsDeleted,
		Tenant_RefID
	)
VALUES 
	(
		@CMN_BPT_EMP_ExtraWorkCalculationID,
		@GlobalPropertyMatchingID,
		@ExtraWorkCalculation_Name,
		@IsCalculatingOvertimeEnabled,
		@AreAdditionalWorkDays_CalculatedIn_Hours,
		@AreAdditionalWorkDays_CalculatedIn_DaysAsHours,
		@AreAdditionalWorkDays_CalculatedIn_Days,
		@StandardWorkDay_in_mins,
		@IsDisplayedAs_HoursAsDays,
		@IsDisplayedAs_DaysAndHours,
		@MinimalOvertimeTreshold_in_minutes,
		@Creation_Timestamp,
		@IsDeleted,
		@Tenant_RefID
	)