INSERT INTO 
	imo_questionnaire_actiontimeframegroups
	(
		IMO_Questionnaire_ActionTimeframeGroupID,
		Label_DictID,
		CopyOf_PreviouslyPublishedVersion_RefID,
		Creation_Timestamp,
		IsDeleted,
		Tenant_RefID
	)
VALUES 
	(
		@IMO_Questionnaire_ActionTimeframeGroupID,
		@Label,
		@CopyOf_PreviouslyPublishedVersion_RefID,
		@Creation_Timestamp,
		@IsDeleted,
		@Tenant_RefID
	)