UPDATE 
	cmn_str_pps_workplace_activity_professionassignments
SET 
	CMN_STR_Profession_RefID=@CMN_STR_Profession_RefID,
	Workplace_Activity_RefID=@Workplace_Activity_RefID,
	Creation_Timestamp=@Creation_Timestamp,
	IsDeleted=@IsDeleted,
	Tenant_RefID=@Tenant_RefID
WHERE 
	CMN_STR_PPS_Workplace_Activity_ProfessionAssignmentID = @CMN_STR_PPS_Workplace_Activity_ProfessionAssignmentID