INSERT INTO 
	cmn_bpt_emp_workplaceassignments_workpatterns
	(
		CMN_BPT_EMP_WorkplaceAssignments_WorkPatternID,
		IsWeek_Even,
		IsWeek_Odd,
		BoundTo_WorkplaceAssignment_RefID,
		CMN_PPS_ShiftTemplate_RefID,
		CMN_BPT_STA_AbsenceReason_RefID,
		IsMonday,
		IsTuesday,
		IsWednesday,
		IsThursday,
		IsFriday,
		IsSaturday,
		IsSunday,
		Creation_Timestamp,
		IsDeleted,
		Tenant_RefID
	)
VALUES 
	(
		@CMN_BPT_EMP_WorkplaceAssignments_WorkPatternID,
		@IsWeek_Even,
		@IsWeek_Odd,
		@BoundTo_WorkplaceAssignment_RefID,
		@CMN_PPS_ShiftTemplate_RefID,
		@CMN_BPT_STA_AbsenceReason_RefID,
		@IsMonday,
		@IsTuesday,
		@IsWednesday,
		@IsThursday,
		@IsFriday,
		@IsSaturday,
		@IsSunday,
		@Creation_Timestamp,
		@IsDeleted,
		@Tenant_RefID
	)