INSERT INTO 
	hec_prc_procurementorder_positions
	(
		HEC_PRC_ProcurementOrder_PositionID,
		Ext_ORD_PRC_ProcurementOrder_Position_RefID,
		Clearing_Doctor_RefID,
		ClearingDoctor_DisplayName,
		OrderedFor_Patient_RefID,
		OrderedForPatient_DisplayName,
		OrderedFor_Doctor_RefID,
		OrderedForDoctor_DisplayName,
		IsOrderForPatient_PatientFeeWaived,
		IfProFormaOrderPosition_PrintLabelOnly,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@HEC_PRC_ProcurementOrder_PositionID,
		@Ext_ORD_PRC_ProcurementOrder_Position_RefID,
		@Clearing_Doctor_RefID,
		@ClearingDoctor_DisplayName,
		@OrderedFor_Patient_RefID,
		@OrderedForPatient_DisplayName,
		@OrderedFor_Doctor_RefID,
		@OrderedForDoctor_DisplayName,
		@IsOrderForPatient_PatientFeeWaived,
		@IfProFormaOrderPosition_PrintLabelOnly,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)