INSERT INTO 
	hec_pat_ki67_specimenanalysis
	(
		HEC_PAT_Ki67_SpecimenAnalysisID,
		Analysis_Name,
		AnalysisPersistedBy_Account_RefID,
		Specimen_RefID,
		AnalysisResults,
		CellMap_Document_RefID,
		MarkupNoFill_Document_RefID,
		MarkupFill_Document_RefID,
		IsReportCreated,
		IfReportCreated_Report_Document_RefID,
		Creation_Timestamp,
		IsDeleted,
		Tenant_RefID
	)
VALUES 
	(
		@HEC_PAT_Ki67_SpecimenAnalysisID,
		@Analysis_Name,
		@AnalysisPersistedBy_Account_RefID,
		@Specimen_RefID,
		@AnalysisResults,
		@CellMap_Document_RefID,
		@MarkupNoFill_Document_RefID,
		@MarkupFill_Document_RefID,
		@IsReportCreated,
		@IfReportCreated_Report_Document_RefID,
		@Creation_Timestamp,
		@IsDeleted,
		@Tenant_RefID
	)