INSERT INTO 
	cmn_str_pps_dailyworkschedule_details
	(
		CMN_STR_PPS_DailyWorkSchedule_DetailID,
		InstantiatedWithShiftTemplate_RefID,
		CMN_CAL_Event_RefID,
		DailyWorkSchedule_RefID,
		AbsenceReason_RefID,
		SheduleForWorkplace_RefID,
		IsWorkBreak,
		CMN_BPT_EMP_Employee_LeaveRequest_RefID,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@CMN_STR_PPS_DailyWorkSchedule_DetailID,
		@InstantiatedWithShiftTemplate_RefID,
		@CMN_CAL_Event_RefID,
		@DailyWorkSchedule_RefID,
		@AbsenceReason_RefID,
		@SheduleForWorkplace_RefID,
		@IsWorkBreak,
		@CMN_BPT_EMP_Employee_LeaveRequest_RefID,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)