INSERT INTO 
	hec_pro_component_substanceingredients
	(
		HEC_PRO_Component_SubstanceIngredientID,
		Component_RefID,
		Substance_RefID,
		Unit_RefID,
		QuantityValue,
		Suffix,
		SubstanceIngredientTypeStatus,
		SequenceNumber,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@HEC_PRO_Component_SubstanceIngredientID,
		@Component_RefID,
		@Substance_RefID,
		@Unit_RefID,
		@QuantityValue,
		@Suffix,
		@SubstanceIngredientTypeStatus,
		@SequenceNumber,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)