INSERT INTO 
	cmn_bpt_supplier_defaultdeliverytimes
	(
		CMN_BPT_Supplier_DefaultDeliveryTimeID,
		Supplier_RefID,
		CRONExpression,
		Specified_Product_Group_RefID,
		Specified_Product_RefID,
		Specified_Product_Variant_RefID,
		Specified_Product_Release_RefID,
		TimeToDelivery_in_min,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@CMN_BPT_Supplier_DefaultDeliveryTimeID,
		@Supplier_RefID,
		@CRONExpression,
		@Specified_Product_Group_RefID,
		@Specified_Product_RefID,
		@Specified_Product_Variant_RefID,
		@Specified_Product_Release_RefID,
		@TimeToDelivery_in_min,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)