INSERT INTO 
	usr_accounts
	(
		USR_AccountID,
		DefaultLanguage_RefID,
		AccountType,
		Username,
		BusinessParticipant_RefID,
		RemoveViewedNotificationAfterDays,
		AccountSignInEmailAddress,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@USR_AccountID,
		@DefaultLanguage_RefID,
		@AccountType,
		@Username,
		@BusinessParticipant_RefID,
		@RemoveViewedNotificationAfterDays,
		@AccountSignInEmailAddress,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)