INSERT INTO 
	ord_cuo_customerorder_headers
	(
		ORD_CUO_CustomerOrder_HeaderID,
		ProcurementOrderITL,
		Current_CustomerOrderStatus_RefID,
		CustomerOrder_Number,
		CustomerOrder_Date,
		OrderingCustomer_BusinessParticipant_RefID,
		CreatedBy_BusinessParticipant_RefID,
		CanceledBy_BusinessParticipant_RefID,
		CustomerOrder_Currency_RefID,
		TotalValue_BeforeTax,
		IsCustomerOrderFinalized,
		DeliveryDeadline,
		IsPartialShippingAllowed,
		BillingAddressUCD_RefID,
		ShippingAddressUCD_RefID,
		DeliveryRequestedFrom_Warehouse_RefID,
		CreatedAt_PointOfSale_RefID,
		WasAutoApprovedUponReceipt,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@ORD_CUO_CustomerOrder_HeaderID,
		@ProcurementOrderITL,
		@Current_CustomerOrderStatus_RefID,
		@CustomerOrder_Number,
		@CustomerOrder_Date,
		@OrderingCustomer_BusinessParticipant_RefID,
		@CreatedBy_BusinessParticipant_RefID,
		@CanceledBy_BusinessParticipant_RefID,
		@CustomerOrder_Currency_RefID,
		@TotalValue_BeforeTax,
		@IsCustomerOrderFinalized,
		@DeliveryDeadline,
		@IsPartialShippingAllowed,
		@BillingAddressUCD_RefID,
		@ShippingAddressUCD_RefID,
		@DeliveryRequestedFrom_Warehouse_RefID,
		@CreatedAt_PointOfSale_RefID,
		@WasAutoApprovedUponReceipt,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)