INSERT INTO 
	cmn_countries
	(
		CMN_CountryID,
		Default_Language_RefID,
		Default_Currency_RefID,
		Country_Name_DictID,
		Country_ISOCode_Alpha2,
		Country_ISOCode_Alpha3,
		Country_ISOCode_Numeric,
		IsActive,
		IsDefault,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@CMN_CountryID,
		@Default_Language_RefID,
		@Default_Currency_RefID,
		@Country_Name,
		@Country_ISOCode_Alpha2,
		@Country_ISOCode_Alpha3,
		@Country_ISOCode_Numeric,
		@IsActive,
		@IsDefault,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)