INSERT INTO 
	hec_act_plannedactions
	(
		HEC_ACT_PlannedActionID,
		HealthcarePlannedActionITL,
		Patient_RefID,
		Appointment_RefID,
		PlannedFor_Date,
		IsPerformed,
		IfPerformed_PerformedAction_RefID,
		IsToBePerformedExternally,
		MedicalPractice_RefID,
		MedicalPracticeType_RefID,
		ToBePerformedBy_BusinessParticipant_RefID,
		IsPlannedFollowup,
		IfPlannedFollowup_PreviousAction_RefID,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@HEC_ACT_PlannedActionID,
		@HealthcarePlannedActionITL,
		@Patient_RefID,
		@Appointment_RefID,
		@PlannedFor_Date,
		@IsPerformed,
		@IfPerformed_PerformedAction_RefID,
		@IsToBePerformedExternally,
		@MedicalPractice_RefID,
		@MedicalPracticeType_RefID,
		@ToBePerformedBy_BusinessParticipant_RefID,
		@IsPlannedFollowup,
		@IfPlannedFollowup_PreviousAction_RefID,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)