INSERT INTO 
	ord_prc_expecteddelivery_headers
	(
		ORD_PRC_ExpectedDelivery_HeaderID,
		ExpectedDeliveryHeaderITL,
		ExpectedDeliveryDate,
		ExpectedDeliveryNumber,
		LOG_WRH_Warehouse_RefID,
		IsDeliveryOpen,
		IsDeliveryClosed,
		IsDeliveryManuallyCreated,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@ORD_PRC_ExpectedDelivery_HeaderID,
		@ExpectedDeliveryHeaderITL,
		@ExpectedDeliveryDate,
		@ExpectedDeliveryNumber,
		@LOG_WRH_Warehouse_RefID,
		@IsDeliveryOpen,
		@IsDeliveryClosed,
		@IsDeliveryManuallyCreated,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)