INSERT INTO 
	ord_cuo_rfp_issuedproposalresponse_positions
	(
		ORD_CUO_RFP_IssuedProposalResponse_PositionID,
		ProposalResponsePositionITPL,
		IssuedProposalResponseHeader_RefID,
		CMN_PRO_Product_RefID,
		CMN_PRO_Product_Variant_RefID,
		CMN_PRO_Product_Release_RefID,
		CreatedFrom_RequestForProposal_Position_RefID,
		Quantity,
		TotalPrice_WithoutTax,
		TotalPrice_IncludingTax,
		PricePerUnit_WithoutTax,
		PricePerUnit_IncludingTax,
		IsReplacementProduct,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@ORD_CUO_RFP_IssuedProposalResponse_PositionID,
		@ProposalResponsePositionITPL,
		@IssuedProposalResponseHeader_RefID,
		@CMN_PRO_Product_RefID,
		@CMN_PRO_Product_Variant_RefID,
		@CMN_PRO_Product_Release_RefID,
		@CreatedFrom_RequestForProposal_Position_RefID,
		@Quantity,
		@TotalPrice_WithoutTax,
		@TotalPrice_IncludingTax,
		@PricePerUnit_WithoutTax,
		@PricePerUnit_IncludingTax,
		@IsReplacementProduct,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)