INSERT INTO 
	hec_act_performedaction_referrals
	(
		HEC_ACT_PerformedAction_ReferralID,
		HEC_ACT_PerformedAction_RefID,
		IsReferral_ForFollowup,
		ReferralTo_MedicalPracticeType_RefID,
		ReferralTo_MedicalPractice_RefID,
		ReferralTo_BusinessParticipant_RefID,
		PatientEffectivelyWentTo_MedicalPractice_RefID,
		ReferralComment,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@HEC_ACT_PerformedAction_ReferralID,
		@HEC_ACT_PerformedAction_RefID,
		@IsReferral_ForFollowup,
		@ReferralTo_MedicalPracticeType_RefID,
		@ReferralTo_MedicalPractice_RefID,
		@ReferralTo_BusinessParticipant_RefID,
		@PatientEffectivelyWentTo_MedicalPractice_RefID,
		@ReferralComment,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)