INSERT INTO 
	imo_questionnaire_customactions
	(
		IMO_Questionnaire_CustomActionID,
		Questionnaire_Status_RefID,
		Default_Timeframe_RefID,
		Unit_RefID,
		Creator_Account_RefID,
		Label_DictID,
		Unit_Cost,
		IsAuthorized,
		IsPrivate,
		Creation_Timestamp,
		IsDeleted,
		Tenant_RefID
	)
VALUES 
	(
		@IMO_Questionnaire_CustomActionID,
		@Questionnaire_Status_RefID,
		@Default_Timeframe_RefID,
		@Unit_RefID,
		@Creator_Account_RefID,
		@Label,
		@Unit_Cost,
		@IsAuthorized,
		@IsPrivate,
		@Creation_Timestamp,
		@IsDeleted,
		@Tenant_RefID
	)