INSERT INTO 
	cmn_bpt_ctm_catalogproductextensionrequests
	(
		CMN_BPT_CTM_CatalogProductExtensionRequestID,
		CatalogProductExtensionRequestITL,
		RequestedBy_Customer_BusinessParticipant_RefID,
		RequestedBy_Person_BusinessParticipant_RefID,
		RequestedFor_Catalog_RefID,
		Request_Question,
		Request_Answer,
		RequestCaseIdentifier,
		IsAnswerSent,
		IfAnswerSent_By_BusinessParticipant_RefID,
		IfAnswerSent_Date,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@CMN_BPT_CTM_CatalogProductExtensionRequestID,
		@CatalogProductExtensionRequestITL,
		@RequestedBy_Customer_BusinessParticipant_RefID,
		@RequestedBy_Person_BusinessParticipant_RefID,
		@RequestedFor_Catalog_RefID,
		@Request_Question,
		@Request_Answer,
		@RequestCaseIdentifier,
		@IsAnswerSent,
		@IfAnswerSent_By_BusinessParticipant_RefID,
		@IfAnswerSent_Date,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)