INSERT INTO 
	cmn_bpt_emp_employee_workplaceassignments
	(
		CMN_BPT_EMP_Employee_WorkplaceAssignment,
		CMN_BPT_EMP_Employee_RefID,
		CMN_BPT_EMP_Employee_PlanGroup_RefID,
		BoundTo_Workplace_RefID,
		Default_BreakTime_Template_RefID,
		SequenceNumber,
		WorkplaceAssignment_StartDate,
		WorkplaceAssignment_EndDate,
		IsBreakTimeCalculated_Planning,
		IsBreakTimeCalculated_Actual,
		Creation_Timestamp,
		IsDeleted,
		Tenant_RefID
	)
VALUES 
	(
		@CMN_BPT_EMP_Employee_WorkplaceAssignment,
		@CMN_BPT_EMP_Employee_RefID,
		@CMN_BPT_EMP_Employee_PlanGroup_RefID,
		@BoundTo_Workplace_RefID,
		@Default_BreakTime_Template_RefID,
		@SequenceNumber,
		@WorkplaceAssignment_StartDate,
		@WorkplaceAssignment_EndDate,
		@IsBreakTimeCalculated_Planning,
		@IsBreakTimeCalculated_Actual,
		@Creation_Timestamp,
		@IsDeleted,
		@Tenant_RefID
	)