INSERT INTO 
	usr_devices
	(
		USR_DeviceID,
		DeviceName,
		MACAddress,
		IMEI,
		SerialNumber,
		SecurityVerificationToken,
		DeviceSecurityCode,
		ExclusivelyUsableWith_Account_RefID,
		IsBanned,
		DeviceVendor,
		DeviceOperatingSystem,
		DeviceOperatingSystem_Version,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@USR_DeviceID,
		@DeviceName,
		@MACAddress,
		@IMEI,
		@SerialNumber,
		@SecurityVerificationToken,
		@DeviceSecurityCode,
		@ExclusivelyUsableWith_Account_RefID,
		@IsBanned,
		@DeviceVendor,
		@DeviceOperatingSystem,
		@DeviceOperatingSystem_Version,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)