

var translationsDoctorDE = {
    //***BUTTONS***//

    BUTTON_PASSSWORD_SENT: 'Passwort senden',
    BUTTON_CANCEL: 'Abbrechen',
    BUTTON_SAVE: 'Speichern',
    BUTTON_CONFIRM: 'BESTÄTIGEN',
    BUTTON_CONFIRML: 'Bestätigen',
    BUTTON_DELETE: 'DELETE',
    BUTTON_EDIT: 'Bearbeiten',
    BUTTON_BACK: 'Zurück',
    BUTTON_ADD_CONTRACT: 'Vertrag hinzufugen',
    BUTTON_ACTIVATE_DOCTOR_ACCOUNTS_CONFIRM: 'Ja, aktivieren',
    BUTTON_ACTIVATE_DOCTOR_ACCOUNTS_CANCEL: 'Nein, nicht aktivieren',
    BUTTON_DEACTIVATE_DOCTOR_ACCOUNTS_CONFIRM: 'Ja, deaktiviren',
    BUTTON_DEACTIVATE_DOCTOR_ACCOUNTS_CANCEL: 'Nein, nicht deaktivieren',

    //***LABELS***//

    LABEL_PRACTICE_NAME: 'Praxisname',
    LABEL_BANK: 'Kreditinstitut',
    LABEL_BANK_ACCOUNT: 'Bankverbindung',
    LABEL_GENERATE_PASSWORD: 'Passwort generieren',
    LABEL_DEFINE_PASSWORD: 'Passwort festlegen',
    LABEL_PASSWORD: 'Passwort',
    LABEL_REPEAT_PASSWORD: 'Passwort wiederholen',
    LABEL_RESET_PASSWORD: 'Passwort zurücksetzen',
    LABEL_DEACTIVATE_ACCOUNT: 'Account deaktivieren',

    LABEL_LOGIN_EMAIL: 'Login-E-Mail-Adresse',

    LABEL_EMAIL: 'E-Mail',
    LABEL_PHONE: 'Telefon',
    LABEL_FAX_NR: 'Fax-Nr.',

    LABEL_ADD_PRACTICE: 'Praxis hinzufügen',

    LABEL_STREET: 'Straße',
    LABEL_NO: 'Haus-Nr.',
    LABEL_ZIP: 'PLZ',
    LABEL_CITY: 'Ort',
    LABEL_BSNR: 'BSNR',
    LABEL_MAIN_EMAIL: 'Haupt-E-Mail-Adresse',
    LABEL_MAIN_PHONE: 'Haupt-Telefonnummer',
    LABEL_FAX: 'Fax',
    LABEL_CONTACT_PERSON: 'Ansprechpartner',
    LABEL_CONTACT_PRACTICE: 'Praxis Kontakt',

    LABEL_PRACTICE_BANK_ACCOUNT: 'Bankverbindung der Praxis',
    LABEL_ACCOUNT_HOLDER: 'Kontoinhaber',
    LABEL_BIC: 'BIC',
    LABEL_IBAN: 'IBAN',

    LABEL_PRACTICE: 'Praxis',
    LABEL_PRACTICE_ACCOUNT: 'Praxis Account',

    LABEL_WELCOMEEMAILWILLBESENTTOPRACTICE: 'Eine Willkommens-E-Mail wird an die Praxis versendet',
    LABEL_SURGERY_PRACTICE: 'operierende Praxis',
    LABEL_ORDERS_DRUGS: 'bestellt Medikamente',
    LABEL_DEFAULT_SHIPPING_DATE_OFFSET: 'Standardlieferdatum',
    LABEL_LABEL_DAYS_TO_OP: 'Tag/Tage vor der IVOM',
    LABEL_ONLY_LABEL_REQUIRED: 'Etiketten liefern',
    LABEL_WAIVE_SERVICE_FEE: 'Verwaltungs-pauschale erlassen',


    LABEL_ADD_DOCTOR: 'Arzt hinzufügen',
    LABEL_SALUTATION: 'Anrede',
    LABEL_TITLE: 'Titel',
    LABEL_FIRSTNAME: 'Vorname',
    LABEL_LASTNAME: 'Nachname',
    LABEL_LANR: 'LANR',
    LABEL_DOCTORSPRACTICE: 'Praxis des Arztes',
    LABEL_PRACTICE_DOCTOR_WORKS_IN: 'Praxis in denen der Arzt arbeitet',
    LABEL_PRACTICE: 'Praxis',
    LABEL_BANKACCOUNT: 'Bankverbindung',
    LABEL_USERPRACTICEBANK: 'Bankverbindung der Praxis übernehmen',
    LABEL_ACCOUNT: 'Account',
    LABEL_WELCOMEEMAILWILLBESENTTODOCTOR: 'Eine Willkommens-E-Mail wird an den Arzt versendet',

    LABEL_INVALID_PLZ_NO: 'Ungültiges Postleitzahlenformat (nummerisch).',
    LABEL_INVALID_BSNR_NO: 'Ungültiges BSNR-Format (nummerisch).',
    LABEL_BSNR_LENGTH: 'Ungültiges BSNR-Format (Länge).',
    LABEL_BSNR_EXISTS: 'BSNR existiert bereits.',
    LABEL_EMAIL_NOT_VALID: 'Ungültige E-Mail-Adresse.',
    LABEL_INVALID_DATEFORMAT_NO: 'Ungültiges Datumsformat (nummerisch).',
    LABEL_IBAN_INVALID: 'Ungültige IBAN.',
    LABEL_BIC_INVALID: 'Ungültige BIC.',
    LABEL_ENTER_BANK_NAME: 'Bitte tragen Sie den Namen der Bank ein.',
    LABEL_ENTER_BIC: 'Bitte tragen Sie den BIC ein.',
    LABEL_ACCOUNT_EXISTS: 'Ein Konto mit dieser E-Mail-Adresse existiert bereits.',
    LABEL_ENTER_PASSWORD: 'Bitte geben Sie ein Passwort ein.',
    LABEL_PASSWORD_FORMAT: 'Bitte verwenden Sie für Ihr Passwort mind. 8 große und kleine Buchstaben und mind. eine Ziffer. Für erhöhte Passwortsicherheit wird die zusätzliche Verwendung der folgenden Symbole empfohlen: ~!@#$%^&*_-+=`|\(){}[]:;<>,.?/".',
    LABEL_PASSWORD_MISMATCH: 'Passwörter stimmen nicht überein.',
    LABEL_INVALID_LANR: 'Ungültige LANR.',
    LABEL_LANR_LENGTH: 'Ungültiges LANR-Format (Länge).',
    LABEL_LANR_EXISTS: 'LANR existiert bereits.',
    LABEL_INVALID_LANR_NO: 'Ungültiges LANR-Format (nummerisch).',

    LABEL_DOCTOR_PRACTICE_NAME: 'Nachname, Vorname/Praxis',
    LABEL_DOCTOR_NAME: 'Nachname, Vorname (Arzt)',
    LABEL_DOCTOR_PRACTICE: 'Arzt/Praxis',
    LABEL_BSNR_LANR: 'BSNR/LANR',
    LABEL_CONTRACT: 'Verträge',
    LABEL_ADDRESS: 'Adresse',
    LABEL_CONTACT: 'Kontakt',
    LABEL_BANK: 'Bank',
    LABEL_IBAN_BIC: 'IBAN/BIC',
    LABEL_ACCOUNT_STATUS: 'Account-Status',
    LABEL_PRACTICE_ADDED: 'Neuer Praxis gespeichert',
    LABEL_DOCTOR_ADDED: 'Neuer Arzt gespeichert',

    LABEL_ADD_CONTRACT: 'Vertrag hinzufügen',
    LABEL_CONTRACT: 'Vertrag',
    LABEL_START_DATE: 'Gültig von',
    LABEL_END_DATE: 'Gültig bis',
    LABEL_CONTRACT_START_DATE_INVALID: 'Contract start date invalid.',
    LABEL_CONTRACT_END_DATE_INVALID: 'Contract end date invalid.',
    LABEL_HIP: 'Krankenkassen',
    LABEL_IBAN_NOT_FOUND: 'IBAN not found.',
    LABEL_ACTIVATE_DOCTOR_ACCOUNTS_TITLE: 'Arzt-Konten aktivieren',
    LABEL_DEACTIVATE_DOCTOR_ACCOUNTS_TITLE: 'Arzt-Konten deaktivieren',
    LABEL_ACTIVATE_DOCTOR_ACCOUNTS_CONTENT: 'Bitte beachten Sie, dass auch die Konten der Ärzte dieser Praxis aktiviert werden.',
    LABEL_DEACTIVATE_DOCTOR_ACCOUNTS_CONTENT: 'Bitte beachten Sie, dass auch die Konten der Ärzte dieser Praxis deaktiviert werden.',
    LABEL_DOCTORS: 'Ärzte',
    LABEL_PRACTICES: 'Praxen',
    LABEL_INACTIVE: 'Inaktiv',
    LABEL_ACTIVE: 'Aktiv',
    LABEL_TEMP: 'Temporär',

    LABEL_APOTHEKE_NAME: 'Name der Apotheke',
    LABEL_DELIVERY_FROM_INVALID: 'Delivery date from is invalid',
    LABEL_DELIVERY_TO_INVALID: 'Delivery date to is invalid',
    LABEL_FROM_LOWER: 'From must be lower than to date',
    LABEL_NONE: 'None',

    LABEL_CONTRACT_START_DATE_NOT_IN_CONTRACT_VALIDITY_TIMESPAN: 'Selected start date is not in selected contract\'s validity timespan ({{contractValidityTimespan}})',
    LABEL_CONTRACT_END_DATE_BEFORE_CONTRACT_START_DATE: 'Selected end date is not after selected start date.',
    LABEL_CONTRACT_END_DATE_NOT_IN_CONTRACT_VALIDITY_TIMESPAN: 'Selected end date is not in selected contract\'s validity timespan ({{contractValidityTimespan}})'

};
var translationsDoctorEN = {

    //***BUTTONS***//

    BUTTON_CANCEL: 'Cancel',
    BUTTON_SAVE: 'Save',


    BUTTON_CONFIRM: 'CONFIRM',
    BUTTON_CONFIRML: 'Confirm',

    BUTTON_DELETE: 'DELETE',
    BUTTON_EDIT: 'EDIT',
    BUTTON_BACK: 'Back',
    BUTTON_ADD_CONTRACT: 'Add Contract',
    BUTTON_PASSSWORD_SENT: 'Password sent',
    BUTTON_ACTIVATE_DOCTOR_ACCOUNTS_CONFIRM: 'Yes, activate',
    BUTTON_DEACTIVATE_DOCTOR_ACCOUNTS_CANCEL: 'No, don\'t activate',
    BUTTON_ACTIVATE_DOCTOR_ACCOUNTS_CONFIRM: 'Yes, deactivate',
    BUTTON_DEACTIVATE_DOCTOR_ACCOUNTS_CANCEL: 'No, don\'t deactivate',

    //***LABELS***//

    LABEL_PRACTICE_NAME: 'Practice name',
    LABEL_BANK: 'Bank',

    LABEL_GENERATE_PASSWORD: 'Generate password',
    LABEL_DEFINE_PASSWORD: 'Define password',
    LABEL_PASSWORD: 'Password',
    LABEL_REPEAT_PASSWORD: 'Repeat password',
    LABEL_RESET_PASSWORD: 'Reset password',
    LABEL_DEACTIVATE_ACCOUNT: 'Deactivate account',

    LABEL_LOGIN_EMAIL: 'Login Email',
    LABEL_BANK_ACCOUNT: 'Bank Account',
    LABEL_EMAIL: 'E-Mail',
    LABEL_PHONE: 'Phone-Nr.',
    LABEL_FAX_NR: 'Fax-Nr.',

    LABEL_ADD_PRACTICE: 'Add practice',
    LABEL_STREET: 'Street',
    LABEL_NO: 'No.',
    LABEL_ZIP: 'ZIP',
    LABEL_CITY: 'City',
    LABEL_BSNR: 'BSNR',
    LABEL_MAIN_EMAIL: 'Main Email',
    LABEL_MAIN_PHONE: 'Main phone',
    LABEL_FAX: 'Fax',
    LABEL_CONTACT_PERSON: 'Contact person',
    LABEL_CONTACT_PRACTICE: 'Contact practice',
    LABEL_PRACTICE_BANK_ACCOUNT: 'Practice Bank Account',
    LABEL_ACCOUNT_HOLDER: 'Account holder',
    LABEL_BIC: 'BIC',
    LABEL_IBAN: 'IBAN',
    LABEL_PRACTICE: 'Praxis',
    LABEL_PRACTICE_ACCOUNT: 'Practice account',
    LABEL_WELCOMEEMAILWILLBESENTTOPRACTICE: 'A welcome email will be sent to the practice',
    LABEL_SURGERY_PRACTICE: 'surgery Practice',
    LABEL_ORDERS_DRUGS: 'Orders Drugs',
    LABEL_DEFAULT_SHIPPING_DATE_OFFSET: 'Default shipping date offset',
    LABEL_LABEL_DAYS_TO_OP: 'Tag/Tage vor der IVOM',
    LABEL_ONLY_LABEL_REQUIRED: 'Only label required',
    LABEL_WAIVE_SERVICE_FEE: 'Waive Service Fee',

    LABEL_ADD_DOCTOR: 'Add doctor',
    LABEL_SALUTATION: 'Salutation',
    LABEL_TITLE: 'Title',
    LABEL_FIRSTNAME: 'First name',
    LABEL_LASTNAME: 'Last name',
    LABEL_LANR: 'LANR',
    LABEL_DOCTORSPRACTICE: 'Doctor’s Practice',
    LABEL_PRACTICE_DOCTOR_WORKS_IN: 'Practice the doctor works in',
    LABEL_PRACTICE: 'Practice',
    LABEL_BANKACCOUNT: 'Bank Account',
    LABEL_USERPRACTICEBANK: 'Use Practice Bank Account',
    LABEL_ACCOUNT: 'Account',
    LABEL_WELCOMEEMAILWILLBESENTTODOCTOR: 'A welcome email will be send to the doctor.',

    LABEL_INVALID_PLZ_NO: 'Invalid ZIP code format (numeric).',
    LABEL_INVALID_BSNR_NO: 'Invalid BSNR format (numeric).',
    LABEL_BSNR_LENGTH: 'Invalid BSNR format (length).',
    LABEL_BSNR_EXISTS: 'BSNR already exists.',
    LABEL_EMAIL_NOT_VALID: 'Invalid email address format.',
    LABEL_INVALID_DATEFORMAT_NO: 'Invalid date format (numeric).',
    LABEL_IBAN_INVALID: 'Invalid IBAN.',
    LABEL_BIC_INVALID: 'Invalid BIC.',
    LABEL_ENTER_BANK_NAME: "Please enter the bank's name.",
    LABEL_ENTER_BIC: 'Please enter the BIC.',
    LABEL_ACCOUNT_EXISTS: 'An account with this email address exists already.',
    LABEL_ENTER_PASSWORD: 'Please enter a password.',
    LABEL_PASSWORD_FORMAT: 'Please create a password with at least 8 characters in upper/lower case and at least one number. It is recommended to add the following symbols for extra security ~!@#$%^&*_-+=`|\(){}[]:;<>,.?/.',
    LABEL_PASSWORD_MISMATCH: 'Password missmatch.',

    LABEL_INVALID_LANR: 'Invalid LANR.',
    LABEL_LANR_EXISTS: 'LANR already exists.',
    LABEL_INVALID_LANR_NO: 'Invalid LANR format (numeric).',
    LABEL_LANR_LENGTH: 'Invalid LANR format (length).',

    LABEL_DOCTOR_PRACTICE_NAME: 'Last Name, First Name, Practice ',
    LABEL_DOCTOR_PRACTICE: 'Doctor/Practice',
    LABEL_BSNR_LANR: 'BSNR/LANR',
    LABEL_CONTRACT: 'Contracts',
    LABEL_ADDRESS: 'Address',
    LABEL_CONTACT: 'Contact',
    LABEL_BANK: 'Bank',
    LABEL_IBAN_BIC: 'IBAN/BIC',
    LABEL_ACCOUNT_STATUS: 'Account Status',
    LABEL_PRACTICE_ADDED: 'New Practice saved.',
    LABEL_DOCTOR_ADDED: 'New Doctor saved.',

    LABEL_ADD_CONTRACT: 'Add Contract',
    LABEL_CONTRACT: 'Contract',
    LABEL_START_DATE: 'Valid from',
    LABEL_END_DATE: 'Valid to',

    LABEL_CONTRACT_START_DATE_INVALID: 'Contract start date invalid.',
    LABEL_CONTRACT_END_DATE_INVALID: 'Contract end date invalid.',
    LABEL_HIP: 'Health Insurance Providers',

    LABEL_IBAN_NOT_FOUND: 'IBAN not found.',
    LABEL_ACTIVATE_DOCTOR_ACCOUNTS_TITLE: 'Doctor accounts activation',
    LABEL_DEACTIVATE_DOCTOR_ACCOUNTS_TITLE: 'Doctor accounts deactivation',
    LABEL_ACTIVATE_DOCTOR_ACCOUNTS_CONTENT: 'Please note that all related accounts for this practice\'s doctors will be activated as well.',
    LABEL_DEACTIVATE_DOCTOR_ACCOUNTS_CONTENT: 'Please note that all related accounts for this practice\'s doctors will be deactivated as well.',

    LABEL_DOCTORS: 'Doctors',
    LABEL_PRACTICES: 'Practices',
    LABEL_INACTIVE: 'Inactive',
    LABEL_ACTIVE: 'Inactive',
    LABEL_TEMP: 'Inactive',
    LABEL_APOTHEKE_NAME: 'Name der Apotheke',
    LABEL_DELIVERY_FROM_INVALID: 'Delivery date from is invalid',
    LABEL_DELIVERY_TO_INVALID: 'Delivery date to is invalid',
    LABEL_FROM_LOWER: 'From must be lower than to date',
    LABEL_NONE: 'None',

};
