

var translationsOrderDE = {
    //***LABELS***//
    LABEL_ALTERNATIVE_DELIVERY_DATE: 'Abweichendes lieferdatum',
    LABEL_DELIVERY_DATE: 'Lieferdatum',
    LABEL_DELIVERY_TIME: 'Lieferzeit',
    LABEL_DRUG_NAME: 'Name des Medikaments',
    LABEL_NO_FEE: 'Gebührenbefreit',
    LABEL_PRACTICE_INVOICE: 'Rechnung an Praxis',
    LABEL_ORDER_DRUG: 'Medikament bestellen',
    LABEL_ONLY_LABEL_REQUIRED: 'Nur Etikett liefern',
    LABEL_PATIENT_NAME: 'Name des Patienten',
    LABEL_TREATMENT_DATE: 'Behandlungsdatum',
    LABEL_ADD_TREATMENT: 'Behandlung hinzufügen',
    LABEL_FROM: 'von',
    LABEL_TO: 'bis',
    LABEL_HOUR: 'Uhr',
    LABEL_DRUG: 'Medikament',
    LABEL_PHARMACY: 'Apotheke',
    LABEL_LOKALIZATION: 'Lokalisation',
    LABEL_LEFT: 'links',
    LABEL_RIGHT: 'rechts',
    LABEL_CONFIRMED: 'Gesichert',
    LABEL_OP_DOCTOR: 'OP-Arzt',
    LABEL_AC_DOCTOR: 'Nachsorgearzt',
    LABEL_ADD_NEW_PATIENT: 'neuen Patient anlegen',
    LABEL_DIAGNOSE_DRUG: 'Diagnose / Medikament',
    LABEL_AFTERCARE: 'Nachsorge',
    LABEL_STATUS: 'Status',
    LABEL_LAST_NAME_FIRST_NAME_DOB: 'Nachname, Vorname',
    LABEL_INVALID_DELIVERY_TIME: 'Lieferzeit von must be greater than or equal to Liereferzeit bis',
    LABEL_LAST_USED: 'ZULETZT VERWENDET',
    OP1: 'Behandlung geplant',
    MO0: 'offen',
    MO8: 'überfällig',
    MO1: 'Medikament bestellt',
    MO2: 'Bestellung angenommen',
    MO3: 'Medikament in Auslieferung',
    MO4: 'Medikament nicht lieferbar',
    MO6: 'Storniert',
    MO10: 'Externally ordered',
    LABEL_ORDERED: 'bestellt',
    LABEL_EXTERNALLY_ORDERED: 'externally ordered',
    LABEL_ACCEPTED: 'angenommen',
    LABEL_REJECTED2: 'nicht lieferbar',
    LABEL_SHIPPED: 'in Auslieferung',
    LABEL_CANCELED: 'stornierte',
    LABEL_OVERDUE: 'überfällige',

    
    LABEL_ORDER_STATUS: 'Order Status, Status Datum',
    LABEL_DOC_OR_PRACTICE: 'Arzt,Praxis',
    LABEL_CONFIRM_REJECT_ORDER: 'Bitte bestätigen Sie die Ablehnung der Bestellung mit ihrem Passwort.',
    LABEL_REJECT_ORDER: 'Bestellung abgelehnt',

    LABEL_ORDERS_SHIPPING_POPUP: '{{eligible}} of {{total}} orders will not be shipped because they are not in suitable status. Maybe you are trying to import an old file? If you would like to review the file first, click cancel. Otherwise click proceed – all currently accepted orders will be shipped',
    LABEL_ORDERS_SHIPPING_POPUPS: 'bestellungen ausliefern',
    LABEL_CASES_STATUS_CHANGED: 'Cases status changed to FS2, report created and uploaded to archive',

    //***BUTTONS***//
    BUTTON_ADD_PARTICIPATION_CONSENT: 'Teilnahmeerklärung hinzufügen',
    BUTTON_REJECT_ORDER: 'Bestellung ablehnen'
    
};
var translationsOrderEN = {
    //***LABELS***//
  
    LABEL_ALTERNATIVE_DELIVERY_DATE: 'Alternative delivery date',
    LABEL_DELIVERY_DATE: 'Delivery date',
    LABEL_DELIVERY_TIME: 'Delivery time',
    LABEL_DRUG_NAME: 'Drug',
    LABEL_NO_FEE: 'No fee',
    LABEL_PRACTICE_INVOICE: 'Invoice to Practice',
    LABEL_ORDER_DRUG: 'Order drug',
    LABEL_ONLY_LABEL_REQUIRED: 'Only label required',
    LABEL_PATIENT_NAME: 'Patient Name',
    LABEL_TREATMENT_DATE: 'Treatment date',
    LABEL_ADD_TREATMENT: 'Add Treatment',
    LABEL_FROM: 'from',
    LABEL_TO: 'to',
    LABEL_HOUR: 'Hours',
    LABEL_DRUG: 'Drug',
    LABEL_PHARMACY: 'Pharmacy',
    LABEL_DIAGNOSE: 'Diagnosis',
    LABEL_LOKALIZATION: 'Effected Eye',
    LABEL_LEFT: 'left',
    LABEL_RIGHT: 'right',
    LABEL_CONFIRMED: 'Confirmed',
    LABEL_OP_DOCTOR: 'OP Doctor',
    LABEL_AC_DOCTOR: 'Aftercare Doctor',
    LABEL_ADD_NEW_PATIENT: 'add new patient',
    LABEL_DIAGNOSE_DRUG: 'Diagnose / Drug',
    LABEL_AFTERCARE: 'Aftercare',
    LABEL_STATUS: 'Status',
    LABEL_LAST_NAME_FIRST_NAME_DOB: 'Last Name, First Name',
    LABEL_INVALID_DELIVERY_TIME: 'Delivery time to must be greater than or equal to delivery time from',
    LABEL_LAST_USED: 'LAST USED',
    OP1: 'Treatment planned',
    MO1: 'neue Bestellung',
    MO2: 'angenommen',
    MO3: 'in Auslieferung',
    MO4: 'abgelehnt',
    MO6: 'storniert',
    MO10: 'Externally ordered',
    LABEL_ORDERED: 'Ordered ',
    LABEL_EXTERNALLY_ORDERED: 'externally ordered',
    LABEL_ACCEPTED: 'Accepted',
    LABEL_REJECTED2: 'Rejected',
    LABEL_SHIPPED: 'Shipped',
    LABEL_CANCELED: 'Canceled',
    LABEL_OVERDUE: 'Overdue',

    LABEL_CONFIRM_REJECT_ORDER: 'Please confirm the order rejection with your password.',
    LABEL_ORDER_STATUS: 'Order status,Status Date',
    LABEL_DOC_OR_PRACTICE: 'Doc,Practice',



    LABEL_REJECT_ORDER: 'Order rejected',

    LABEL_ORDERS_SHIPPING_POPUP: 'orders will not be shipped because they are not in suitable status. Maybe you are trying to import an old file? If you would like to review the file first, click cancel. Otherwise click proceed – all currently accepted orders will be shipped',
    LABEL_ORDERS_SHIPPING_POPUPS: 'orders shipped',
    LABEL_CASES_STATUS_CHANGED: 'Cases status changed, report created and uploaded to archive',
    //***BUTTONS***//
    BUTTON_ADD_PARTICIPATION_CONSENT: 'Add participation consent',
    BUTTON_REJECT_ORDER: 'Order declined'
};