

var translationsPatientDE = {
    //***BUTTONS***//
    BUTTON_ADD_PARTICIPATION_CONSENT: 'Teilnahmeerklärung hinzufügen',
    //***LABELS***//

    LABEL_LEFT_EYE: 'Linkes Auge',
    LABEL_RIGHT_EYE: 'Rechtes Auge',
    LABEL_OP: 'IVOM',
    LABEL_OCT: 'OCT',
    LABEL_OCT_DOCTOR: 'Oct Arzt',

    LABEL_FIRST_NAME: 'Vorname',
    LABEL_LAST_NAME: 'Nachname',
    LABEL_LAST_NAME_FIRST_NAME: 'Nachname, Vorname',
    LABEL_SEX: 'Geschlecht',
    LABEL_DATE_OF_BIRTH: 'Geburtsdatum',
    LABEL_HEALTH_INSURANCE_PROVIDER: 'Krankenkasse',
    LABEL_INSURANCE_ID: 'Versichertennummer',
    LABEL_INSURANCE_STATUS: 'Versichertenstatus',
    LABEL_NEW_PATIENT: 'neuer Patient',
    LABEL_PARTICIPATION_CONSENT: 'Teilnahmeerklärung',
    LABEL_ADD_PARTICIPATION_CONSENT: 'Teilnahmeerklärung hinzufügen',
    LABEL_INVALID_HEALTH_INSURANCE_NUMBER: 'Ungültiges Versichertennummer.',
    LABEL_INVALID_INSURANCE_STATUS_CODE: 'Ungültiges Versichertenstatus',
    LABEL_SAVED_NEW_PATIENT: 'Neuer Patient gespeichert.',
    LABEL_CANT_SAVE: 'Die Änderung konnte nicht gespeichert werden.',
    LABEL_PATIENTDATA_NOT_ALIGNRD_WITH_HIN: 'Der Versichertenstatus stimmt nicht mit den Patientendetails überein.',
    LABEL_HIN_MATCHES_ANY_OTHER_PATIENT_IN_PRACTICE: 'Es existiert bereits ein Patient namens {{first_name}} {{last_name}} mit identischer Versicherungsnummer.',
    LABEL_COMBINATION_FIRST_LAST_NAME_HIM_MATCHES: 'Es existiert bereits ein Patient namens {{first_name}} {{last_name}} mit identischem Geburtsdatum.',
    LABEL_CASE: 'Vorgänge',
    LABEL_PARTICIPATION_CONSENT: 'Teilnahmeerklärung',
    LABEL_CONTRACT: 'Vertrag',
    LABEL_ISSUE_DATE: 'Austellungsdatum',
    LABEL_ISSUE_DATE_LOWER_THEN_CONTRACT_DATE: 'Teilnahmeerklärung Datum muss im Zeitbereich vom Vertragslaufzeitdatum sein.',
    LABEL_SAVED_NEW_PARTICIPATION_CONSENT: 'Teilnahmeerklärung geschpeichert.',
    LABEL_PATIENT_EDITED: 'Patient bearbeitet.',
    LABEL_HEALTH_INSURANCE_NUMBER_ONLY_DIGITS: 'Der Versichertenstatus darf nur Zahlen enthalten.',
    LABEL_ERROR_NEW_KVR_VALIDATION: 'Inserted KVNR number breaks validation rules for the new KVNR, but passes validation rules for old KVNR (6-12 digits).',    
    LABEL_DIAGNOSIS_DRUG: 'Diagnose / Medikament',
    LABEL_NOT_ORDERED: 'Medikament nicht bestellt',
    LABEL_PARTICIPATION_ACTIVE: 'Teilnahmeerklärung aktiv',
    LABEL_PARTICIPATION_NOT_ACTIVE: 'Teilnahmeerklärung abgelaufen',
    LABEL_PARTICIPATION_NOT_YET_ACTIVE: 'Teilnahmeerklärung noch nicht aktiv',

    LABEL_ACTIVE_CONSENT: 'aktualisiert',
    LABEL_EXPIRED_CONSENT: 'abgelaufen',

    LABEL_OP_DATE: "IVOM",
    LABEL_PATIENT_ID: 'externe ID',
    LABEL_PATIENT_FEE_WAIVED_FROM: 'Gebührenbefreit seit',
    LABEL_TREATMENT_YEAR: 'Behandlungsjahr',
    LABEL_REJECTED_OCT: 'Nicht zugewiesen',
    op: 'Behandlung',
    ac: 'Nachsorge',
    order: 'Bestellungen',
    participation: 'Teilnahmeerklärung',
};
var translationsPatientEN = {

    //***BUTTONS***//
    BUTTON_ADD_PARTICIPATION_CONSENT: 'Add participation consent',

    //***LABELS***//


    LABEL_FIRST_NAME: 'First Name',
    LABEL_LAST_NAME: 'Last Name',
    LABEL_LAST_NAME_FIRST_NAME: 'First Name, Last Name',
    LABEL_SEX: 'Sex',
    LABEL_DATE_OF_BIRTH: 'Date of birth',
    LABEL_HEALTH_INSURANCE_PROVIDER: 'Health Insurance Provider',
    LABEL_INSURANCE_ID: 'Insurance ID',
    LABEL_INSURANCE_STATUS: 'Insurance Status',
    LABEL_NEW_PATIENT: 'new Patient',
    LABEL_PARTICIPATION_CONSENT: 'Participation consent',
    LABEL_ADD_PARTICIPATION_CONSENT: 'Add participation consent',
    LABEL_INVALID_HEALTH_INSURANCE_NUMBER: 'Invalid Insurance ID.',
    LABEL_INVALID_INSURANCE_STATUS_CODE: 'Invalid Insurance Status',
    LABEL_SAVED_NEW_PATIENT: 'New patient saved.',
    LABEL_CANT_SAVE: 'Changes saved',
    LABEL_PATIENTDATA_NOT_ALIGNRD_WITH_HIN: 'The health insurance status doesn’t match with the patient’s data.',
    LABEL_HIN_MATCHES_ANY_OTHER_PATIENT_IN_PRACTICE: 'There is record of a patient {{first_name}} {{last_name}} with the same insurance number. ',
    LABEL_COMBINATION_FIRST_LAST_NAME_HIM_MATCHES: 'There is a record of a patient named {{first_name}} {{last_name}} , born on the same date in the system.',
    LABEL_CASE: 'Cases',
    LABEL_PARTICIPATION_CONSENT: 'Teilnahmeerklärung',
    LABEL_CONTRACT: 'Contract',
    LABEL_ISSUE_DATE: 'Issue date',
    LABEL_ISSUE_DATE_LOWER_THEN_CONTRACT_DATE: 'Participation consent date must be in range of the contract duration date.',
    LABEL_SAVED_NEW_PARTICIPATION_CONSENT: 'Participation consent saved.',
    LABEL_PATIENT_EDITED: 'Patient edited.',
    LABEL_HEALTH_INSURANCE_NUMBER_ONLY_DIGITS: 'Helath insurance number should contain only numbers.',
    LABEL_ERROR_NEW_KVR_VALIDATION: 'Inserted KVNR number breaks validation rules for the new KVNR, but passes validation rules for old KVNR (6-12 digits).',
    LABEL_CASE_ONE: 'Case',
    LABEL_DIAGNOSIS_DRUG: 'Diagnosis / Drug',
    LABEL_NOT_ORDERED: 'Medicine not ordered',
    LABEL_PARTICIPATION_ACTIVE: 'Teilnahmeerklärung aktiv',
    LABEL_PARTICIPATION_NOT_ACTIVE: 'Teilnahmeerklärung abgelaufen',

    LABEL_OP_DATE: "IVOM",
    LABEL_PATIENT_ID: 'externe ID',
    LABEL_PATIENT_FEE_WAIVED_FROM: 'Gebührenbefreit seit',
    LABEL_TREATMENT_YEAR: 'Behandlungsjahr',
    LABEL_REJECTED_OCT: 'Nicht zugewiesen',
    op: 'Operation',
    ac: 'Aftercare',
    order: 'Order',
    participation: 'Participation',

};