

var translationsTreatmentDE = {
    //***LABELS***//
    LABEL_TREATMENT: 'Behandlung',
    LABEL_LOKALIZATION: 'Lokalisation',
    LABEL_DIAGNOSE_DRUG: 'Diagnose, Medikament',
    LABEL_LAST_NAME_FIRST_NAME_DOB: 'Nachname, Vorname',
    LABEL_CASE_TYPE: 'Vorgang',
    LABEL_DOCTOR_PRACTICE: 'Arzt, Praxis',
    LABEL_MANAGEMENT_FEE: 'Management-pauschale',
    LABEL_STATUS_STATUS_DATE: 'Status, Status Datum',
    LABEL_MANAGEMENT_FEE_WAIVED: 'erlassen',
    LABEL_MANAGEMENT_FEE_DEDUCTED: 'berechnen',
    LABEL_HIP_RESPONSE: 'Nachricht der Krankenkasse',
    LABEL_COMMENT_FIELD: 'Kommentarfeld (optional)',
    LABEL_CASE_SUBMITTED_FOR_ERROR_CORRECTION: 'Der Vorgang wurde dem Arzt übermittelt.',
    LABEL_THIS_WEEK: 'diese Woche',
    LABEL_LAST_4_WEEKS: 'letzte 4 Wochen',
    LABEL_LAST_WEEK: 'letzte Woche',
    LABEL_LAST_MONTH: 'letzter Monat',
    LABEL_THIS_MONTH: 'dieser Monat',

    LABEL_LAST_90_DAYS: 'letzte 90 Tage',
    LABEL_ENTER_DATE_PERIOD: 'Zeitraum eingrenzen',
    LABEL_DATE_PERIOD: 'Zeitraum',
    LABEL_ALL: 'Alles',
    LABEL_OPERATIONS: 'Behandlung',
    LABEL_AFTERCARES: 'Nachsorge',
    LABEL_READY: 'freigegeben',
    LABEL_SUBMITTED: 'übermittelt',
    LABEL_ON_HOLD: 'Gesperrt',
    LABEL_NOT_ON_HOLD: 'Nicht gesperrt',
    LABEL_CONFIRMED: 'bestätigt',
    LABEL_ERRORS: 'Fehlermeldung',
    LABEL_CORRECTION: 'Wartet auf Korrektur',
    LABEL_PAID: 'ausgezahlt',
    LABEL_CANCELLED: 'storniert',
    LABEL_REJECTED: 'abgelehnt',
    LABEL_RECLAIM: 'Rückforderung',
    LABEL_CHANGE_STATUS_POPUP_TITLE: 'Managementpauschale und / oder Status für Auswahl ändern',
    LABEL_CHANGE_MANAGEMENT_FEE_STATUS: 'Managementpauschale ändern',
    LABEL_DOCTOR_RESPONSIBLE: 'Mitarbeiter',
    LABEL_PASSWORD: 'Passwort',
    LABEL_GROUND: 'Grund',
    LABEL_STATUS: 'Status',
    LABEL_PLEASE_ENTER_PASSWORD_TO_EDIT_CASE: 'Bitte geben Sie Ihr passwort ein um die Änderung zu bestätigen',
    LABEL_EDIT_STATUS: 'Status ändern',
    LABEL_MULTI_CHANGE_STATUS_ELGIBILITY: '{{eligible}} of {{total}} selected cases will not be edited, since they are already in the selected status. Continue?',

    //***STATUS LABELS***//
    FS0: 'Offen',
    FS1: 'Zur Übermittlung freigegeben',
    FS2: 'Übermittelt',
    FS3: 'Gesperrt',
    FS4: 'Bestätigt',
    FS5: 'Korrektur erforderlich',
    FS6: 'Auf Fehlerbearbeitung warten',
    FS7: 'Überwiesen',
    FS8: 'Storniert',
    FS9: 'Ablehnung durch Krankenkasse',
    FS10: 'Rückforderung',
    FS11: 'Stornierung anhängig',
    FS21: 'Unerledigt',
    FS13: 'zur Dokumentation',

    OP1: 'Behandlung geplant',
    OP3: 'Überfällig',
    OP4: 'Gelöscht',

    AC1: 'offen',
    AC3: 'überfällig',
    AC4: 'zurückgezogen',
    AC10: 'bezahlt',
    AC11: 'storniert',
    AC12: 'ablehnung durch die Krankenkasse',

    OCT4: 'zurückgezogen',

    //***BUTTONS***//
    BUTTON_REJECT_ORDER: 'Bestellung ablehnen',
    BUTTON_RETURN_TO_DOCTOR: 'Zurück zum Arzt',
    BUTTON_CHANGE_STATUS: 'Status/Pauschale ändern'
    
};
var translationsTreatmentEN = {
    //***LABELS***//  
    LABEL_TREATMENT: 'Treatment',
    LABEL_LOKALIZATION: 'Effected Eye',
    LABEL_DIAGNOSE_DRUG: 'Diagnose / Drug',
    LABEL_LAST_NAME_FIRST_NAME_DOB: 'Last Name, First Name',
    LABEL_CASE_TYPE: 'Case Type',
    LABEL_DOCTOR_PRACTICE: 'Doctor, Practice',
    LABEL_MANAGEMENT_FEE_WAIVED: 'waived',
    LABEL_MANAGEMENT_FEE_DEDUCTED: 'deducted',
    LABEL_HIP_RESPONSE: 'Message from HIP',
    LABEL_COMMENT_FIELD: 'Comment (optional)',
    LABEL_CASE_SUBMITTED_FOR_ERROR_CORRECTION: 'Case returned to doctor successfully.',
    LABEL_THIS_WEEK: 'this week',
    LABEL_LAST_4_WEEKS: 'last 4 weeks',
    LABEL_LAST_WEEK: 'last week',
    LABEL_LAST_MONTH: 'last month',
    LABEL_THIS_MONTH: 'this month',
    LABEL_LAST_90_DAYS: 'last 90 days',
    LABEL_ENTER_DATE_PERIOD: 'Enter date period',
    LABEL_DATE_PERIOD: 'Date period',
    LABEL_ALL: 'All',
    LABEL_OPERATIONS: 'Treatment',
    LABEL_AFTERCARES: 'Aftercare',
    LABEL_READY: 'Ready',
    LABEL_SUBMITTED: 'Submitted',
    LABEL_ON_HOLD: 'On hold',
    LABEL_NOT_ON_HOLD: 'Not on hold',
    LABEL_CONFIRMED: 'Confirmed',
    LABEL_ERRORS: 'Error',
    LABEL_CORRECTION: 'Waiting for correction',
    LABEL_PAID: 'Paid',
    LABEL_CANCELLED: 'Canceled',
    LABEL_REJECTED: 'Rejected',
    LABEL_RECLAIM: 'Reclaim',
    LABEL_EDIT_STATUS: 'Edit status',
    LABEL_MULTI_CHANGE_STATUS_ELGIBILITY: '{{eligibile_cases}} of {{total_cases}} selected cases will not be edited, since they are already in the selected status. Continue?',

    //***STATUS LABELS***//
    FS0: 'open',
    FS1: 'Ready for submission to HIP',
    FS2: 'Submitted to HIP',
    FS3: 'On hold',
    FS4: 'Confirmed by HIP',
    FS5: 'Error feedback from HIP',
    FS6: 'Waiting for error correction',
    FS7: 'Paid',
    FS8: 'Canceled',
    FS9: 'Rejection by HIP',
    FS10: 'Reclaim the paiment',
    FS11: 'Cancellation pending',
    OP1: 'Treatment planned',
    OP3: 'Overdue',
    OP4: 'Deleted',


    AC1: 'open',
    AC2: 'performed',
    AC3: 'overdue',
    AC4: 'withdrawn',

    AC6: 'fee settlement',
    AC7: 'confirmed by HIP',
    AC8: 'error correction necessary',
    AC9: 'payment in process',
    AC10: 'Paid',
    AC11: 'canceled',
    AC12: 'rejection by the - HIP',



    LABEL_MANAGEMENT_FEE: 'Management Fee',
    LABEL_STATUS_STATUS_DATE: 'Status, Status Date',

    //***BUTTONS***//
    BUTTON_REJECT_ORDER: 'Reject order',
    BUTTON_RETURN_TO_DOCTOR: 'Return to doctor',
    BUTTON_CHANGE_STATUS: 'Change status/fee'
};