UPDATE 
	cmn_bpt_emp_employmentrelationship_templates_2_workingcontract
SET 
	CMN_BPT_EMP_EmploymentRelationship_Template_RefID=@CMN_BPT_EMP_EmploymentRelationship_Template_RefID,
	CMN_BPT_EMP_WorkingContract_RefID=@CMN_BPT_EMP_WorkingContract_RefID,
	Creation_Timestamp=@Creation_Timestamp,
	IsDeleted=@IsDeleted,
	Tenant_RefID=@Tenant_RefID
WHERE 
	AssignmentID = @AssignmentID