INSERT INTO 
	hec_patient_prescription_headers
	(
		HEC_Patient_Prescription_HeaderID,
		HEC_ACT_PerformedAction_RefID,
		Patient_RefID,
		PrescribedBy_Doctor_RefID,
		Prescription_InternalNumber,
		Prescription_Date,
		Prescription_Comment,
		Perscription_UploadedByBusinessParticipant_RefID,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@HEC_Patient_Prescription_HeaderID,
		@HEC_ACT_PerformedAction_RefID,
		@Patient_RefID,
		@PrescribedBy_Doctor_RefID,
		@Prescription_InternalNumber,
		@Prescription_Date,
		@Prescription_Comment,
		@Perscription_UploadedByBusinessParticipant_RefID,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)