INSERT INTO 
	log_wrh_racks
	(
		LOG_WRH_RackID,
		GlobalPropertyMatchingID,
		Area_RefID,
		Rack_Name,
		Shelf_NamePrefix,
		CoordinateCode,
		Shelves_Use_XCoordinate,
		Shelves_Use_YCoordinate,
		Shelves_Use_ZCoordinate,
		Shelves_XLabel,
		Shelves_YLabel,
		Shelves_ZLabel,
		IsStructureHidden,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@LOG_WRH_RackID,
		@GlobalPropertyMatchingID,
		@Area_RefID,
		@Rack_Name,
		@Shelf_NamePrefix,
		@CoordinateCode,
		@Shelves_Use_XCoordinate,
		@Shelves_Use_YCoordinate,
		@Shelves_Use_ZCoordinate,
		@Shelves_XLabel,
		@Shelves_YLabel,
		@Shelves_ZLabel,
		@IsStructureHidden,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)