INSERT INTO 
	cmn_bpt_customer_promiseddeliverytimes
	(
		CMN_BPT_Customer_PromisedDeliveryTimeID,
		Customer_RefID,
		CRONExpression,
		Specified_Product_Group_RefID,
		Specified_Product_RefID,
		Specified_Product_Variant_RefID,
		Specified_Product_Release_RefID,
		TimeToDelivery_in_min,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@CMN_BPT_Customer_PromisedDeliveryTimeID,
		@Customer_RefID,
		@CRONExpression,
		@Specified_Product_Group_RefID,
		@Specified_Product_RefID,
		@Specified_Product_Variant_RefID,
		@Specified_Product_Release_RefID,
		@TimeToDelivery_in_min,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)