INSERT INTO 
	hec_act_performedactions
	(
		HEC_ACT_PerformedActionID,
		HealthcarePerformedActionITL,
		Patient_RefID,
		IsPerformed_Internally,
		IfPerformedInternaly_ResponsibleBusinessParticipant_RefID,
		IsPerformed_Externally,
		IsPerformed_MedicalPractice_RefID,
		IfPerformed_MedicalPracticeType_RefID,
		IfPerformed_DateOfAction_Year,
		IfPerformed_DateOfAction_Month,
		IfPerformed_DateOfAction_Day,
		IfPerfomed_DateOfAction,
		IsFollowupPerformedAction,
		IsFollowupPerformed_PreviousPerformedAction_RefID,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@HEC_ACT_PerformedActionID,
		@HealthcarePerformedActionITL,
		@Patient_RefID,
		@IsPerformed_Internally,
		@IfPerformedInternaly_ResponsibleBusinessParticipant_RefID,
		@IsPerformed_Externally,
		@IsPerformed_MedicalPractice_RefID,
		@IfPerformed_MedicalPracticeType_RefID,
		@IfPerformed_DateOfAction_Year,
		@IfPerformed_DateOfAction_Month,
		@IfPerformed_DateOfAction_Day,
		@IfPerfomed_DateOfAction,
		@IsFollowupPerformedAction,
		@IsFollowupPerformed_PreviousPerformedAction_RefID,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)