INSERT INTO 
	cmn_qst_questionnaire_questionitems
	(
		CMN_QST_Questionnaire_ItemID,
		Questionnaire_Template_RefID,
		QuestionItem_Label_DictID,
		QuestionItem_Description_DictID,
		QuestionItem_SequenceNumber,
		IsAnswer_Standard,
		IfAnswer_StandardType_RefID,
		IsAnswer_Enum,
		IfAnswer_EnumType_RefID,
		Creation_Timestamp,
		IsDeleted,
		Tenant_RefID
	)
VALUES 
	(
		@CMN_QST_Questionnaire_ItemID,
		@Questionnaire_Template_RefID,
		@QuestionItem_Label,
		@QuestionItem_Description,
		@QuestionItem_SequenceNumber,
		@IsAnswer_Standard,
		@IfAnswer_StandardType_RefID,
		@IsAnswer_Enum,
		@IfAnswer_EnumType_RefID,
		@Creation_Timestamp,
		@IsDeleted,
		@Tenant_RefID
	)