INSERT INTO 
	res_str_apartment_requiredactions
	(
		RES_STR_Apartment_RequiredActionID,
		ApartmentPropertyAssessment_RefID,
		SelectedActionVersion_RefID,
		EffectivePrice_RefID,
		Comment,
		Action_PricePerUnit_RefID,
		Action_Unit_RefID,
		Action_UnitAmount,
		IsCustom,
		IfCustom_Name,
		IfCustom_Description,
		Creation_Timestamp,
		IsDeleted,
		Tenant_RefID,
		Action_Timeframe_RefID
	)
VALUES 
	(
		@RES_STR_Apartment_RequiredActionID,
		@ApartmentPropertyAssessment_RefID,
		@SelectedActionVersion_RefID,
		@EffectivePrice_RefID,
		@Comment,
		@Action_PricePerUnit_RefID,
		@Action_Unit_RefID,
		@Action_UnitAmount,
		@IsCustom,
		@IfCustom_Name,
		@IfCustom_Description,
		@Creation_Timestamp,
		@IsDeleted,
		@Tenant_RefID,
		@Action_Timeframe_RefID
	)