INSERT INTO 
	log_wrh_inj_inventryjob_countingresults
	(
		LOG_WRH_INJ_InventoryJob_CountingResultID,
		CountingRun_RefID,
		Process_Shelf_RefID,
		CountedAmount,
		IsDifferenceToExpectedQuantityFound,
		Product_RefID,
		Product_Variant_RefID,
		Product_Release_RefID,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@LOG_WRH_INJ_InventoryJob_CountingResultID,
		@CountingRun_RefID,
		@Process_Shelf_RefID,
		@CountedAmount,
		@IsDifferenceToExpectedQuantityFound,
		@Product_RefID,
		@Product_Variant_RefID,
		@Product_Release_RefID,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)