//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMDocConnectDBMethods.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMDocConnectDBMethods.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zurückgezogen.
        /// </summary>
        internal static string AC4 {
            get {
                return ResourceManager.GetString("AC4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a new record for a previously unknown aftercare ophthalmologist has just been created..
        /// </summary>
        internal static string adHocFirstLine {
            get {
                return ResourceManager.GetString("adHocFirstLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify the information for new doctor and the respective practice as soon as possible to avoid duplicates..
        /// </summary>
        internal static string adHocSecondLine {
            get {
                return ResourceManager.GetString("adHocSecondLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Aftercare Doctor.
        /// </summary>
        internal static string adHocSubject {
            get {
                return ResourceManager.GetString("adHocSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The aftercare.
        /// </summary>
        internal static string aftercare {
            get {
                return ResourceManager.GetString("aftercare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best regards,.
        /// </summary>
        internal static string bestRegards {
            get {
                return ResourceManager.GetString("bestRegards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        internal static string bodyLine1 {
            get {
                return ResourceManager.GetString("bodyLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for working with the mediosmanagement fee settlement program..
        /// </summary>
        internal static string bodyLine2 {
            get {
                return ResourceManager.GetString("bodyLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset. Your new password is:.
        /// </summary>
        internal static string bodyLine3 {
            get {
                return ResourceManager.GetString("bodyLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For security reasons we are recommending that you should change this password upon your first login..
        /// </summary>
        internal static string bodyLine4 {
            get {
                return ResourceManager.GetString("bodyLine4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please don’t hesitate to contact us in case of further questions..
        /// </summary>
        internal static string bodyLine6 {
            get {
                return ResourceManager.GetString("bodyLine6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viele Grüße..
        /// </summary>
        internal static string bodyLine7 {
            get {
                return ResourceManager.GetString("bodyLine7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dein Medios Connect Team..
        /// </summary>
        internal static string bodyLine8 {
            get {
                return ResourceManager.GetString("bodyLine8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medios Connect / Case cancellation.
        /// </summary>
        internal static string cancelataion_SubjectMail {
            get {
                return ResourceManager.GetString("cancelataion_SubjectMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been cancelled retroactively..
        /// </summary>
        internal static string cancelation_firstLine {
            get {
                return ResourceManager.GetString("cancelation_firstLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is still confirmed by the HIP. Please check this case..
        /// </summary>
        internal static string cancelation_secondLine {
            get {
                return ResourceManager.GetString("cancelation_secondLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to case.
        /// </summary>
        internal static string caseItem {
            get {
                return ResourceManager.GetString("caseItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case-.
        /// </summary>
        internal static string CaseNum1 {
            get {
                return ResourceManager.GetString("CaseNum1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number.
        /// </summary>
        internal static string CaseNum2 {
            get {
                return ResourceManager.GetString("CaseNum2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        internal static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment: .
        /// </summary>
        internal static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17172100035.
        /// </summary>
        internal static string ContractCharacteristicsID {
            get {
                return ResourceManager.GetString("ContractCharacteristicsID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17172100035.
        /// </summary>
        internal static string ContractCharacteristicsID1 {
            get {
                return ResourceManager.GetString("ContractCharacteristicsID1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to created by.
        /// </summary>
        internal static string createdBy {
            get {
                return ResourceManager.GetString("createdBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        internal static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed information for invoice.
        /// </summary>
        internal static string DetailedInfoForInvoice {
            get {
                return ResourceManager.GetString("DetailedInfoForInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diag. / .
        /// </summary>
        internal static string Diagnose {
            get {
                return ResourceManager.GetString("Diagnose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Medios Connect  .
        /// </summary>
        internal static string emailSubject {
            get {
                return ResourceManager.GetString("emailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medios Connect  / Neues Passwort.
        /// </summary>
        internal static string emailSubject1 {
            get {
                return ResourceManager.GetString("emailSubject1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Euro).
        /// </summary>
        internal static string Euro {
            get {
                return ResourceManager.GetString("Euro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax:.
        /// </summary>
        internal static string fax {
            get {
                return ResourceManager.GetString("fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for using the mediosmanagement fee settlement program.
        /// </summary>
        internal static string firstLine {
            get {
                return ResourceManager.GetString("firstLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string footerFrom {
            get {
                return ResourceManager.GetString("footerFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string footerTo {
            get {
                return ResourceManager.GetString("footerTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please don’t hesitate to contact us in case of further questions.
        /// </summary>
        internal static string fourthLine {
            get {
                return ResourceManager.GetString("fourthLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        internal static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zur Übermittlung freigegeben.
        /// </summary>
        internal static string FS1 {
            get {
                return ResourceManager.GetString("FS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rückforderung.
        /// </summary>
        internal static string FS10 {
            get {
                return ResourceManager.GetString("FS10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stornierung anhängig.
        /// </summary>
        internal static string FS11 {
            get {
                return ResourceManager.GetString("FS11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation only.
        /// </summary>
        internal static string FS13 {
            get {
                return ResourceManager.GetString("FS13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to übermittelt.
        /// </summary>
        internal static string FS2 {
            get {
                return ResourceManager.GetString("FS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCT pending.
        /// </summary>
        internal static string FS21 {
            get {
                return ResourceManager.GetString("FS21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gesperrt.
        /// </summary>
        internal static string FS3 {
            get {
                return ResourceManager.GetString("FS3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bestätigt.
        /// </summary>
        internal static string FS4 {
            get {
                return ResourceManager.GetString("FS4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to korrektur erforderlich.
        /// </summary>
        internal static string FS5 {
            get {
                return ResourceManager.GetString("FS5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wartet auf Korrektur.
        /// </summary>
        internal static string FS6 {
            get {
                return ResourceManager.GetString("FS6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to überwiesen.
        /// </summary>
        internal static string FS7 {
            get {
                return ResourceManager.GetString("FS7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to storniert.
        /// </summary>
        internal static string FS8 {
            get {
                return ResourceManager.GetString("FS8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ablehnung durch Krankenkasse.
        /// </summary>
        internal static string FS9 {
            get {
                return ResourceManager.GetString("FS9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to further questions..
        /// </summary>
        internal static string furtherQuestions {
            get {
                return ResourceManager.GetString("furtherQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gültig bis.
        /// </summary>
        internal static string goodUntil {
            get {
                return ResourceManager.GetString("goodUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case (GPOS).
        /// </summary>
        internal static string GPOS {
            get {
                return ResourceManager.GetString("GPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi mm Team,.
        /// </summary>
        internal static string helloMM {
            get {
                return ResourceManager.GetString("helloMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.:.
        /// </summary>
        internal static string houseNr {
            get {
                return ResourceManager.GetString("houseNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 120.
        /// </summary>
        internal static string immidiatenotificationordernumber {
            get {
                return ResourceManager.GetString("immidiatenotificationordernumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 591104483.
        /// </summary>
        internal static string InterchangeSenderID {
            get {
                return ResourceManager.GetString("InterchangeSenderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 591104483.
        /// </summary>
        internal static string InterchangeSenderID1 {
            get {
                return ResourceManager.GetString("InterchangeSenderID1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrechnungen.
        /// </summary>
        internal static string InvoiceDocumentName {
            get {
                return ResourceManager.GetString("InvoiceDocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is invoice for doctor account .
        /// </summary>
        internal static string InvoiceForAccount {
            get {
                return ResourceManager.GetString("InvoiceForAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice from.
        /// </summary>
        internal static string invoiceFrom {
            get {
                return ResourceManager.GetString("invoiceFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice number:.
        /// </summary>
        internal static string invoiceNumber {
            get {
                return ResourceManager.GetString("invoiceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice period.
        /// </summary>
        internal static string InvoicePeriod {
            get {
                return ResourceManager.GetString("InvoicePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice period.
        /// </summary>
        internal static string InvoicePeriod2begin {
            get {
                return ResourceManager.GetString("InvoicePeriod2begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to im Überblick.
        /// </summary>
        internal static string InvoicePeriod2end {
            get {
                return ResourceManager.GetString("InvoicePeriod2end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to überwiesen.
        /// </summary>
        internal static string InvoiceRemitted {
            get {
                return ResourceManager.GetString("InvoiceRemitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum for this invoice period.
        /// </summary>
        internal static string InvoiceSumme {
            get {
                return ResourceManager.GetString("InvoiceSumme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokal..
        /// </summary>
        internal static string Localization {
            get {
                return ResourceManager.GetString("Localization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://lynxv3.b-op.com/mmdocconnect-doc/.
        /// </summary>
        internal static string LoginURLDocApp {
            get {
                return ResourceManager.GetString("LoginURLDocApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://lynxv3.b-op.com/mmdocconnect-mm/.
        /// </summary>
        internal static string LoginURLMM {
            get {
                return ResourceManager.GetString("LoginURLMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://lynxv3.b-op.com/mmdocconnect-mm/index.html#/treatment/.
        /// </summary>
        internal static string LoginURLMMTreatmentPage {
            get {
                return ResourceManager.GetString("LoginURLMMTreatmentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medios Connect / New Settlement Receipt.
        /// </summary>
        internal static string MailSubjectReceipt {
            get {
                return ResourceManager.GetString("MailSubjectReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mediosmanagement fee settlement program..
        /// </summary>
        internal static string mediosconnectsettlement {
            get {
                return ResourceManager.GetString("mediosconnectsettlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medios Connect .
        /// </summary>
        internal static string mmdocConnect {
            get {
                return ResourceManager.GetString("mmdocConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new settlement receipt is ready for you to download: .
        /// </summary>
        internal static string newSettlementForYou {
            get {
                return ResourceManager.GetString("newSettlementForYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medikament nicht bestellt .
        /// </summary>
        internal static string notOrdered {
            get {
                return ResourceManager.GetString("notOrdered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medikament bestellt.
        /// </summary>
        internal static string ordered {
            get {
                return ResourceManager.GetString("ordered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following order must be processed immediately:.
        /// </summary>
        internal static string orderurgent {
            get {
                return ResourceManager.GetString("orderurgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teilnahmeerklärung.
        /// </summary>
        internal static string participarionConsent {
            get {
                return ResourceManager.GetString("participarionConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        internal static string Patient {
            get {
                return ResourceManager.GetString("Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        internal static string PatientBirthDate {
            get {
                return ResourceManager.GetString("PatientBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance No..
        /// </summary>
        internal static string PatientInsuranceNumber {
            get {
                return ResourceManager.GetString("PatientInsuranceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period of invoice.
        /// </summary>
        internal static string PeriodOfInvoice {
            get {
                return ResourceManager.GetString("PeriodOfInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        internal static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please don’t hesitate to contact us in case of.
        /// </summary>
        internal static string pleaseContactUs {
            get {
                return ResourceManager.GetString("pleaseContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reclaimed.
        /// </summary>
        internal static string Reclaimed {
            get {
                return ResourceManager.GetString("Reclaimed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference number.
        /// </summary>
        internal static string referenceNumber {
            get {
                return ResourceManager.GetString("referenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best regards,.
        /// </summary>
        internal static string regards {
            get {
                return ResourceManager.GetString("regards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your initial password is:.
        /// </summary>
        internal static string secondLine {
            get {
                return ResourceManager.GetString("secondLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street:.
        /// </summary>
        internal static string street {
            get {
                return ResourceManager.GetString("street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum for.
        /// </summary>
        internal static string SumFor {
            get {
                return ResourceManager.GetString("SumFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum for deleted.
        /// </summary>
        internal static string SumForDeleted {
            get {
                return ResourceManager.GetString("SumForDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum for reclaimed.
        /// </summary>
        internal static string SumForReclaimed {
            get {
                return ResourceManager.GetString("SumForReclaimed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for being a loyal user of the.
        /// </summary>
        internal static string thankYouForBeinguser {
            get {
                return ResourceManager.GetString("thankYouForBeinguser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For security reasons we are recommending that you should change this password upon your first login..
        /// </summary>
        internal static string thirdLine {
            get {
                return ResourceManager.GetString("thirdLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medios Connect  / Eilbestellung.
        /// </summary>
        internal static string urgentOrder {
            get {
                return ResourceManager.GetString("urgentOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string WelcomePracticeName {
            get {
                return ResourceManager.GetString("WelcomePracticeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Medios Connect team..
        /// </summary>
        internal static string YourMediosConnectTeam {
            get {
                return ResourceManager.GetString("YourMediosConnectTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP:.
        /// </summary>
        internal static string zip {
            get {
                return ResourceManager.GetString("zip", resourceCulture);
            }
        }
    }
}
