INSERT INTO 
	hec_bil_billposition_billcodes
	(
		HEC_BIL_BillPosition_BillCodeID,
		PotentialCode_RefID,
		BillPosition_RefID,
		TotalPrice_IncludingTax,
		TotalPointValue,
		ValueMultiplicator,
		ValueMultiplicator_Comment,
		PointValue,
		UnitPrice_BeforeTax,
		UnitPrice_IncludingTax,
		TotalPrice_BeforeTax,
		IM_BillingCode,
		IM_BillingCode_Name,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@HEC_BIL_BillPosition_BillCodeID,
		@PotentialCode_RefID,
		@BillPosition_RefID,
		@TotalPrice_IncludingTax,
		@TotalPointValue,
		@ValueMultiplicator,
		@ValueMultiplicator_Comment,
		@PointValue,
		@UnitPrice_BeforeTax,
		@UnitPrice_IncludingTax,
		@TotalPrice_BeforeTax,
		@IM_BillingCode,
		@IM_BillingCode_Name,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)