INSERT INTO 
	cmn_ctr_contracts
	(
		CMN_CTR_ContractID,
		ContractName,
		ContractDescription,
		ValidFrom,
		ValidThrough,
		IsTerminated,
		IfTerminated_TerminationDate,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@CMN_CTR_ContractID,
		@ContractName,
		@ContractDescription,
		@ValidFrom,
		@ValidThrough,
		@IsTerminated,
		@IfTerminated_TerminationDate,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)