INSERT INTO 
	log_rcp_receipt_positions
	(
		LOG_RCP_Receipt_PositionID,
		ReceiptPositionITL,
		Receipt_Header_RefID,
		TotalQuantityTakenIntoStock,
		TotalQuantityFreeOfCharge,
		ExpectedPositionPrice,
		PriceOnSupplierBill,
		ReceiptPosition_Product_RefID,
		ReceiptPosition_ProductVariant_RefID,
		ReceiptPosition_ProductRelease_RefID,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@LOG_RCP_Receipt_PositionID,
		@ReceiptPositionITL,
		@Receipt_Header_RefID,
		@TotalQuantityTakenIntoStock,
		@TotalQuantityFreeOfCharge,
		@ExpectedPositionPrice,
		@PriceOnSupplierBill,
		@ReceiptPosition_Product_RefID,
		@ReceiptPosition_ProductVariant_RefID,
		@ReceiptPosition_ProductRelease_RefID,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)