INSERT INTO 
	hec_dia_potentialdiagnoses
	(
		HEC_DIA_PotentialDiagnosisID,
		PotentialDiagnosisITL,
		PotentialDiagnosis_Name_DictID,
		PotentialDiagnosis_Description_DictID,
		ICD10_Code,
		IsHospitalTransmissionIndicated,
		IsRefferalIndicated,
		IsAllergy,
		IsRefferalIndicated_PracticeType_RefID,
		DefaultTimeUntillDeactivation_InDays,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@HEC_DIA_PotentialDiagnosisID,
		@PotentialDiagnosisITL,
		@PotentialDiagnosis_Name,
		@PotentialDiagnosis_Description,
		@ICD10_Code,
		@IsHospitalTransmissionIndicated,
		@IsRefferalIndicated,
		@IsAllergy,
		@IsRefferalIndicated_PracticeType_RefID,
		@DefaultTimeUntillDeactivation_InDays,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)