INSERT INTO 
	cmn_str_sce_structurecalendarevents
	(
		CMN_STR_SCE_StructureCalendarEventID,
		CMN_CAL_Event_RefID,
		StructureEvent_Name_DictID,
		StructureEvent_Description_DictID,
		R_CalendarInstance_RefID,
		IsHavingCapacityRestriction,
		IfHavingCapacityRestriction_Restriction_RefID,
		StructureCalendarEvent_Type_RefID,
		IsShowingNotification,
		IsWorkingDayEvent,
		IsWorkingHalfDayEvent,
		IsNonWorkingDay,
		IsEvent_ImportedFromTemplate,
		IsBusinessDay,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@CMN_STR_SCE_StructureCalendarEventID,
		@CMN_CAL_Event_RefID,
		@StructureEvent_Name,
		@StructureEvent_Description,
		@R_CalendarInstance_RefID,
		@IsHavingCapacityRestriction,
		@IfHavingCapacityRestriction_Restriction_RefID,
		@StructureCalendarEvent_Type_RefID,
		@IsShowingNotification,
		@IsWorkingDayEvent,
		@IsWorkingHalfDayEvent,
		@IsNonWorkingDay,
		@IsEvent_ImportedFromTemplate,
		@IsBusinessDay,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)