INSERT INTO 
	cmn_trl_introductionrequests
	(
		CMN_TRL_IntroductionRequestID,
		IntroductionRequestITL,
		RequestingTenantCode,
		RequestedForTenantCode,
		IsApproved,
		IsRejected,
		IsPermanentlyRejected,
		PerformedBy_Account_RefID,
		PerformedDate,
		RejectedReason,
		RequestTitle,
		RequestComment,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@CMN_TRL_IntroductionRequestID,
		@IntroductionRequestITL,
		@RequestingTenantCode,
		@RequestedForTenantCode,
		@IsApproved,
		@IsRejected,
		@IsPermanentlyRejected,
		@PerformedBy_Account_RefID,
		@PerformedDate,
		@RejectedReason,
		@RequestTitle,
		@RequestComment,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)