INSERT INTO 
	pps_tsk_task_templates
	(
		PPS_TSK_Task_TemplateID,
		TaskTemplateNumber,
		TaskTemplateDisplayName,
		TaskTemplateName_DictID,
		TaskTemplateDescription_DictID,
		Duration_EstimatedMin_in_sec,
		Duration_Recommended_in_sec,
		Duration_EstimatedMax_in_sec,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@PPS_TSK_Task_TemplateID,
		@TaskTemplateNumber,
		@TaskTemplateDisplayName,
		@TaskTemplateName,
		@TaskTemplateDescription,
		@Duration_EstimatedMin_in_sec,
		@Duration_Recommended_in_sec,
		@Duration_EstimatedMax_in_sec,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)