SELECT *
FROM 
	hec_cmt_membership_potentialprocedurecatalogsubscriptions
WHERE 
	HEC_CMT_Membership_PotentialProcedureCatalogSubscriptionID = @HEC_CMT_Membership_PotentialProcedureCatalogSubscriptionID