INSERT INTO 
	ord_prc_expecteddelivery_2_procurementorderposition
	(
		AssignmentID,
		ORD_PRC_ExpectedDelivery_Position_RefID,
		ORD_PRC_ProcurementOrder_Position_RefID,
		AssignedQuantityFromProcurementOrderPosition,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@AssignmentID,
		@ORD_PRC_ExpectedDelivery_Position_RefID,
		@ORD_PRC_ProcurementOrder_Position_RefID,
		@AssignedQuantityFromProcurementOrderPosition,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)