INSERT INTO 
	res_bld_basement_2_basementtype
	(
		AssignmentID,
		RES_BLD_Basement_RefID,
		RES_BLD_Basement_Type_RefID,
		Comment,
		Creation_Timestamp,
		IsDeleted,
		Tenant_RefID
	)
VALUES 
	(
		@AssignmentID,
		@RES_BLD_Basement_RefID,
		@RES_BLD_Basement_Type_RefID,
		@Comment,
		@Creation_Timestamp,
		@IsDeleted,
		@Tenant_RefID
	)