INSERT INTO 
	cmn_pro_product_variants
	(
		CMN_PRO_Product_VariantID,
		ProductVariantITL,
		VariantName_DictID,
		CMN_PRO_Product_RefID,
		ProductVariant_DocumentationStructure_RefID,
		IsStandardProductVariant,
		IsImportedFromExternalCatalog,
		IsProductAvailableForOrdering,
		IsObsolete,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@CMN_PRO_Product_VariantID,
		@ProductVariantITL,
		@VariantName,
		@CMN_PRO_Product_RefID,
		@ProductVariant_DocumentationStructure_RefID,
		@IsStandardProductVariant,
		@IsImportedFromExternalCatalog,
		@IsProductAvailableForOrdering,
		@IsObsolete,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)