INSERT INTO 
	hec_pro_component_productapplications
	(
		HEC_PRO_Component_ProductApplicationID,
		HEC_PRO_Component_RefID,
		SequenceNumber,
		IsPreparationNeccessaryBeforeApplication,
		ApplicationMatterState,
		ApplicationKindState,
		ProductApplicationLocation,
		ProductApplicationMethod,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@HEC_PRO_Component_ProductApplicationID,
		@HEC_PRO_Component_RefID,
		@SequenceNumber,
		@IsPreparationNeccessaryBeforeApplication,
		@ApplicationMatterState,
		@ApplicationKindState,
		@ProductApplicationLocation,
		@ProductApplicationMethod,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)