SELECT *
FROM 
	hec_act_plannedaction_potentialprocedure_requiredproduct
WHERE 
	HEC_ACT_PlannedAction_PotentialProcedure_RequiredProductID = @HEC_ACT_PlannedAction_PotentialProcedure_RequiredProductID