INSERT INTO 
	bil_billposition_2_product
	(
		AssignmentID,
		BIL_BillPosition_RefID,
		CMN_PRO_Product_RefID,
		CMN_PRO_Product_Variant_RefID,
		CMN_PRO_Product_Release_RefID,
		LOG_ProductTrackingInstance_RefID,
		Quantity,
		Comment,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@AssignmentID,
		@BIL_BillPosition_RefID,
		@CMN_PRO_Product_RefID,
		@CMN_PRO_Product_Variant_RefID,
		@CMN_PRO_Product_Release_RefID,
		@LOG_ProductTrackingInstance_RefID,
		@Quantity,
		@Comment,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)