INSERT INTO 
	ord_cuo_customerorderreturn_headers
	(
		ORD_CUO_CustomerOrderReturn_HeaderID,
		Customer_RefID,
		CorrespondingReceiptHeader_RefID,
		DateOfCustomerReturn,
		CustomerOrderReturnNumber,
		Currency_RefID,
		TotalValueBeforeTax,
		Customer_BillingAddressUCD_RefID,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@ORD_CUO_CustomerOrderReturn_HeaderID,
		@Customer_RefID,
		@CorrespondingReceiptHeader_RefID,
		@DateOfCustomerReturn,
		@CustomerOrderReturnNumber,
		@Currency_RefID,
		@TotalValueBeforeTax,
		@Customer_BillingAddressUCD_RefID,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)