
Select
  pps_tsk_bok_deviceresources.PPS_DEV_Device_Instance_RefID,
  pps_tsk_bok_staffresources.CMN_BPT_EMP_Employee_RefID,
  pps_tsk_bok_deviceresources.PPS_TSK_BOK_DeviceResourceID,
  pps_tsk_bok_staffresources.PPS_TSK_BOK_StaffResourceID,
  pps_tsk_bok_staffresources.CreatedFor_TaskTemplateRequiredStaff_RefID,
  pps_tsk_bok_availableresourcecombinations.PPS_TSK_BOK_AvailableResourceCombinationID
From
  pps_tsk_bok_availableresourcecombinations Left Join
  pps_tsk_bok_deviceresources
    On
    pps_tsk_bok_availableresourcecombinations.PPS_TSK_BOK_AvailableResourceCombinationID = pps_tsk_bok_deviceresources.AvailableResourceCombination_RefID And pps_tsk_bok_availableresourcecombinations.IsDeleted = 0 Left Join
  pps_tsk_bok_staffresources
    On
    pps_tsk_bok_availableresourcecombinations.PPS_TSK_BOK_AvailableResourceCombinationID = pps_tsk_bok_staffresources.AvailableResourceCombination_RefID And pps_tsk_bok_staffresources.IsDeleted = 0
Where
  (pps_tsk_bok_availableresourcecombinations.IsAvailable = 0 or pps_tsk_bok_availableresourcecombinations.PPS_TSK_BOK_AvailableResourceCombinationID = @CombinationID) And
  pps_tsk_bok_availableresourcecombinations.BookableTimeSlot_RefID = @SlotID And
  pps_tsk_bok_availableresourcecombinations.Tenant_RefID = @TenantID And
  pps_tsk_bok_availableresourcecombinations.IsDeleted = 0
  