INSERT INTO 
	cmn_pro_prc_warehousespecific_averageprocurementprices
	(
		CMN_PRO_PRC_WarehouseSpecific_AverageProcurementPriceID,
		CurrentAverageProcurement_Price_RefID,
		LOG_WRH_Warehouse_RefID,
		Product_RefID,
		Product_Variant_RefID,
		IsCurrentAveragePrice,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@CMN_PRO_PRC_WarehouseSpecific_AverageProcurementPriceID,
		@CurrentAverageProcurement_Price_RefID,
		@LOG_WRH_Warehouse_RefID,
		@Product_RefID,
		@Product_Variant_RefID,
		@IsCurrentAveragePrice,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)