INSERT INTO 
	acc_dun_dunningprocess_history
	(
		ACC_DUN_DunningProcess_HistoryID,
		ACC_DUN_DunningProcess_RefID,
		ACC_DUN_Dunning_Level_RefID,
		DunningProcessFee_IncludingThisDunningLevel,
		IsCurrentStep,
		TriggeredBy_BusinessParticipant_RefID,
		TriggeredAt_Date,
		IsSentToCustomer,
		SendToCustomerBy_BusinessParticipant_RefID,
		SendToCustomerAt_Date,
		Comment,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@ACC_DUN_DunningProcess_HistoryID,
		@ACC_DUN_DunningProcess_RefID,
		@ACC_DUN_Dunning_Level_RefID,
		@DunningProcessFee_IncludingThisDunningLevel,
		@IsCurrentStep,
		@TriggeredBy_BusinessParticipant_RefID,
		@TriggeredAt_Date,
		@IsSentToCustomer,
		@SendToCustomerBy_BusinessParticipant_RefID,
		@SendToCustomerAt_Date,
		@Comment,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)