INSERT INTO 
	ord_cuo_customerorder_positions
	(
		ORD_CUO_CustomerOrder_PositionID,
		CustomerProcurementOrderPositionITL,
		CustomerOrder_Header_RefID,
		Position_OrdinalNumber,
		Position_Quantity,
		Position_ValuePerUnit,
		Position_ValueTotal,
		Position_Comment,
		Position_Description,
		Position_Unit_RefID,
		Position_RequestedDateOfDelivery,
		CMN_PRO_Product_Variant_RefID,
		CMN_PRO_Product_RefID,
		CMN_PRO_Product_Release_RefID,
		IsProductReplacementAllowed,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@ORD_CUO_CustomerOrder_PositionID,
		@CustomerProcurementOrderPositionITL,
		@CustomerOrder_Header_RefID,
		@Position_OrdinalNumber,
		@Position_Quantity,
		@Position_ValuePerUnit,
		@Position_ValueTotal,
		@Position_Comment,
		@Position_Description,
		@Position_Unit_RefID,
		@Position_RequestedDateOfDelivery,
		@CMN_PRO_Product_Variant_RefID,
		@CMN_PRO_Product_RefID,
		@CMN_PRO_Product_Release_RefID,
		@IsProductReplacementAllowed,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)