

var translationsDE = {

    //***LABELS GLOBAL***//
    LABEL_NEXT_EDIFACT_NUMBER: 'Next EDIFACT number',
    LABEL_CONTRACT_CHARACTERISTIC_ID: 'Characteristic ID',
    LABEL_EDIFACT_TYPE: 'EDIFACT type',
    LABEL_ENCRYPT_EDIFACT: 'Encrypt EDIFACT',
    LABEL_SHOULD_DOWNLOAD_REPORT_UPON_SUBMISSION: 'Übermittlungsbestätigungen gesammelt herunterladen',
    LABEL_PRESS_ENTER_TO_SEARCH: 'aktivieren von: Zum Suchen Enter drücken',
    LABEL_CONTRACT_TYPE: 'Contract type',
    LABEL_MESSAGE_TYPE: 'Message type',
    LABEL_MERGE_HIPS: 'Merge for all HIPs',
    LABEL_USE_K_FOR_CORRECTION: 'Use K for correction',
    LABEL_IK_NUMBER: 'Hauptverwaltung',

    LABEL_YOUR_SESSION_HAS_EXPIRED: 'Ihre Sitzung ist abgelaufen. Bitte drücken Sie OK, um die Abmeldung.',
    LABEL_NOTICE: 'Beachten',

    LABEL_404: 'Zugriff nicht gestattet.',
    LABEL_NOT_IMPLEMENTED: 'Diese Funktion ist noch nicht implementiert, Bitte entschuldigen Sie die Unannehmlichkeiten. Vielen Dank für Ihre Geduld.',
    LABEL_TREATMENT: 'Behandlungen',
    LABEL_ORDERS: 'Bestellungen',
    LABEL_PATIENT: 'Patienten',
    LABEL_DOCTOR: 'Ärzte',
    LABEL_ARCHIVE: 'Archiv',
    LABEL_MASTERDATA: 'Stammdaten',
    LABEL_DRUGS: 'Medikamente',
    LABEL_DIAGNOSES: 'Diagnosen',
    LABEL_HEALTHINSURANCES: 'Krankenkassen',
    LABEL_CONTRACT: 'Verträge',
    LABEL_PHARMACY: 'Apotheken',
    LABEL_EMPLOYEE: 'Mitarbeiter',
    LABEL_MYACCOUNT: 'Mein Account',
    LABEL_SETTINGSGLOBAL: 'Einstellungen',
    LABEL_LOGOUT: 'Abmelden',
    LABEL_SOMETHING_WENT_WRONG: "Irgendwas ist schiefgegangen.",
    LABEL_OPERATION_SUCCESSFUL: "Operation war erfolgreich.",
    LABEL_NO_RECORDS_FOUND: 'Keine Datensätze gefunden.',
    LABEL_CANCEL: 'Abbrechen',
    LABEL_PASSWORD: 'Passwort',
    LABEL_CHANGE: 'Andern',
    LABEL_CONFIRM_PASSWORD: 'Wie lautet Ihr Passwort?',
    LABEL_PLEASE_ENTER_PASSWORD: 'Bitte geben Sie Ihr Passwort ein um die Vorgänge zur Abrechnung frei zu geben.',
    LABEL_DOCTOR_IN_CHARGE: 'Behandelnder Arzt',
    LABEL_DATE_PLACEHOLDER: 'TT.MM.JJJJ',
    LABEL_DATE_TIME: 'Datum, Zeit',
    LABEL_DATE: 'Datum',
    LABEL_DATE_FROM: 'von',
    LABEL_DATE_TO: 'bis',
    LABEL_SEARCH: 'Suche...',

    LABEL_RESET_PASSWORD: 'Passwort zurücksetzen',
    LABEL_NEW_PASSWORD_GENERATE: 'Neues Passwort generieren',
    LABEL_DEFINE_NEW_PASSWORD: 'Neues Passwort erstellen',
    LABEL_REPEAT_NEW_PASSWORD: 'Neues Passwort wiederholen',
    LABEL_CHANGE_PASSWORD_SURE1: 'Wollen Sie jetzt wirklich das Passwort für den ',
    LABEL_CHANGE_PASSWORD_SURE2: ' Account ändern?',
    LABEL_PASSWORD_CHANGED: 'Passwort erfolgreich geändert',
    LABEL_WELCOME_EMAIl1: 'Eine E-Mail mit dem neuen Passwort wird an den ',
    LABEL_WELCOME_EMAIl2: ' versendet.',
    LABEL_CHANGES_SAVED: 'Änderung gespeichert.',

    LABEL_CHANGE_NOW: 'Jetzt ändern',

    LABEL_WHAT_IS_YOUR_PASSWORD: 'Wie lautet Ihr Passwort?',
    LABEL_PLEASE_ENTER_PASSWORD: 'Bitte geben Sie Ihr Passwort ein',
    LABEL_CREDENTIALS_NOT_VERIFIED: 'Bitte überprüfen Sie Ihre Zugangsdaten und versuchen Sie es nochmal.',
    LABEL_MERGE_DOCTOR_TITLE: 'Merge doctor',
    LABEL_LANR_NOT_FOUND: 'No doctor found with entered LANR in the selected practice. Continue without merging?',
    LABEL_MERGE_DOCTOR_MESSAGE_SINGLE: 'The specified LANR corresponds to doctor {{doctor}} from {{practice}}. Would you like to merge temporary doctor into this doctor record?',
    LABEL_MERGE_DOCTOR_MESSAGE_MULTIPLE: 'The specified LANR corresponds to these doctors. Would you like to merge temporary doctor into any of these doctor records?',
    LABEL_MERGE_DOCTOR_DESCRIPTION: '{{ doctor }} from {{ practice }}',
    LABEL_DOCTOR_MERGED: 'Doctor merged successfully.',

    LABEL_ADD_USER: 'Mitarbeiter hinzufügen',
    LABEL_USER_ACCOUNT: 'Account für Mitarbeiter anlegen',
    LABEL_ADMIN_ACCOUNT: 'Admin Account',
    LABEL_USER_ADDED: 'New User added',
    LABEL_MR: 'Herr',
    LABEL_MIS: 'Frau',
    LABEL_NAME: 'Name',
    LABEL_DEFAULT_EMAIL: 'Standard-Benachrichtigungsadresse',
    LABEL_ORDER_INTERVAL: 'Intervall für Bestellbenachrichtigung',
    LABEL_MINUTES: 'Minuten',
    LABEL_IN: 'in',
    LABEL_IMMEDIATE_ORDER_INTERVAL: 'Sofortbenachrichtigung bei Bestellungen ',
    LABEL_CANCELSETTINGS: 'Änderungen verwerfen',
    LABEL_PLEASE_PASSWORD: 'Bitte geben sie ihr Passwort ein.',
    LABEL_INVALID_NUMBER_ORDER: 'Ungültiges Intervall für Bestellbenachrichtigung - Minuten (nummerisch).',
    LABEL_INVALID_NUMBER_IMORDER: 'Ungültiges Sofortbenachrichtigung bei Bestellungen in - Minuten (nummerisch).',
    LABEL_APP_SETTINGS_SAVED: 'New company settings saved',
    LABEL_WELCOMEEMAILWILLBESENTTOUSER: 'Eine Willkommens-E-Mail wird an den Mitarbeiter versendet',
    LABEL_NON_COOPERATTING_PHARMACY: 'Ich möchte eine andere Praxis angeben',
    BUTTON_SAVESETTINGS: 'Änderung speichern',
    BUTTON_CANCELSETTINGS: 'Änderungen verwerfen',

    //dashboard
    LABEL_RESPONSE: 'Rückmeldungen',
    LABEL_VOLUME: 'Volumen',
    LABEL_CASES: 'Vorgänge',
    LABEL_OLDEST_CASE: 'Ältester Vorgang',
    BUTTON_IMPORT_HIP_RESPONSE: 'Rückmeldung der Krankenkasse importieren',
    LABEL_PAYMENT: 'Auszahlung',
    LABEL_STATUS_CHANGE: 'Statuswechsel',
    BUTTON_SEND_PAYMENT_FILE_TO_CONTROLLING: 'Auszahlung an Buchhaltung übermitteln',
    LABEL_ERROR_CORRECTIONS: 'Fehlerbearbeitung',
    BUTTON_SHOW_ALL_ERRONEOUS_CASES: 'Alle fehlerhaften Vorgänge zeigen',
    LABEL_CASES_ON_HOLD: 'Gesperrte Vorgänge',
    BUTTON_SHOW_ALL_ON_HOLD_CASES: 'Alle gesperrten Vorgänge zeigen',
    LABEL_SETTLEMENT: 'Abrechnungen',
    BUTTON_SUBMIT_SETLLEMENT_TO_HIP: 'Abrechnung an Krankenkasse übermitteln',
    LABEL_DRUG_ORDER: 'Bestellungen annehmen',
    BUTTON_EXPORT_ALL_ORDERS: 'Alle Bestellungen exportieren',
    LABEL_DRUG_ORDERS_SHIPPED: 'Bestellungen ausliefern',
    BUTTON_IMPORT_ORDERS: 'Bestellungen importieren',
    LABEL_POPUP_STERIBASE: 'Bestellung akzeptiert. Export zu Steribase noch nicht unterstützt.',
    LABEL_NO_AVAILABLE_ITEMS: 'There are no eligible items for this operation',
    LABEL_REVIEW_TEMPORARY_DOCTORS: 'Neue Nachsorgeärzte überprüfen',
    LABEL_AMMOUNT: 'Anzahl',
    LABEL_OLDEST_CHANGE: 'Ältester Änderung',
    LABEL_LAST_NAME_FIRST_NAME: 'Nachname, Vorname',
    LABEL_EMAIL_ADDRESS: 'E-Mail',
    LABEL_PHONE_NUMBER: 'Telefonnummer',
    LABEL_PHONE_FAX: 'Telefon, Fax',
    LABEL_ADMIN: 'Admin',
    LABEL_ADMIN_USER_INFO: 'There must be at least one active admin user. If you want to revoke admin rights to this user, please grant admin rights to another user first',
    LABEL_USER_EDITED: 'User edited',
    LABEL_RECEIVE_NOTIFICATION: 'Benachrichtigungen erhalten',
    LABEL_MY_ACCOUNT: 'Mein Account',
    LABEL_MY_CONTACT_DETAILS: 'Meine Kontaktdaten',
    LABEL_MY_ACCESS_DETAILS: 'Meine Zugangsdaten',
    LABEL_MY_ACCOUNT_EDITED: 'Account bearbeitet',
    LABEL_CUSTOMER_NUMBER: 'Debitorennummer',
    LABEL_INVALID_CUSTOMER_NUMBER_LENGTH: 'Ungültiges Debitorennummer (Länge)',
    LABEL_INVALID_CUSTOMER_NUMBER_FORMAT: 'Ungültiges Debitorennummer (nummerisch)',
    LABEL_COMPLETE_ORDER_REPORT_CREATED: 'Complete orders report created',
    BUTTON_CREATE_COMPLETE_ORDERS_REPORT: 'Create complete orders report',
    LABEL_COMPLETE_ORDERS_REPORT: 'Complete orders report',
    LABEL_IS_CERTIFICATED_FOR_OCT: 'Is certified for OCT',
    //archive
    LABEL_TYPE: 'Art',
    LABEL_RECIPIENT: 'Empfänger',
    LABEL_DESCRIPTION: 'Beschreibung',
    BUTTON_DOWNLOAD: 'Herunterladen',
    LABEL_EDIFACT: 'EDIFACT Export',
    LABEL_DATEV: 'DATEV Export',
    LABEL_HIPIMPORT: 'KV Import',
    LABEL_HIPERROR: 'KV Fehler',
    LABEL_STERIBASE: 'Steribase',
    LABEL_ADRESSE: 'Adresse',

    //patient
    LAEL_OP_DOCTOR_PRACTICE: 'OP-Arzt/Praxis',
    LAEL_AC_DOCTOR_PRACTICE: 'Nachsorgearzt/Praxis',
    LABEL_YES: 'ja',
    LABEL_NEIN: 'nein',

    LABEL_WARNING: 'Warnung!',
    aktiv: 'Aktiv',
    inaktiv: 'Inaktiv',
    temp: 'Temporär',

    LABEL_NO_CASES_ELIGIBLE_FOR_STATUS_CHANGE: 'No cases eligible for status change.',

    // contracts
    LABEL_CONTRACT_NAME: 'Vertrag',
    LABEL_CONTRACT_TITLE: 'Vertragsname',
    LABEL_VALID_FROM: 'Gültig von',
    LABEL_VALID_THROUGH: 'Gültig bis',
    LABEL_HIP_NAMES: 'Krankenkassen',
    LABEL_HIP_NAME: 'Krankenkasse',
    LABEL_GPOSES: 'Gebührenpositionen',
    LABEL_DUE_DATES: 'Fristen',
    LABEL_CONTRACT_SAVED: 'Neuer Vertrag gespeichert.',
    LABEL_GPOS_NUMBER: 'GPOS-Nr.',
    LABEL_GPOS_NAME: 'GPOS',
    LABEL_ADD_GPOS: 'GPOS hinzufügen',
    LABEL_ADD_GPOS_EXPANDED: 'Gebührenposition hinzufügen',
    LABEL_GPOS: 'Gebührenposition',
    LABEL_CASE_ONE: 'Vorgang',
    LABEL_INJECTIONS_FROM: 'von Injektions-Nr.',
    LABEL_INJECTIONS_TO: 'bis Injektions-Nr.',
    LABEL_FEE_IN_EUR: 'Vergütung in €',
    LABEL_MANAGEMENT_FEE_IN_EUR: 'Managementgebühr in €',
    LABEL_WAIVE_WITH_ORDER: 'erlassen bei Bestellung ',
    LABEL_OP_CASE_TYPE: 'OP',
    LABEL_AC_CASE_TYPE: 'Nachsorge',
    LABEL_PRE_EXAMINATION_CASE_TYPE: 'OCT',
    LABEL_GPOS_ADDED: 'Neuer Gebührenposition gespeichert.',
    LABEL_ADD: 'Hinzufügen',
    LABEL_DRUG_ALREADY_SELECTED: 'Selected drug is already added to this contract.',
    LABEL_DIAGNOSE_ALREADY_SELECTED: 'Selected diagnose is already added to this contract.',
    LABEL_HIP_ALREADY_SELECTED: 'Selected health insurance provider is already added to this contract.',
    LABEL_DOCTOR_ALREADY_SELECTED: 'Selected doctor already has a participation consent on this contract.',
    LABEL_DIAGNOSE: 'Diagnose',
    LABEL_ICD10_NUMBER: 'ICD10 Nummer',
    LABEL_HIP_NUMBER: 'Krankenkasse-Nr.',
    LABEL_ADD_CHANGE_DUE_DATES: 'Fristen einstellen',
    LABEL_PARTICIPATION_CONSENT_DURATION: 'Gültigkeit der Teilnahmeerklärung',
    LABEL_DAYS_BETWEEN_SURGERY_AND_AFTERCARE: 'Anzahl der Tage zwischen OP und Nachsorge',
    LABEL_NUMBER_OF_DAYS_BETWEEN_SURGERY_AND_SETTLEMENT_CLAIM: 'Anzahl der Tage zwischen Behandlung und Abrechnung',
    LABEL_NUMBER_OF_DAYS_BETWEEN_SUBMISSION_TO_HIP_AND_REPLY: 'Anzahl der Tage zwischen Abrechnung und Rückmeldung Krankenkasse',
    LABEL_NUMBER_OF_DAYS_BETWEEN_RESPONSE_AND_PAYMENT: 'Anzahl der Tage zwischen Rückmeldung und Auszahlung',
    LABEL_NUMBER_OF_DAYS_BETWEEN_HIP_RESPONSE_AND_REJECTION: 'Anzahl der Tage zwischen Rückmeldung und Ablehnung durch Krankenkasse',
    LABEL_MONTHS: 'Monate',
    LABEL_DAYS: 'Tage',
    LABEL_REMOVE_DIAGNOSE_TITLE: 'Remove diagnose from contract',
    LABEL_REMOVE_DRUG_TITLE: 'Remove drug from contract',
    LABEL_REMOVE_HIP_TITLE: 'Remove HIP from contract',
    LABEL_REMOVE_DOCTOR_TITLE: 'Remove doctor from contract',
    LABEL_REMOVE_GPOS_TITLE: 'Remove GPOS from contract',
    LABEL_REMOVE_DATA_FROM_CONTRACT_CONTENT: 'Are you sure you want to remove {{eligible}} from this contract?',
    LABEL_REMOVE_FROM_CONTRACT: 'Remove from contract',
    LABEL_FEE_VALUE_MUST_BE_NUMBER: 'Fee value must be a number.',
    LABEL_MANAGEMET_FEE_VALUE_MUST_BE_NUMBER: 'Management fee value must be a number.',
    LABEL_FROM_INJECTION_MUST_BE_NUMBER: 'Injections from must be a number.',
    LABEL_GPOS_NUMBER_NOT_UNIQUE: 'Gpos number [{{number}}] already exists.',
    LABEL_FROM_INJECTIONS_NOT_UNIQUE: 'From injections number [{{number}}] already exists.',
    LABEL_CONTRACT_COPIED: 'Vertrag kopiert.',
    LABEL_VALID_FROM_INVALID_DATE: 'Ungültiges Datum (Gültig von)',
    LABEL_VALID_THROUGH_INVALID_DATE: 'Ungültiges Datum (Gültig bis)',
    LABEL_INVALID_DATE: 'Ungültiges Datum',
    LABEL_PARTICIPATION_CONSENT_INVALID: 'Ungültiges Nummer (Gültigkeit der Teilnahmeerklärung)',
    LABEL_DAYS_BETWEEN_SURGERY_AND_AFTERCARE_INVALID: 'Ungültiges Nummer (Anzahl der Tage zwischen OP und Nachsorge)',
    LABEL_DAYS_BETWEEN_SURGERY_AND_SETTLEMENT_INVALID: 'Ungültiges Nummer (Anzahl der Tage zwischen Behandlung und Abrechnung)',
    LABEL_DAYS_BETWEEN_SUBMISSION_AND_REPLY_INVALID: 'Ungültiges Nummer (Anzahl der Tage zwischen Abrechnung und Rückmeldung Krankenkasse)',
    LABEL_DAYS_BETWEEN_RESPONSE_AND_PAYMENT_INVALID: 'Ungültiges Nummer (Anzahl der Tage zwischen Rückmeldung und Auszahlung)',
    LABEL_DAYS_BETWEEN_RESPONSE_AND_REJECTION_INVALID: 'Ungültiges Nummer (Anzahl der Tage zwischen Rückmeldung und Ablehnung durch Krankenkasse)',
    LABEL_OCT_MAX_NUMBER_OF_DAYS_BEFORE_OP: 'Before the OP, the OCT can be submitted for ',
    LABEL_OP_RENEWS_PATIENT_CONSENT: 'Teilnahmeerklärung erneuert sich bei einer OP innerhalb der Gültigkeit automatisch.',
    LABEL_OCT_MAX_DAYS_BEFORE_OP_INVALID: 'Ungültiges Nummer (Number of days OCT can take place before OP)',
    LABEL_DOCTOR_NEEDS_CERTIFICATION: 'Doctor needs OCT certification',
    LABEL_USE_SETTLEMNT_YEAR: 'Use settlement year instead of treatment year',
    LABEL_OCT_VALID_FROM_INVALID: 'OCT valid from date is invalid',

    LABEL_COPY_CONTRACT_TITLE: 'Vertrag kopieren',
    LABEL_COPY_CONTRACT_CONTENT: '{{eligible}} kopieren?',
    LABEL_VALID_THROUGH_DATE_BEFORE_VALID_FROM_DATE: 'Valid through date must be greater than valid from date.',
    LABEL_ELIPSIS_MORE: '+ {{number}} weitere',
    LABEL_BEVACIZUMAB_CASE_TYPE: 'Zusatzposition Bevacizumab',
    LABEL_MANAGEMENT_CASE_TYPE: 'Wartezeitenmanagement',
    LABEL_START_DATE_MANDATORY: 'Contract consent start date not entered.',
    LABEL_CONTRACT_DATES_OVERLAPS: 'Für diesen Zeitraum liegt schon ein aktiver Vertrag {{consentContractName}} ( {{consentValidFrom}} - {{consentValidThrough}} ) vor.',
    LABEL_CONSENT_END_DATE_NOT_VALID: 'Consent end date must be between {{consentTimeframe}}',
    LABEL_CONTRACT_START_DATE_NOT_ENTERED: 'Contract start date not entered.',
    LABEL_CONSENT_START_NOT_IN_CONTRACT_VALIDITY_TIMESPAN: 'Selected consent start date doesn\'t fall into contract validity timespan.',
    LABEL_CONSENT_TIMESPAN: 'Consent timespan',

    LABEL_CONTRACT_TYPE_7: 'type 7',
    LABEL_CONTRACT_TYPE_8: 'type 8',
    LABEL_EDIFACT_TYPE_3: '3',
    LABEL_EDIFACT_TYPE_4: '4',
    LABEL_MESSAGE_TYPE_DIR73C: 'DIR73C',
    LABEL_MESSAGE_TYPE_DIR140: 'DIR140',
    LABEL_NONE: 'Keine',

    // PRE-EXAMINATION LABELS
    LABEL_MAX_NUMBER_OF_PREEXAMINATIONS_PREFIX: 'Max',
    LABEL_MAX_NUMBER_OF_PREEXAMINATIONS_SUFFIX: 'OCT\'s per localization in',
    LABEL_PREEXAMINATION_MAX_VALUE_INVALID: 'Ungültiges Nummer (Max number of pre-examinations)',
    LABEL_PREEXAMINATION_DAYS_VALUE_INVALID: 'Ungültiges Nummer (Pre-examinations days constraint)',
    LABEL_PREEXAMINATIONS: 'OCT',

    LABEL_CONTACT: 'Ansprechpartner',
    LABEL_PREFERRED_PHARMACY: 'Bevorzugte Apotheke',
    LABEL_QUICK_ORDER_VERWNDEN: 'Quick-Order verwnden (Praxisadresse wird als Lieferadresse verwendet)',
    LABEL_QUICK_ORDER_GRACE_PERIOD: 'Passwort Grace-Periode bei Quick-Order verwender',
    LABEL_OTHER_OPTIONS: 'Andere Einstellungen',

    TOOLTIP_QUICK_ORDER_MSG: 'Um die Quick-Order zu nutzen, wählen Sie bitte eine bevorzugte Apotheke aus und geben Sie Praxisadresse, Ansprechpartner, Standardlieferdatum und Standardlieferzeit an.',

    //***BUTTONS GLOBAL***//
    BUTTON_404: 'Zurück zur Hauptseite',
    BUTTON_SHOW_NEW_DOCTORS: 'Neue Nachsorgeärzte anzeigen',

    BUTTON_CONFIRM: 'BESTÄTIGEN',
    BUTTON_CONFIRM_NORMALCASE: 'Bestätigen',
    BUTTON_YES: 'Ja',
    BUTTON_NO: 'Nein',
    BUTTON_ADD_NEW_USER: 'Mitarbeiter hinzufügen',
    BUTTON_COPY: 'Kopieren',
    BUTTON_GO_TO_PATIENT_DETAILS: 'Patientenakte aufrufen',
};

var translationsEN = {
    //***LABELS GLOBAL***//
    LABEL_YOUR_SESSION_HAS_EXPIRED: 'Your session has expired. Please press OK to logout.',
    LABEL_NOTICE: 'Notice',

    LABEL_404: 'Forbidden page.',
    LABEL_NOT_IMPLEMENTED: 'Sorry, this functionality is not implemented yet. Thanks for your patience.',
    LABEL_TREATMENT: 'Treatment',
    LABEL_ORDERS: 'Orders',
    LABEL_PATIENT: 'Patient',
    LABEL_DOCTOR: 'Doctors',
    LABEL_ARCHIVE: 'Archive',
    LABEL_MASTERDATA: 'Master data',
    LABEL_DRUGS: 'Medication',
    LABEL_DIAGNOSES: 'Diagnoses',
    LABEL_HEALTHINSURANCES: 'Health insurances',
    LABEL_CONTRACT: 'Contract',
    LABEL_PHARMACY: 'Pharmacy',
    LABEL_EMPLOYEE: 'Employee',
    LABEL_MYACCOUNT: 'My account',
    LABEL_SETTINGSGLOBAL: 'Settings',
    LABEL_LOGOUT: 'Logout',
    LABEL_SOMETHING_WENT_WRONG: "Something went wrong.",
    LABEL_OPERATION_SUCCESSFUL: "Operation successful.",
    LABEL_NO_RECORDS_FOUND: 'No records found.',
    LABEL_CANCEL: 'Cancel',
    LABEL_PASSWORD: 'Password',
    LABEL_CHANGE: 'Change',
    LABEL_CONFIRM_PASSWORD: 'What is your password?',
    LABEL_PLEASE_ENTER_PASSWORD: 'Please enter your password to enter the billing operations.',
    LABEL_DOCTOR_IN_CHARGE: 'Doctor in charge',
    LABEL_DATE_PLACEHOLDER: 'MM.DD.YYYY',
    LABEL_DATE_TIME: 'Date, Time',
    LABEL_DATE: 'Date',
    LABEL_DATE_FROM: 'from',
    LABEL_DATE_TO: 'to',
    LABEL_SEARCH: 'Search...',
    LABEL_PRESS_ENTER_TO_SEARCH: 'Press enter to search',

    LABEL_RESET_PASSWORD: 'Reset Password',
    LABEL_NEW_PASSWORD_GENERATE: 'Generate Password',
    LABEL_DEFINE_NEW_PASSWORD: 'Define Password',
    LABEL_REPEAT_NEW_PASSWORD: 'Repeat Password',
    LABEL_CHANGE_PASSWORD_SURE1: 'Do you really want to change the password for the ',
    LABEL_CHANGE_PASSWORD_SURE2: ' account now?',
    LABEL_CHANGE_NOW: 'Change now (Save)',
    LABEL_PASSWORD_CHANGED: 'Password successfully changed.',
    LABEL_WELCOME_EMAIl1: 'A welcome email will be send to the ',
    LABEL_WELCOME_EMAIl2: ' account.',
    LABEL_CHANGES_SAVED: 'Changes saved.',
    LABEL_MERGE_DOCTOR_MESSAGE_SINGLE: 'The specified LANR corresponds to doctor {{doctor}} from {{practice}}. Would you like to merge temporary doctor into this doctor record?',
    LABEL_MERGE_DOCTOR_MESSAGE_MULTIPLE: 'The specified LANR corresponds to these doctors. Would you like to merge temporary doctor into any of these doctor records?',
    LABEL_MERGE_DOCTOR_DESCRIPTION: '{{ doctor }} from {{ practice }}',
    LABEL_DOCTOR_MERGED: 'Doctor merged successfully.',

    LABEL_ADD_USER: 'Add user',
    LABEL_USER_ACCOUNT: 'Accountfor user',
    LABEL_ADMIN_ACCOUNT: 'Admin Account',
    LABEL_ADMIN_USER_INFO: 'There must be at least one active admin user. If you want to revoke admin rights to this user, please grant admin rights to another user first',
    LABEL_USER_EDITED: 'User edited',
    LABEL_RECEIVE_NOTIFICATION: 'Receive Notifications',
    LABEL_MY_ACCOUNT: 'My Account',
    LABEL_MY_CONTACT_DETAILS: 'My contact details',
    LABEL_MY_ACCESS_DETAILS: 'My Access details',
    LABEL_MY_ACCOUNT_EDITED: 'Account edited',
    //dashboard
    LABEL_RESPONSE: 'Response',
    LABEL_VOLUME: 'Volume',
    LABEL_CASES: 'Cases',
    LABEL_OLDEST_CASE: 'Oldest Case',
    BUTTON_IMPORT_HIP_RESPONSE: 'Import HIP response',
    LABEL_PAYMENT: 'Payment',
    LABEL_STATUS_CHANGE: 'Status Change',
    BUTTON_SEND_PAYMENT_FILE_TO_CONTROLLING: 'Send payment file ',
    LABEL_ERROR_CORRECTIONS: 'Error Corrections',
    BUTTON_SHOW_ALL_ERRONEOUS_CASES: 'Show all erroneous cases',
    LABEL_CASES_ON_HOLD: 'Cases on hold',
    BUTTON_SHOW_ALL_ON_HOLD_CASES: 'Show all on hold cases',
    LABEL_SETTLEMENT: 'Settlement',
    BUTTON_SUBMIT_SETLLEMENT_TO_HIP: 'Submit settlement to HIP',
    LABEL_DRUG_ORDER: 'Drug Orders',
    BUTTON_EXPORT_ALL_ORDERS: 'Export all Orders',
    LABEL_DRUG_ORDERS_SHIPPED: 'Drug Orders shipped',
    BUTTON_IMPORT_ORDERS: 'Import Orders',
    LABEL_POPUP_STERIBASE: 'Orders accepted, report created and uploaded to archive, export to Steribase not implemented yet',
    LABEL_WHAT_IS_YOUR_PASSWORD: 'What is your password?',
    LABEL_PLEASE_ENTER_PASSWORD: 'Please enter your password',
    LABEL_CREDENTIALS_NOT_VERIFIED: 'Sorry, these credentials could not be verified.',
    LABEL_NAME: 'Name',
    LABEL_USER_ADDED: 'New User added',
    LABEL_WARNING: 'Warning!',
    LABEL_NO_AVAILABLE_ITEMS: 'There are not eligible items for this operation',
    LABEL_REVIEW_TEMPORARY_DOCTORS: 'Review new AC Docs',
    LABEL_AMMOUNT: 'Amount',
    LABEL_OLDEST_CHANGE: 'Oldest Change',

    LABEL_DEFAULT_EMAIL: 'Default Notification Address',
    LABEL_ORDER_INTERVAL: 'Order Notification Interval - minutes',
    LABEL_IMMEDIATE_ORDER_INTERVAL: 'Immediate notification if order is within - minutes',
    LABEL_CANCELSETTINGS: 'Cancel',
    LABEL_PLEASE_PASSWORD: 'Please enter your password',
    LABEL_INVALID_NUMBER_ORDER: 'Invalid Order Notification Interval - minutes - numeric.',
    LABEL_INVALID_NUMBER_IMORDER: 'Invalid Immediate notification if order is within - minute - numeric.',
    LABEL_APP_SETTINGS_SAVED: 'New company settings saved',
    LABEL_WELCOMEEMAILWILLBESENTTOUSER: 'Welcome email will be send to user',
    LABEL_NON_COOPERATTING_PHARMACY: 'I would like to specify another practice',
    LABEL_NO_CASES_ELIGIBLE_FOR_STATUS_CHANGE: 'No cases eligible for status change.',
    LABEL_COMPLETE_ORDER_REPORT_CREATED: 'Complete orders report created',
    BUTTON_CREATE_COMPLETE_ORDERS_REPORT: 'Create complete orders report',
    LABEL_COMPLETE_ORDERS_REPORT: 'Complete orders report',

    //arch
    LABEL_TYPE: 'Type',
    LABEL_RECIPIENT: 'Recipient',
    LABEL_DESCRIPTION: 'Description',
    BUTTON_DOWNLOAD: 'Download',
    LABEL_EDIFACT: 'EDIFACT Export',
    LABEL_DATEV: 'DATEV Export',
    LABEL_HIPIMPORT: 'HIP Import',
    LABEL_HIPERROR: 'HIP Error',
    LABEL_STERIBASE: 'Steribase',
    LABEL_ADRESSE: 'Adresse',

    LABEL_LAST_NAME_FIRST_NAME: 'Last Name, First Name',
    LABEL_EMAIL_ADDRESS: 'E-mail',
    LABEL_PHONE_NUMBER: 'Phone Number',
    LABEL_PHONE_FAX: 'Telefon, Fax',
    LABEL_ADMIN: 'Admin',
    LABEL_MR: 'Mr',
    LABEL_MIS: 'Miss',
    LABEL_YES: 'yes',
    LABEL_NO: 'no',

    //patient
    LAEL_OP_DOCTOR_PRACTICE: 'OP Doc/Practice',
    LAEL_AC_DOCTOR_PRACTICE: 'Nachsorgearzt/Praxis',

    // contracts
    LABEL_CONTRACT_NAME: 'Contract',
    LABEL_CONTRACT_TITLE: 'Contract\'s title',
    LABEL_VALID_FROM: 'Valid from',
    LABEL_VALID_THROUGH: 'Valid until',
    LABEL_HIP_NAMES: 'Health insurance providers',
    LABEL_HIP_NAME: 'Health insurance provider',
    LABEL_GPOSES: 'Fee IDs',
    LABEL_DUE_DATES: 'Due Dates',
    LABEL_CONTRACT_SAVED: 'Contract saved.',
    LABEL_GPOS_NUMBER: 'Fee number',
    LABEL_GPOS_NAME: 'Fee type',
    LABEL_ADD_GPOS: 'Add new Fee ID',
    LABEL_ADD_GPOS_EXPANDED: 'Add new Fee ID',
    LABEL_GPOS: 'Gebührenposition',
    LABEL_CASE_ONE: 'Vorgang',
    LABEL_INJECTIONS_FROM: 'von Injektions-Nr.',
    LABEL_INJECTIONS_TO: 'bis Injektions-Nr.',
    LABEL_FEE_IN_EUR: 'Vergütung in €',
    LABEL_MANAGEMENT_FEE_IN_EUR: 'Managementgebühr in €',
    LABEL_WAIVE_WITH_ORDER: 'erlassen bei Bestellung ',
    LABEL_OP_CASE_TYPE: 'OP',
    LABEL_AC_CASE_TYPE: 'Nachsorge',
    LABEL_GPOS_ADDED: 'Neuer Gebührenposition gespeichert.',
    LABEL_ADD: 'Hinzufügen',
    LABEL_DRUG_ALREADY_SELECTED: 'Selected drug is already added to this contract.',
    LABEL_DIAGNOSE_ALREADY_SELECTED: 'Selected diagnose is already added to this contract.',
    LABEL_HIP_ALREADY_SELECTED: 'Selected health insurance provider is already added to this contract.',
    LABEL_DOCTOR_ALREADY_SELECTED: 'Selected doctor already has a participation consent on this contract.',
    LABEL_DIAGNOSE: 'Diagnose',
    LABEL_ICD10_NUMBER: 'ICD10 number',
    LABEL_HIP_NUMBER: 'HIP ID',
    LABEL_ADD_CHANGE_DUE_DATES: 'Configure Due Dates',
    LABEL_PARTICIPATION_CONSENT_DURATION: 'Duration of participation consent ',
    LABEL_DAYS_BETWEEN_SURGERY_AND_AFTERCARE: 'Number of days between surgery and aftercare',
    LABEL_NUMBER_OF_DAYS_BETWEEN_SURGERY_AND_SETTLEMENT_CLAIM: 'Number of days between treatment and settlement claim',
    LABEL_NUMBER_OF_DAYS_BETWEEN_SUBMISSION_TO_HIP_AND_REPLY: 'Number of days between submission to HIP and reply',
    LABEL_NUMBER_OF_DAYS_BETWEEN_RESPONSE_AND_PAYMENT: 'Number of days between response and payment',
    LABEL_NUMBER_OF_DAYS_BETWEEN_HIP_RESPONSE_AND_REJECTION: 'Number of days between HIP response and rejection',
    LABEL_MONTHS: 'months',
    LABEL_DAYS: 'days',
    LABEL_REMOVE_FROM_CONTRACT: 'Remove from contract',
    LABEL_REMOVE_DIAGNOSE_TITLE: 'Remove diagnose from contract',
    LABEL_REMOVE_DRUG_TITLE: 'Remove drug from contract',
    LABEL_REMOVE_HIP_TITLE: 'Remove HIP from contract',
    LABEL_REMOVE_DOCTOR_TITLE: 'Remove doctor from contract',
    LABEL_REMOVE_GPOS_TITLE: 'Remove GPOS from contract',
    LABEL_REMOVE_DATA_FROM_CONTRACT_CONTENT: 'Are you sure you want to remove {{eligible}} from this contract?',
    LABEL_GPOS_NUMBER_NOT_UNIQUE: 'Gpos number [{{number}}] already exists.',
    LABEL_CONTRACT_COPIED: 'Contract copied.',
    LABEL_START_DATE_MANDATORY: 'Contract consent start date not entered.',
    LABEL_CONTRACT_DATES_OVERLAPS: 'There is a contract {{consentContractName}} ( {{consentValidFrom}} - {{consentValidThrough}} ) active already for this period.',

    LABEL_CONTACT: 'Ansprechpartner',
    LABEL_PREFERRED_PHARMACY: 'Preferred pharmacy',
    LABEL_QUICK_ORDER_VERWNDEN: 'Quick-Order verwnden (Praxisadresse wird als Lieferadresse verwendet)',
    LABEL_QUICK_ORDER_GRACE_PERIOD: 'Passwort Grace-Periode bei Quick-Order verwender',
    LABEL_OTHER_OPTIONS: 'Other options',
    LABEL_NONE: 'None',

    TOOLTIP_QUICK_ORDER_MSG: 'Um die Quick-Order zu nutzen, wählen Sie bitte eine bevorzugte Apotheke aus und geben Sie Praxisadresse, Ansprechpartner, Standardlieferdatum und Standardlieferzeit an.',

    //***ACCOUNT STATUS***//
    aktiv: 'Active',
    inaktiv: 'Inactive',
    temp: 'Temp',

    //***BUTTONS GLOBAL***//
    BUTTON_404: 'Return to default page',
    BUTTON_CONFIRM: 'CONFIRM',
    BUTTON_CONFIRM_NORMALCASE: 'Confirm',
    BUTTON_YES: 'Yes',
    BUTTON_NO: 'No',
    BUTTON_ADD_NEW_USER: 'Add User',
    BUTTON_SHOW_NEW_DOCTORS: 'Show new AC Docs',
    BUTTON_SAVESETTINGS: 'Save',
    BUTTON_CANCELSETTINGS: 'Cancel',
    BUTTON_COPY: 'Copy',
    BUTTON_GO_TO_PATIENT_DETAILS: 'Patientenakte aufrufen',
};
