INSERT INTO 
	ord_cuo_rfp_issuedproposalresponse_headers
	(
		ORD_CUO_RFP_IssuedProposalResponse_HeaderID,
		ProposalResponseHeaderITPL,
		CreatedFor_RequestForProposal_Header_RefID,
		DefaultCurrency_RefID,
		ValidThrough,
		TotalPrice_WithoutTax,
		TotalPrice_IncludingTax,
		ProposalResponseDocument_RefID,
		IsActive,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@ORD_CUO_RFP_IssuedProposalResponse_HeaderID,
		@ProposalResponseHeaderITPL,
		@CreatedFor_RequestForProposal_Header_RefID,
		@DefaultCurrency_RefID,
		@ValidThrough,
		@TotalPrice_WithoutTax,
		@TotalPrice_IncludingTax,
		@ProposalResponseDocument_RefID,
		@IsActive,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)