INSERT INTO 
	res_realestateproperties
	(
		RES_RealestatePropertyID,
		RealestateProperty_Title,
		RealestateProperty_InternalID,
		InformationSubmittedBy_Account_RefID,
		RealestateProperty_Address_RefID,
		RealestateProperty_Location_RefID,
		RealestateProperty_GroundValuePrice_RefID,
		RealestateProperty_AverageAreaRentPrice_RefID,
		RealestateProperty_ConstructionDate,
		RealestateProperty_RefurbishmentDate,
		RealestateProperty_InformationDate,
		RealestateProperty_LivingSpace_in_sqm,
		RealestateProperty_NumberOfResidentialUnits,
		RealestateProperty_GroundAreaSize_in_sqm,
		Geolocation_Lattitude,
		Geolocation_Longitude,
		Creation_Timestamp,
		IsLocked,
		IsArchived,
		IsDeleted,
		Tenant_RefID
	)
VALUES 
	(
		@RES_RealestatePropertyID,
		@RealestateProperty_Title,
		@RealestateProperty_InternalID,
		@InformationSubmittedBy_Account_RefID,
		@RealestateProperty_Address_RefID,
		@RealestateProperty_Location_RefID,
		@RealestateProperty_GroundValuePrice_RefID,
		@RealestateProperty_AverageAreaRentPrice_RefID,
		@RealestateProperty_ConstructionDate,
		@RealestateProperty_RefurbishmentDate,
		@RealestateProperty_InformationDate,
		@RealestateProperty_LivingSpace_in_sqm,
		@RealestateProperty_NumberOfResidentialUnits,
		@RealestateProperty_GroundAreaSize_in_sqm,
		@Geolocation_Lattitude,
		@Geolocation_Longitude,
		@Creation_Timestamp,
		@IsLocked,
		@IsArchived,
		@IsDeleted,
		@Tenant_RefID
	)