INSERT INTO 
	ord_prc_extrademandproducts
	(
		ORD_PRC_ExtraDemandProductID,
		Supplier_RefID,
		Product_RefID,
		Product_Variant_RefID,
		Product_Release_RefID,
		RequestedQuantity,
		IsProcurementRunning,
		ProcurementOrderPosition_RefID,
		CreatedBy_BusinessParticipant_RefID,
		CreatedFor_Office_RefID,
		DeliveryTo_Warehouse_RefID,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@ORD_PRC_ExtraDemandProductID,
		@Supplier_RefID,
		@Product_RefID,
		@Product_Variant_RefID,
		@Product_Release_RefID,
		@RequestedQuantity,
		@IsProcurementRunning,
		@ProcurementOrderPosition_RefID,
		@CreatedBy_BusinessParticipant_RefID,
		@CreatedFor_Office_RefID,
		@DeliveryTo_Warehouse_RefID,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)