//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMDocConnectDocAppServices.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMDocConnectDocAppServices.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hallo.
        /// </summary>
        internal static string bodyLine1 {
            get {
                return ResourceManager.GetString("bodyLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vielen Dank für Deine Mitarbeit am Abrechnungsprogramm von mediosmanagement..
        /// </summary>
        internal static string bodyLine2 {
            get {
                return ResourceManager.GetString("bodyLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dein Passwort wurde zurückgesetzt. Das neue Passwort lautet:.
        /// </summary>
        internal static string bodyLine3 {
            get {
                return ResourceManager.GetString("bodyLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte ändere das Passwort aus Sicherheitsgründen bei Deinem ersten Login..
        /// </summary>
        internal static string bodyLine4 {
            get {
                return ResourceManager.GetString("bodyLine4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für Rückfragen stehen wir Dir gern zur Verfügung..
        /// </summary>
        internal static string bodyLine6 {
            get {
                return ResourceManager.GetString("bodyLine6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viele Grüße..
        /// </summary>
        internal static string bodyLine7 {
            get {
                return ResourceManager.GetString("bodyLine7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dein mediosmanagement Team..
        /// </summary>
        internal static string bodyLine8 {
            get {
                return ResourceManager.GetString("bodyLine8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17172100035.
        /// </summary>
        internal static string ContractCharacteristicsID {
            get {
                return ResourceManager.GetString("ContractCharacteristicsID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medios Connect  / Neues Passwort.
        /// </summary>
        internal static string emailSubject {
            get {
                return ResourceManager.GetString("emailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 591104483.
        /// </summary>
        internal static string InterchangeSenderID {
            get {
                return ResourceManager.GetString("InterchangeSenderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://lynxv3.b-op.com/mmdocconnect-doc/.
        /// </summary>
        internal static string link {
            get {
                return ResourceManager.GetString("link", resourceCulture);
            }
        }
    }
}
