INSERT INTO 
	cmn_cal_repetitionpatterns_yearly
	(
		CMN_CAL_RepetitionPattern_YearlyID,
		Repetition_RefID,
		Repetition_EveryNumberOfYears,
		Repetition_Month,
		IsFixed,
		IsRelative,
		IfRelative_RepetitionPattern_RefID,
		IfFixed_DayOfMonth,
		Creation_Timestamp,
		IsDeleted,
		Tenant_RefID
	)
VALUES 
	(
		@CMN_CAL_RepetitionPattern_YearlyID,
		@Repetition_RefID,
		@Repetition_EveryNumberOfYears,
		@Repetition_Month,
		@IsFixed,
		@IsRelative,
		@IfRelative_RepetitionPattern_RefID,
		@IfFixed_DayOfMonth,
		@Creation_Timestamp,
		@IsDeleted,
		@Tenant_RefID
	)