

var translationsOrderDE = {
    //***LABELS***//
	LABEL_FILTER_BY_IVOM_DATE: 'Filtern nach IVOM-Datum',
	LABEL_ORDER_IVOM_DATE: 'IVOM-Datum',
    LABEL_TREATMENT_DATE_OF_SOME_ORDERS_IS_BEFORE_DELIVERY_DATE: 'Für einige ausgewählte Medikamente ist die Behandlung früher geplannt als der Liefertermin. Möchten Sie mit dem gewählten Liefertermin fortfahren?',
    LABEL_POSITION_COMMENT: 'Kommentar zum Medikament',
    LABEL_HEADER_COMMENT: 'Kommentar zur Bestellung',
    LABEL_ALTERNATIVE_DELIVERY_DATE: 'Abweichendes Lieferdatum',
    LABEL_DELIVERY_DATE: 'Lieferdatum',
    LABEL_DELIVERY_TIME: 'Lieferzeit',
    LABEL_DRUG_NAME: 'Name des Medikaments',
    LABEL_NO_FEE: 'Gebührenbefreit',
    LABEL_PRACTICE_INVOICE: 'Rechnung an Praxis',
    LABEL_ORDER_DRUG: 'Medikament bestellen',
    LABEL_ONLY_LABEL_REQUIRED: 'Nur Etikett liefern',
    LABEL_PATIENT_NAME: 'Name des Patienten',
    LABEL_TREATMENT_DATE: 'Behandlungsdatum',
    LABEL_ADD_TREATMENT: 'Behandlung hinzufügen',
    LABEL_TREATMENT: 'Behandlung',
    LABEL_FROM: 'von',
    LABEL_TO: 'bis',
    LABEL_HOUR: 'Uhr',
    LABEL_DRUG: 'Medikament',
    LABEL_PHARMACY: 'Apotheke, Liefertermin',
    LABEL_DIAGNOSE: 'Diagnose',
    LABEL_LOKALIZATION: 'Lokalisation',
    LABEL_LEFT: 'links',
    LABEL_RIGHT: 'rechts',
    LABEL_CONFIRMED: 'Gesichert',
    LABEL_OP_DOCTOR: 'operierender Arzt',
    LABEL_AC_DOCTOR: 'Betreuender Augenarzt',
    LABEL_ADD_NEW_PATIENT: 'neuen Patient anlegen',
    LABEL_DIAGNOSE_DRUG: 'Diagnose / Medikament',
    LABEL_AFTERCARE: 'Nachsorge',
    LABEL_STATUS: 'Status',
    LABEL_LAST_NAME_FIRST_NAME_DOB: 'Nachname, Vorname <Geburtsdatum>',
    LABEL_INVALID_DELIVERY_TIME: 'Lieferzeit (von) ist kleiner als Lieferzeit (bis).',
    LABEL_LAST_USED: 'ZULETZT VERWENDET',
    LABEL_EDIT_ORDER_MESSAGE: 'Bitte beachten Sie, dass vorgenommene Änderungen auch die geplannte Behandlung betreffen und nicht nur die Bestellung.',
    OP1: 'Behandlung geplant',
    MO1: 'Medikament bestellt',
    LABEL_TODAY: 'Heute',
    LABEL_TOMORROW: 'Morgen',
    LABEL_FUTURE: 'alle Lieferungen für geplante IVOMs',
    LABEL_CUSTOM: 'Zeitraum',
    LABEL_YES: 'Ja',
    LABEL_ORDER_MESSAGE: 'Diese Bestellung ist Teil einer Behandlung. Einige Informationen können daher nur in der Behandlung bearbeitet werden.',

    //***BUTTONS***//
    BUTTON_ADD_PARTICIPATION_CONSENT: 'Teilnahmeerklärung hinzufügen'

};
var translationsOrderEN = {
    //***LABELS***//

    LABEL_ALTERNATIVE_DELIVERY_DATE: 'Alternative delivery date',
    LABEL_DELIVERY_DATE: 'Delivery date',
    LABEL_DELIVERY_TIME: 'Delivery time',
    LABEL_DRUG_NAME: 'Drug',
    LABEL_NO_FEE: 'No fee',
    LABEL_PRACTICE_INVOICE: 'Invoice to Practice',
    LABEL_ORDER_DRUG: 'Order drug',
    LABEL_ONLY_LABEL_REQUIRED: 'Only label required',
    LABEL_PATIENT_NAME: 'Patient Name',
    LABEL_TREATMENT_DATE: 'Treatment date',
    LABEL_ADD_TREATMENT: 'Add Treatment',
    LABEL_TREATMENT: 'Treatment',
    LABEL_FROM: 'from',
    LABEL_TO: 'to',
    LABEL_HOUR: 'Hours',
    LABEL_DRUG: 'Drug',
    LABEL_PHARMACY: 'Pharmacy',
    LABEL_DIAGNOSE: 'Diagnosis',
    LABEL_LOKALIZATION: 'Effected Eye',
    LABEL_LEFT: 'left',
    LABEL_RIGHT: 'right',
    LABEL_CONFIRMED: 'Confirmed',
    LABEL_OP_DOCTOR: 'OP Doctor',
    LABEL_AC_DOCTOR: 'Aftercare Doctor',
    LABEL_ADD_NEW_PATIENT: 'add new patient',
    LABEL_DIAGNOSE_DRUG: 'Diagnose / Drug',
    LABEL_AFTERCARE: 'Aftercare',
    LABEL_STATUS: 'Status',
    LABEL_LAST_NAME_FIRST_NAME_DOB: 'Last Name, First Name <DOB>',
    LABEL_INVALID_DELIVERY_TIME: 'Delivery time to must be greater than or equal to delivery time from',
    LABEL_LAST_USED: 'LAST USED',
    LABEL_EDIT_ORDER_MESSAGE: 'Please have in mind that editing these data will affect the planned treatment, not just the order.',
    OP1: 'Treatment planned',
    MO1: 'Drug ordered',
    LABEL_ORDER_MESSAGE: 'This order is paired with a treatment and as such it does not allow changing if certain data. In order to change treatment data, please locate and edit the treatment itself.',
    LABEL_FUTURE: 'Future',
    LABEL_CUSTOM: 'Custom',


    //***BUTTONS***//
    BUTTON_ADD_PARTICIPATION_CONSENT: 'Add participation consent'
};