

var translationsPatientDE = {
    //***BUTTONS***//
    BUTTON_ADD_PARTICIPATION_CONSENT: 'Teilnahmeerklärung hinzufügen',
    BUTTON_ADD_PATIENT_FEE_WAIVER: 'Gebührenbefreiung hinzufügen',
    LABEL_ORIGINATING_PRACTICE: 'operierende Praxis',
    //***LABELS***//
    LABEL_EXISTING_IVOM_FOUND: 'Diese IVOM ist bereits in Medios Connect hinterlegt.',
    LABEL_LATEST_IVOM_EXISTS: 'Diese IVOM ist nach oder am selben Datum wie die letzte IVOM ({{date}}).',
    LABEL_WIZARD_OCTS_FIRST_LINE: 'Die Informationen wurden hinzugefügt. Eine Teilnahmeerklärung für den Patienten {{ patient_name }} wurde mit dem Startdatum {{ earlier_treatment_year_start_date }} angelegt. Bitte geben Sie die Informationen für die {{ number_of_octs }} OCTs aus dem BDOC Vertrag ein.',
    LABEL_DOCUMENTATION_ONLY_CASES_SAVED: 'Die Informationen wurden zur Dokumentation gespeichert.',
    LABEL_ADD_DOCUMENTATION_ONLY_CASES: 'Behandlungen aus dem BDOC Vertrag übertragen (nicht zur Abrechnung)',
    LABEL_PATIENT_ID: 'externe ID',
    LABEL_LEFT_EYE: 'Linkes Auge',
    LABEL_RIGHT_EYE: 'Rechtes Auge',
    LABEL_PATIENT_FEE_WAIVER_SAVED: 'Gebührenbefreiung gespeichert',
    LABEL_FEE_WAIVER_ACTIVE: 'aktuell',
    LABEL_FEE_WAIVER_EXPIRED: 'abgelaufen',
    LABEL_FEE_WAIVER_NOT_YET_ACTIVE: 'noch nicht aktiv',
    LABEL_FEE_WAIVER_ACTIVE_UNTIL: 'Gebührenbefreiung bis {{year}}',
    LABEL_FEE_WAIVER_DELETED: 'Gebührenbefreiung gelöscht',
    LABEL_FEE_WAIVER_EXISTS_FOR_YEAR: 'Eine Gebührenbefreiung für dieses Jahr besteht bereits.',
    LABEL_PATIENT_FEE_WAIVED_FROM: 'Gebührenbefreit seit',

    LABEL_WITH_REJECTED_OCTS: 'abgelehnte OCTs',
    LABEL_FIRST_NAME: 'Vorname',
    LABEL_LAST_NAME: 'Nachname',
    LABEL_LAST_NAME_FIRST_NAME: 'Nachname, Vorname',
    LABEL_SEX: 'Geschlecht',
    LABEL_DATE_OF_BIRTH: 'Geburtsdatum',
    LABEL_HEALTH_INSURANCE_PROVIDER: 'Krankenkasse',
    LABEL_INSURANCE_ID: 'Versichertennummer',
    LABEL_INSURANCE_STATUS: 'Versichertenstatus',
    LABEL_NEW_PATIENT: 'neuer Patient',
    LABEL_PARTICIPATION_CONSENT: 'Teilnahmeerklärung',
    LABEL_ADD_PARTICIPATION_CONSENT: 'Teilnahmeerklärung hinzufügen',
    LABEL_INVALID_HEALTH_INSURANCE_NUMBER: 'Versichertennummer ungültig',
    LABEL_INVALID_INSURANCE_STATUS_CODE: 'Versichertenstatus ungültig',
    LABEL_SAVED_NEW_PATIENT: 'Neuer Patient gespeichert',
    LABEL_CANT_SAVE: 'Die Änderung konnte nicht gespeichert werden.',
    LABEL_PATIENTDATA_NOT_ALIGNRD_WITH_HIN: 'Der Versichertenstatus stimmt nicht mit den Patientendetails überein.',
    LABEL_HIN_MATCHES_ANY_OTHER_PATIENT_IN_PRACTICE: 'Die angegebene Versichertennummer ist bereits für den Patienten {{first_name}} {{last_name}} hinterlegt.',
    LABEL_COMBINATION_FIRST_LAST_NAME_HIM_MATCHES: 'Es existiert bereits ein Patient {{first_name}} {{last_name}} mit identischem Geburtsdatum.',
    LABEL_CASE: 'Vorgang',
    LABEL_PARTICIPATION_CONSENT: 'Teilnahmeerklärung',
    LABEL_CONTRACT: 'Vertrag',
    LABEL_ISSUE_DATE: 'Ausstellungsdatum',
    LABEL_ISSUE_DATE_LOWER_THEN_CONTRACT_DATE: 'Die Teilnahmeerklärung liegt außerhalb der Vertragslaufzeit mit der Krankenkasse. ({{validFrom}} - {{validTo}})',
    LABEL_SAVED_NEW_PARTICIPATION_CONSENT: 'Teilnahmeerklärung gespeichert',
    LABEL_PATIENT_EDITED: 'Patient bearbeitet',
    LABEL_HEALTH_INSURANCE_NUMBER_ONLY_DIGITS: 'Der Versichertenstatus darf nur Zahlen enthalten.',
    LABEL_ERROR_NEW_KVR_VALIDATION: 'Die Versichertennummer konnte nicht validiert werden.',
    LABEL_ERROR_NEW_KVR_VALIDATION_FOR_PATIENT: 'Die Versichertennummer konnte nicht validiert werden. Patient {{name}} ({{insurance_number}})',

    LABEL_ACTIVE_CONSENT: 'aktualisiert',
    LABEL_EXPIRED_CONSENT: 'abgelaufen',

    LABEL_RETRO_CASES_WIZARD_TITLE: 'Behandlungen aus dem BDOC Vertrag übertragen (nicht zur Abrechnung)',
    LABEL_RETRO_CASES_INTRO: 'Start',
    LABEL_RETRO_CASES_OCTS: 'OCTs',
    LABEL_RETRO_CASES_IVOMS: 'IVOMs',
    LABEL_RETRO_CASES_CONFIRM: 'Überprüfen',
    LABEL_RETRO_CASES_INTRO_DESCRIPTION: 'Mit diesem Dialog möchten wir Sie unterstützen, Informationen aus dem BDOC Vertrag in Medios Connect für {{patientName}} zu übertragen. Für eine korrekte Abrechnung mit der Krankenkasse benötigen wir das Datum, wann das aktuell laufende Behandlungsjahr begonnen hat, sowie das Datum der letzten durchgeführten IVOM. Des weiteren wird die Anzahl der im aktuell laufenden Behandlungsjahr über den BDOC Vertrag abgerechneten OCTs benötigt. Anschließend können Sie weitere Informationen zu durchgeführten OCTs und IVOMs eingeben.',
    LABEL_NUMBER_OF_OCTS: 'Anzahl der OCTs im BDOC',
    LABEL_CURRENT_TREATMENT_YEAR_START: 'Start des laufenden Behandlungsjahres',
    LABEL_RETRO_CASES_IVOMS_DESCRIPTION: 'Das Datum der letzten IVOM haben Sie bereits eingegeben. Sie können hier weitere IVOMs dokumentieren.',
    LABEL_RETRO_CASES_CONFIRM_DESCRIPTION: 'Bitte überprüfen Sie die eingegebenen Daten. Für eine Korrektur können Sie zurück gehen. Zum Speichern klicken Sie bitte beenden. Nach dem Speichern sind die Behandlungen mit dem Status "zur Dokumentation" in Medios Connect eingetragen.',
    LABEL_RETRO_CASES_CONFIRM_EYE_OVERVIEW: 'Das Behandlungsjahr startete am {{treatmentYearSarted}}. {{patientName}} hatte {{octNumber}} OCTs im BDOC Vertrag in diesem Behandlungsjahr. Dokumentierte IVOMs: {{opNumber}}',

    LABEL_TREATMENT_YEAR_IN_FUTURE: 'Das Datum ({{date}}) liegt in der Zukunft.',
    LABEL_LATEST_IVOM_IN_FUTURE: 'Das Datum ({{date}}) liegt in der Zukunft.',
    LABEL_OCT_DATE_IN_FUTURE: 'Das Datum ({{date}}) liegt in der Zukunft.',

    LABEL_OP_DATE: 'IVOM Datum',
    LABEL_TREATMENT_YEAR: 'Behandlungsjahr',
};

var translationsPatientEN = {

    //***BUTTONS***//
    BUTTON_ADD_PARTICIPATION_CONSENT: 'Add participation consent',

    //***LABELS***//


    LABEL_FIRST_NAME: 'First Name',
    LABEL_LAST_NAME: 'Last Name',
    LABEL_LAST_NAME_FIRST_NAME: 'First Name, Last Name',
    LABEL_SEX: 'Sex',
    LABEL_DATE_OF_BIRTH: 'Date of birth',
    LABEL_HEALTH_INSURANCE_PROVIDER: 'Health Insurance Provider',
    LABEL_INSURANCE_ID: 'Insurance ID',
    LABEL_INSURANCE_STATUS: 'Insurance Status',
    LABEL_NEW_PATIENT: 'new Patient',
    LABEL_PARTICIPATION_CONSENT: 'Participation consent',
    LABEL_ADD_PARTICIPATION_CONSENT: 'Add participation consent',
    LABEL_INVALID_HEALTH_INSURANCE_NUMBER: 'Invalid Insurance ID.',
    LABEL_INVALID_INSURANCE_STATUS_CODE: 'Invalid Insurance Status',
    LABEL_SAVED_NEW_PATIENT: 'New patient saved.',
    LABEL_CANT_SAVE: 'Changes saved',
    LABEL_PATIENTDATA_NOT_ALIGNRD_WITH_HIN: 'The health insurance status doesn’t match with the patient’s data.',
    LABEL_HIN_MATCHES_ANY_OTHER_PATIENT_IN_PRACTICE: 'There is record of a patient {{first_name}} {{last_name}} with the same insurance number. ',
    LABEL_COMBINATION_FIRST_LAST_NAME_HIM_MATCHES: 'There is a record of a patient named {{first_name}} {{last_name}} , born on the same date in the system.',
    LABEL_CASE: 'Cases',
    LABEL_PARTICIPATION_CONSENT: 'Teilnahmeerklärung',
    LABEL_CONTRACT: 'Contract',
    LABEL_ISSUE_DATE: 'Issue date',
    LABEL_ISSUE_DATE_LOWER_THEN_CONTRACT_DATE: 'Participation consent date must be in range of the contract duration date.',
    LABEL_SAVED_NEW_PARTICIPATION_CONSENT: 'Participation consent saved.',
    LABEL_PATIENT_EDITED: 'Patient edited.',
    LABEL_HEALTH_INSURANCE_NUMBER_ONLY_DIGITS: 'Helath insurance number should contain only numbers.',
    LABEL_ERROR_NEW_KVR_VALIDATION: 'Inserted KVNR number breaks validation rules for the new KVNR.',
    LABEL_ERROR_NEW_KVR_VALIDATION_FOR_PATIENT: 'Inserted KVNR number breaks validation rules for the new KVNR. Patient {{name}} ({{insurance_number}})',

    LABEL_RETRO_CASES_WIZARD_TITLE: 'Document cases from DBOC',
    LABEL_RETRO_CASES_INTRO: 'Intro',
    LABEL_RETRO_CASES_OCTS: 'OCTs',
    LABEL_RETRO_CASES_IVOMS: 'IVOMs',
    LABEL_RETRO_CASES_CONFIRM: 'Confirm',
    LABEL_RETRO_CASES_INTRO_DESCRIPTION: 'With this wizard you can add information from the BDOC contract and start using MediosConnect for {{patientName}}. For the correct settlement with the HIP we need the start date of the currently running treatment year, the date of the last performed IVOM and the number of OCTs which have already been performed for each localization in the currently running treatment year. You will be able to enter detailed OCT and IVOM data in the next 2 steps.',
    LABEL_NUMBER_OF_OCTS: 'Number of OCTs',
    LABEL_CURRENT_TREATMENT_YEAR_START: 'Current treatment year start',
    LABEL_RETRO_CASES_IVOMS_DESCRIPTION: 'We have the information about the last IVOM already, but if you wish, you can add earlier IVOMs to our database, to have everything in one place.',
    LABEL_RETRO_CASES_CONFIRM_DESCRIPTION: 'Here is the summary of the data you entered. If everything seems fine, click on Finish. If you missed something, or see an error, you can go back and correct it.',
    LABEL_RETRO_CASES_CONFIRM_EYE_OVERVIEW: 'Treatment year started on {{treatmentYearSarted}}. {{patientName}} had {{octNumber}} OCTs and {{opNumber}} IVOMs performed in the treatment year.',

    LABEL_TREATMENT_YEAR_IN_FUTURE: 'Treatment year can not be in future ({{date}})',
    LABEL_LATEST_IVOM_IN_FUTURE: 'Last IVOM date can not be in future ({{date}})',
    LABEL_OCT_DATE_IN_FUTURE: 'OCT date can not be in future ({{date}})',

    LABEL_OP_DATE: "IVOM",
    LABEL_TREATMENT_YEAR: "Behandlungsjahr"
};