

var translationsPlanningDE = {
    //***LABELS***//
    LABEL_AFTERCARE_DOCTOR_MANDATORY_FOR_SETTLEMENT: 'Der betreuende Augenarzt muss vor der Abrechnung angegeben werden.',
    LABEL_OCT_DOCTOR_MANDATORY_FOR_SETTLEMENT: 'Der OCT Diagnostik Arzt muss vor der Abrechnung angegeben werden.',
    LABEL_IVOM_DOCTOR_MANDATORY_FOR_SETTLEMENT: 'Der IVOM Arzt muss vor der Abrechnung angegeben werden.',
    LABEL_PENDING_OCT_WONT_BE_AUTOMATICALLY_CANCELLED: 'Eine OCT Diagnostik wurde für diese Behandlung bereits zur Abrechnung vorgemerkt. Wird die Behandlung nicht durchgeführt, kann die OCT Diagnostik nicht mit der Krankenkasse abgerechnet werden. Die vorgemerkte OCT Diagnostik wird nicht automatisch gelöscht.',
    LABEL_PLEASE_ENTER_PASSWORD_TO_CHANGE_ORDER: 'Achtung! Der vorhandene Bestellung wird storniert und ein neuer erstellt. Bitte geben Sie ihr Passwort zur Bestätigung ein.',
    LABEL_PLEASE_ENTER_PASSWORD_TO_CANCEL_ORDER: 'Bitte geben Sie Ihr Passwort ein, um die Bestellung stornieren.',
    LABEL_ALTERNATIVE_DELIVERY_DATE: 'Abweichendes Lieferdatum',
    LABEL_DELIVERY_DATE: 'Lieferdatum',
    LABEL_DELIVERY_TIME: 'Lieferzeit',
    LABEL_DRUG_NAME: 'Name des Medikaments',
    LABEL_NO_FEE: 'Gebührenbefreit',
    LABEL_PRACTICE_INVOICE: 'Rechnung an Praxis',
    LABEL_ORDER_DRUG: 'Medikament bestellen',
    LABEL_ONLY_LABEL_REQUIRED: 'Nur Etikett liefern',
    LABEL_PATIENT_NAME: 'Name des Patienten',
    LABEL_TREATMENT_DATE: 'Behandlungsdatum',
    LABEL_ADD_TREATMENT: 'Behandlung hinzufügen',
    LABEL_TREATMENT: 'Behandlung',
    LABEL_FROM: 'von',
    LABEL_TO: 'bis',
    LABEL_HOUR: 'Uhr',
    LABEL_DRUG: 'Medikament',
    LABEL_DIAGNOSE: 'Diagnose',
    LABEL_LOKALIZATION: 'Lokalisation',
    LABEL_LEFT: 'links',
    LABEL_RIGHT: 'rechts',
    LABEL_CONFIRMED: 'Gesichert',
    LABEL_DOCTOR: 'Arzt',
    LABEL_OP_DOCTOR: 'operierender Arzt',
    LABEL_AC_DOCTOR: 'Betreuender Augenarzt',
    LABEL_ADD_NEW_PATIENT: 'neuen Patient anlegen',
    LABEL_DIAGNOSE_DRUG: 'Diagnose / Medikament',
    LABEL_AFTERCARE: 'Nachsorge',
    LABEL_STATUS: 'Status',
    LABEL_LAST_NAME_FIRST_NAME_DOB: 'Nachname, Vorname',
    LABEL_INVALID_DELIVERY_TIME: 'Lieferzeit (von) ist kleiner als Lieferzeit (bis).',
    LABEL_LAST_USED: 'ZULETZT VERWENDET',
    OP1: 'Behandlung geplant',
    OP3: 'überfällig',
    OP4: 'gelöscht',
    MO1: 'Medikament bestellt',
    MO2: 'Bestellung angenommen',
    MO3: 'Medikament in Auslieferung',
    MO4: 'Medikament nicht lieferbar',
    MO6: 'Bestellung storniert',
    MO9: 'Bestellung gelöscht',
    MO10: 'bestellt bei einer nicht kooperierenden Apotheke',
    LABEL_NO_DRUGS_ORDERED: 'keine Bestellung',
    LABEL_PLEASE_ENTER_VALID_TIME: 'Lieferzeit ungültig',
    LABEL_ORDERED_PLANNED: 'Behandlung geplant & Medikament bestellt',
    LABEL_DELIVERY_DATE_LENGTH: 'Lieferdatum ungültig',
    LABEL_TREATMENT_DATE_LENGTH: 'Behandlungsdatum ungültig',
    LABEL_INVALID_DELIVERY_DATE: 'Das Lieferdatum ist später als das Behandlungsdatum.',
    LABEL_CASE_SUBMITTED: 'Ihre Vorgänge wurden zur Abrechnung übermittelt.',
    LABEL_PLEASE_ENTER_PASSWORD_TO_SUBMIT_CASE: 'Bitte geben Sie Ihr Passwort ein, um die Vorgänge zur Abrechnung zu übermitteln.',
    LABEL_CANCEL_BOTH_ORDER_AND_TREATMENT: 'Behandlung und Bestellung löschen',
    LABEL_CANCEL_DRUG_ORDER_ONLY: 'Bestellung stornieren',
    LABEL_CONTENT_CANCEL_BOTH: 'Möchten Sie die Behandlung und Bestellung löschen?',
    LABEL_CONTENT_CANCEL_TREATMENT: 'Möchten Sie die Behandlung löschen?',
    LABEL_CONTENT_CANCEL_ORDER: 'Möchten Sie die Bestellung löschen?',
    LABEL_TITLE_CANCEL_BOTH: 'Was möchten Sie löschen?',
    LABEL_TITLE_CANCEL_TREATMENT: 'Behandlung löschen',
    LABEL_TITLE_CANCEL_ORDER: 'Bestellung löschen',
    LABEL_RADIO_BOTH: 'Behandlung und Bestellung löschen',
    LABEL_RADIO_ORDER_ONLY: 'Nur Bestellung löschen',
    LABEL_MESSAGE_CANCEL_BOTH: 'Behandlung & Bestellung löschen.',
    LABEL_MESSAGE_CANCEL_TREATMENT: 'Behandlung löschen',
    LABEL_MESSAGE_CANCEL_ORDER: 'Bestellung löschen',
    LABEL_EDIT_PATIENT_DATA: 'Patientendaten überprüfen',
    LABEL_MULTI_EDIT_ELIGIBILITY: 'Einige der ausgewählten Vorgänge sind Bestellungen ohne eine Behandlung. Diese werden nicht geändert. Möchten Sie fortfahren?',
    LABEL_MULTI_SUBMIT_ELIGIBILITY: 'Einige der ausgewählten Behandlungen können nicht übermittelt werden. Möchten Sie fortfahren?',
    LABEL_MULTI_SETTLEMENT_ELIGIBILITY: 'Einige der ausgewählten Behandlungen können nicht geändert werden. Möchten Sie fortfahren?',
    LABEL_NO_ITEMS_FOR_EDIT: 'Die ausgewählten Behandlungen werden nicht geändert. Dieser Vorgang ist nicht möglich.',
    LABEL_CASE_CANNOT_MULTI_EDIT: 'Dieser Vorgang kann zur Bearbeitung nicht ausgewählt werden.',
    LABEL_ADD_NEW_AFTERCARE_DOCTOR: 'neuen Augenarzt anlegen',
    LABEL_CANCEL_OCT_FIRST: 'Case has a pending OCT attached and there is not another IVOM to transfer OCT to. Please cancel the pending OCT first and then try to change the localization again.',

    LABEL_MULTI_EDIT_SETTLEMENT: 'Die Behandlungen wurden aktualisiert',
    LABEL_SCHEDULED: 'Geplant',
    LABEL_OVERDUE2: 'überfällig',
    LABEL_REJECTED: 'Nicht zugewiesen',
    LABEL_CANCELED_DELETED: 'gelöscht',
    LABEL_TREATMENT_WITH_ORDER: 'Behandlungen mit Bestellungen',
    LABEL_ORDERS: 'Bestellungen',
    LABEL_TREATMENTS: 'Behandlungen ohne Bestellungen',

    ORDER_PLACED: 'Medikament in den Warenkorb gelegt',
    ORDER_CONFIRMED: 'Medikament bestellt',
    TREATMENT_PLANNED_AND_ORDER_PLACED: 'Medikament in den Warenkorb gelegt, Behandlung geplant',
    TREATMENT_PLANNED_AND_ORDER_CONFIRMED: 'Medikament bestellt, Behandlung geplant',


    //***BUTTONS***//
    BUTTON_CANCEL_CASE_CANCEL: 'Nein, doch nicht',
    BUTTON_CANCEL_CASE_CONFIRM: 'Ja, Stornieren',
    BUTTON_CANCEL_CASE: 'löschen'

};
var translationsPlanningEN = {
    //***LABELS***//

    LABEL_ALTERNATIVE_DELIVERY_DATE: 'Alternative delivery date',
    LABEL_DELIVERY_DATE: 'Delivery date',
    LABEL_DELIVERY_TIME: 'Delivery time',
    LABEL_DRUG_NAME: 'Drug',
    LABEL_NO_FEE: 'No fee',
    LABEL_PRACTICE_INVOICE: 'Invoice to Practice',
    LABEL_ORDER_DRUG: 'Order drug',
    LABEL_ONLY_LABEL_REQUIRED: 'Only label required',
    LABEL_PATIENT_NAME: 'Patient Name',
    LABEL_TREATMENT_DATE: 'Treatment date',
    LABEL_ADD_TREATMENT: 'Add Treatment',
    LABEL_TREATMENT: 'Treatment',
    LABEL_FROM: 'from',
    LABEL_TO: 'to',
    LABEL_HOUR: 'Hours',
    LABEL_DRUG: 'Drug',
    LABEL_DIAGNOSE: 'Diagnosis',
    LABEL_LOKALIZATION: 'Effected Eye',
    LABEL_LEFT: 'left',
    LABEL_RIGHT: 'right',
    LABEL_CONFIRMED: 'Confirmed',
    LABEL_DOCTOR: 'Doctor',
    LABEL_OP_DOCTOR: 'OP Doctor',
    LABEL_AC_DOCTOR: 'Aftercare Doctor',
    LABEL_ADD_NEW_PATIENT: 'add new patient',
    LABEL_DIAGNOSE_DRUG: 'Diagnose / Drug',
    LABEL_AFTERCARE: 'Aftercare',
    LABEL_STATUS: 'Status',
    LABEL_LAST_NAME_FIRST_NAME_DOB: 'Last Name, First Name',
    LABEL_INVALID_DELIVERY_TIME: 'Delivery time to must be greater than or equal to delivery time from',
    LABEL_LAST_USED: 'LAST USED',
    OP1: 'Treatment planned',
    OP3: 'Overdue',
    OP4: 'Deleted',
    MO1: 'Drug ordered',
    MO2: 'Order confirmed',
    MO3: 'Order shipped',
    MO4: 'Order rejected',
    MO6: 'Cancelled ({{ "MO1" | translate }})',
    LABEL_NO_DRUGS_ORDERED: 'No drug ordered',
    LABEL_PLEASE_ENTER_VALID_TIME: 'Please enter valid time',
    LABEL_ORDERED_PLANNED: 'Treatment planned & drug ordered',
    LABEL_INVALID_DELIVERY_DATE: 'Delivery time can\'t be past treatment date.',
    LABEL_CASE_SUBMITTED: 'Case submitted',
    LABEL_PLEASE_ENTER_PASSWORD_TO_SUBMIT_CASE: 'Please enter your password in order to submit case for settlement.',
    LABEL_CANCEL_BOTH_ORDER_AND_TREATMENT: 'Cancel both treatment and order',
    LABEL_CANCEL_DRUG_ORDER_ONLY: 'Bestellung stornieren',
    LABEL_CONTENT_CANCEL_BOTH: 'Would you like to cancel both treatment and order?',
    LABEL_CONTENT_CANCEL_TREATMENT: 'Are you sure you want to cancel the scheduled treatment?',
    LABEL_CONTENT_CANCEL_ORDER: 'Are you sure you want to cancel the order?',
    LABEL_TITLE_CANCEL_BOTH: 'What would you like to cancel?',
    LABEL_TITLE_CANCEL_TREATMENT: 'Cancel treatment',
    LABEL_TITLE_CANCEL_ORDER: 'Cancel order',
    LABEL_RADIO_BOTH: 'Cancel both treatment and order',
    LABEL_RADIO_ORDER_ONLY: 'Cancel only order',
    LABEL_EDIT_PATIENT_DATA: 'Check patient data',
    LABEL_MULTI_EDIT_ELIGIBILITY: '{{eligibile_cases}} of {{total_cases}} will not be edited, since they are not eligible for submission. Continue?',
    LABEL_MULTI_SUBMIT_ELIGIBILITY: '{{eligibile_cases}} of {{total_cases}} will not be submitted, since they are not eligible for submission. Continue?',
    LABEL_MULTI_SETTLEMENT_ELIGIBILITY: '{{eligibile_cases}} of {{total_cases}} selected cases will not be changed, since they are not eligible. Continue?',
    LABEL_NO_ITEMS_FOR_EDIT: 'Selected cases will not be changed, since they are not eligible.',
    LABEL_CASE_CANNOT_MULTI_EDIT: 'You cannot multi edit/submit this case since it\'s order only',
    LABEL_ADD_NEW_AFTERCARE_DOCTOR: 'Add new aftercare doctor',
    LABEL_CANCEL_OCT_FIRST: 'Case has a pending OCT attached and there is not another IVOM to transfer OCT to. Please cancel the pending OCT first and then try to change the localization again.',

    LABEL_MULTI_EDIT_SETTLEMENT: '  cases updated',
    LABEL_SCHEDULED: 'Scheduled',
    LABEL_OVERDUE2: 'Overdue',
    LABEL_REJECTED: 'Unassigned',
    LABEL_CANCELED_DELETED: 'Deleted',
    LABEL_TREATMENT_WITH_ORDER: 'Treatments with Orders',
    LABEL_ORDERS: 'Orders',
    LABEL_TREATMENTS: 'Treatments',

    ORDER_PLACED: 'when only order created and is sent to shopping cart.',
    ORDER_CONFIRMED: 'when quick order is used.',
    TREATMENT_PLANNED_AND_ORDER_PLACED: 'when treatment is planned and order is sent to shopping cart.',
    TREATMENT_PLANNED_AND_ORDER_CONFIRMED: 'when treatment is planned and quick order is used.',

    //***BUTTONS***//
    BUTTON_CANCEL_CASE_CANCEL: 'No',
    BUTTON_CANCEL_CASE_CONFIRM: 'Yes',
    MO10: 'Externally ordered',
};