INSERT INTO 
	hec_patient_prescription_transactions
	(
		HEC_Patient_Prescription_TransactionID,
		PerscriptionTransaction_DeliveryAddress_RefID,
		PrescriptionTransaction_Patient_RefID,
		PrescriptionTransaction_InternalNubmer,
		PrescriptionTransaction_IsComplete,
		PrescriptionTransaction_RequestedDateOfDeliveryFrom,
		PrescriptionTransaction_RequestedDateOfDeliveryTo,
		PrescriptionTransaction_CreatedByBusinessParticpant_RefID,
		PrescriptionTransaction_Comment,
		PrescriptionTransaction_UsePatientAddress,
		PrescriptionTransaction_UseReceiptAddress,
		PrescriptionTransaction_UseParticipationPolicyAddress,
		Creation_Timestamp,
		IsDeleted,
		Tenant_RefID
	)
VALUES 
	(
		@HEC_Patient_Prescription_TransactionID,
		@PerscriptionTransaction_DeliveryAddress_RefID,
		@PrescriptionTransaction_Patient_RefID,
		@PrescriptionTransaction_InternalNubmer,
		@PrescriptionTransaction_IsComplete,
		@PrescriptionTransaction_RequestedDateOfDeliveryFrom,
		@PrescriptionTransaction_RequestedDateOfDeliveryTo,
		@PrescriptionTransaction_CreatedByBusinessParticpant_RefID,
		@PrescriptionTransaction_Comment,
		@PrescriptionTransaction_UsePatientAddress,
		@PrescriptionTransaction_UseReceiptAddress,
		@PrescriptionTransaction_UseParticipationPolicyAddress,
		@Creation_Timestamp,
		@IsDeleted,
		@Tenant_RefID
	)