INSERT INTO 
	cmn_account_applicationsubscriptions
	(
		CMN_Account_ApplicationSubscriptionID,
		ExternalSubscriptionID,
		Application_RefID,
		Account_RefID,
		UpdatedOn,
		IsDisabled,
		IfDisabled_Reason,
		Configuration,
		Tenant_RefID,
		Creation_Timestamp,
		IsDeleted
	)
VALUES 
	(
		@CMN_Account_ApplicationSubscriptionID,
		@ExternalSubscriptionID,
		@Application_RefID,
		@Account_RefID,
		@UpdatedOn,
		@IsDisabled,
		@IfDisabled_Reason,
		@Configuration,
		@Tenant_RefID,
		@Creation_Timestamp,
		@IsDeleted
	)