UPDATE 
	res_str_outdoorfacility_requiredactions
SET 
	OutdoorFacilityPropertyAssestment_RefID=@OutdoorFacilityPropertyAssestment_RefID,
	SelectedActionVersion_RefID=@SelectedActionVersion_RefID,
	EffectivePrice_RefID=@EffectivePrice_RefID,
	Action_PricePerUnit_RefID=@Action_PricePerUnit_RefID,
	Action_Unit_RefID=@Action_Unit_RefID,
	Action_UnitAmount=@Action_UnitAmount,
	IsCustom=@IsCustom,
	IfCustom_Name=@IfCustom_Name,
	IfCustom_Description=@IfCustom_Description,
	Creation_Timestamp=@Creation_Timestamp,
	IsDeleted=@IsDeleted,
	Tenant_RefID=@Tenant_RefID,
	Action_Timeframe_RefID=@Action_Timeframe_RefID,
	Comment=@Comment
WHERE 
	RES_STR_OutdoorFacility_RequiredActionID = @RES_STR_OutdoorFacility_RequiredActionID