UPDATE 
	ord_cuo_rfp_issuedproposalresponseposition_2_cuo_position
SET 
	ORD_CUO_RFP_IssuedProposalResponse_Position_RefID=@ORD_CUO_RFP_IssuedProposalResponse_Position_RefID,
	ORD_CUO_CustomerOrder_Position_RefID=@ORD_CUO_CustomerOrder_Position_RefID,
	Creation_Timestamp=@Creation_Timestamp,
	Tenant_RefID=@Tenant_RefID,
	IsDeleted=@IsDeleted
WHERE 
	AssignmentID = @AssignmentID