INSERT INTO 
	mrs_run_measurement_values
	(
		MRS_RUN_Measurement_ValueID,
		Measurement_RefID,
		MeasurementValue,
		MeasurementTariff_RefID,
		MeasuredAt_Time,
		MeasuredAt_Lattitude,
		MeasuredAt_Longitude,
		Measurement_AcquisitionType_RefID,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@MRS_RUN_Measurement_ValueID,
		@Measurement_RefID,
		@MeasurementValue,
		@MeasurementTariff_RefID,
		@MeasuredAt_Time,
		@MeasuredAt_Lattitude,
		@MeasuredAt_Longitude,
		@Measurement_AcquisitionType_RefID,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)