INSERT INTO 
	cmn_pro_product_suppliers
	(
		CMN_PRO_Product_SupplierID,
		CMN_PRO_Product_RefID,
		CMN_PRO_Product_Variant_RefID,
		CMN_PRO_Product_Release_RefID,
		CMN_BPT_Supplier_RefID,
		SupplierPriority,
		MinimalPackageOrderingAmount,
		BatchOrderSize,
		ProcurementPrice_RefID,
		RecommendedRetailPrice_RefID,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted
	)
VALUES 
	(
		@CMN_PRO_Product_SupplierID,
		@CMN_PRO_Product_RefID,
		@CMN_PRO_Product_Variant_RefID,
		@CMN_PRO_Product_Release_RefID,
		@CMN_BPT_Supplier_RefID,
		@SupplierPriority,
		@MinimalPackageOrderingAmount,
		@BatchOrderSize,
		@ProcurementPrice_RefID,
		@RecommendedRetailPrice_RefID,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted
	)