INSERT INTO 
	hec_cmt_groupsubscription_requests
	(
		HEC_CMT_GroupSubscription_RequestID,
		Membership_RefID,
		CommunityGroup_RefID,
		RequestComment,
		IsRequested,
		IsRejected,
		IfRejected_ByMember_RefID,
		IfRejected_Reason,
		IsApproved,
		IfApproved_GroupSubscription_RefID,
		IfApproved_ByMember_RefID,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@HEC_CMT_GroupSubscription_RequestID,
		@Membership_RefID,
		@CommunityGroup_RefID,
		@RequestComment,
		@IsRequested,
		@IsRejected,
		@IfRejected_ByMember_RefID,
		@IfRejected_Reason,
		@IsApproved,
		@IfApproved_GroupSubscription_RefID,
		@IfApproved_ByMember_RefID,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)