INSERT INTO 
	cmn_qst_questionitem_standardanswertypes
	(
		CMN_QST_QuestionItem_StandardAnswerTypeID,
		IsBoolean,
		IsNumber,
		IfNumber_IsInteger,
		IfNumber_Min_Inclusive,
		IfNumber_Max_Exclusive,
		IsShortText,
		IfShortText_MaxLength,
		IsLongText,
		Creation_Timestamp,
		IsDeleted,
		Tenant_RefID
	)
VALUES 
	(
		@CMN_QST_QuestionItem_StandardAnswerTypeID,
		@IsBoolean,
		@IsNumber,
		@IfNumber_IsInteger,
		@IfNumber_Min_Inclusive,
		@IfNumber_Max_Exclusive,
		@IsShortText,
		@IfShortText_MaxLength,
		@IsLongText,
		@Creation_Timestamp,
		@IsDeleted,
		@Tenant_RefID
	)