INSERT INTO 
	hec_patient_parametervalues
	(
		HEC_Patient_ParameterValueID,
		Patient_RefID,
		PatientParameter_RefID,
		DateOfValue,
		IsConfirmed,
		ConfirmedBy_Doctor_RefID,
		EnteredBy_Doctor_RefID,
		DateOfEntry,
		StringValue,
		FloatValue,
		Creation_Timestamp,
		Tenant_RefID,
		IsDeleted,
		Modification_Timestamp
	)
VALUES 
	(
		@HEC_Patient_ParameterValueID,
		@Patient_RefID,
		@PatientParameter_RefID,
		@DateOfValue,
		@IsConfirmed,
		@ConfirmedBy_Doctor_RefID,
		@EnteredBy_Doctor_RefID,
		@DateOfEntry,
		@StringValue,
		@FloatValue,
		@Creation_Timestamp,
		@Tenant_RefID,
		@IsDeleted,
		@Modification_Timestamp
	)