INSERT INTO 
	res_str_hvacr_requiredactions
	(
		RES_STR_HVACR_RequiredActionID,
		HVACRPropertyAssestment_RefID,
		SelectedActionVersion_RefID,
		EffectivePrice_RefID,
		Action_PricePerUnit_RefID,
		Action_Unit_RefID,
		Action_UnitAmount,
		IsCustom,
		IfCustom_Name,
		IfCustom_Description,
		Creation_Timestamp,
		IsDeleted,
		Tenant_RefID,
		Action_Timeframe_RefID,
		Comment
	)
VALUES 
	(
		@RES_STR_HVACR_RequiredActionID,
		@HVACRPropertyAssestment_RefID,
		@SelectedActionVersion_RefID,
		@EffectivePrice_RefID,
		@Action_PricePerUnit_RefID,
		@Action_Unit_RefID,
		@Action_UnitAmount,
		@IsCustom,
		@IfCustom_Name,
		@IfCustom_Description,
		@Creation_Timestamp,
		@IsDeleted,
		@Tenant_RefID,
		@Action_Timeframe_RefID,
		@Comment
	)